CREATE TABLE "zeval_arena_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"arena" text NOT NULL,
	"variant_id" text NOT NULL,
	"variant_key" text NOT NULL,
	"variant_metadata" jsonb,
	"model_id" text NOT NULL,
	"model_name" text NOT NULL,
	"organization" text NOT NULL,
	"license" text NOT NULL,
	"is_open_source" boolean DEFAULT false NOT NULL,
	"announcement_date" text NOT NULL,
	"mu" real NOT NULL,
	"sigma" real NOT NULL,
	"conservative_rating" real NOT NULL,
	"rating_change_7d" real,
	"matches_played" integer NOT NULL,
	"wins" integer NOT NULL,
	"win_rate" real NOT NULL,
	"input_price" real,
	"output_price" real,
	"avg_generation_price" real,
	"priced_generations" integer,
	"throughput_cps" real,
	"avg_ttfb" real,
	"zeval_created_at" text,
	"zeval_updated_at" text,
	"snapshotted_at" timestamp with time zone NOT NULL,
	CONSTRAINT "zeval_arena_entries_arena_variant_unique" UNIQUE("arena","variant_id")
);
--> statement-breakpoint
CREATE TABLE "zeval_base_models" (
	"model_id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"organization" text NOT NULL,
	"organization_id" text NOT NULL,
	"organization_country" text,
	"params" real,
	"training_tokens" real,
	"context" integer,
	"canonical_model_id" text,
	"is_moe" boolean,
	"multimodal" boolean DEFAULT false NOT NULL,
	"release_date" text,
	"announcement_date" text NOT NULL,
	"license" text NOT NULL,
	"knowledge_cutoff" text,
	"input_price" text,
	"output_price" text,
	"throughput" text,
	"latency" text,
	"aime_2025_score" real,
	"hle_score" real,
	"gpqa_score" real,
	"swe_bench_verified_score" real,
	"mmmu_score" real,
	"simpleqa_score" real,
	"osworld_score" real,
	"browsecomp_score" real,
	"toolathlon_score" real,
	"terminal_bench_score" real,
	"tau_bench_retail_score" real,
	"arc_agi_v2_score" real,
	"mmmlu_score" real,
	"charxiv_r_score" real,
	"mmmu_pro_score" real,
	"screenspot_pro_score" real,
	"mcp_atlas_score" real,
	"frontiermath_score" real,
	"mrcr_v2_score" real,
	"scicode_score" real,
	"apex_agents_score" real,
	"swe_bench_pro_score" real,
	"chat_arena_score" real,
	"text_to_website_score" real,
	"threejs_score" real,
	"text_to_game_score" real,
	"p5_animation_score" real,
	"text_to_svg_score" real,
	"dataviz_score" real,
	"tonejs_score" real,
	"snapshotted_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX "zeval_arena_entries_arena_idx" ON "zeval_arena_entries" USING btree ("arena");--> statement-breakpoint
CREATE INDEX "zeval_arena_entries_model_id_idx" ON "zeval_arena_entries" USING btree ("model_id");--> statement-breakpoint
CREATE INDEX "zeval_base_models_org_id_idx" ON "zeval_base_models" USING btree ("organization_id");