import type { AssembledAgentRow } from '@/hooks/use-leaderboard-query';

// Tessera v0 shared fixture — the legal (harness × model) 2×2 matrix.
// Mirrors the contract (§4) verbatim. Used by the leaderboard UI so this lane
// stays independent of the engine/DB. The API replaces this with a real DB read
// once Lane C's persistence path is wired in (see app/api/leaderboard/route.ts).
export const LEGAL_LEADERBOARD_FIXTURE: AssembledAgentRow[] = [
  {
    runId: 'fix-1',
    agentName: 'OMC Legal',
    harness: 'oh-my-claudecode',
    baseModel: 'ollama/qwen3:14b',
    organization: 'Tessera',
    domain: 'legal',
    suite: 'legal_contract_review',
    f1: 0.71,
    passAt1: 0.68,
    passHatK: 0.39,
    k: 4,
    costUsd: 0.0,
    latencyMs: 52000,
    totalTokens: 24100,
    createdAt: '2026-06-20T00:00:00Z',
  },
  {
    runId: 'fix-2',
    agentName: 'OMC Legal',
    harness: 'oh-my-claudecode',
    baseModel: 'ollama/qwen3:8b',
    organization: 'Tessera',
    domain: 'legal',
    suite: 'legal_contract_review',
    f1: 0.63,
    passAt1: 0.6,
    passHatK: 0.3,
    k: 4,
    costUsd: 0.0,
    latencyMs: 38000,
    totalTokens: 19800,
    createdAt: '2026-06-20T00:00:00Z',
  },
  {
    runId: 'fix-3',
    agentName: 'Bare agent.md',
    harness: 'bare-agent.md',
    baseModel: 'ollama/qwen3:14b',
    organization: 'Tessera',
    domain: 'legal',
    suite: 'legal_contract_review',
    f1: 0.55,
    passAt1: 0.52,
    passHatK: 0.24,
    k: 4,
    costUsd: 0.0,
    latencyMs: 31000,
    totalTokens: 12300,
    createdAt: '2026-06-20T00:00:00Z',
  },
  {
    runId: 'fix-4',
    agentName: 'Bare agent.md',
    harness: 'bare-agent.md',
    baseModel: 'ollama/qwen3:8b',
    organization: 'Tessera',
    domain: 'legal',
    suite: 'legal_contract_review',
    f1: 0.48,
    passAt1: 0.45,
    passHatK: 0.18,
    k: 4,
    costUsd: 0.0,
    latencyMs: 22000,
    totalTokens: 9800,
    createdAt: '2026-06-20T00:00:00Z',
  },
];
