import type { ChatModelCard } from '../types';

const anthropicModels: ChatModelCard[] = [
  {
    id: 'claude-opus-4-6',
    displayName: 'Claude Opus 4.6',
    description:
      'Claude Opus 4.6 是 Anthropic 最新旗舰模型，具备自适应思考、百万级上下文窗口和增强的编程代理能力。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 128_000,
    enabled: true,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
    },
    pricing: {
      input: 5,
      output: 25,
      cachedInput: 1.5,
    },
    releasedAt: '2026-02-05',
  },
  {
    id: 'claude-opus-4-5-20251101',
    displayName: 'Claude Opus 4.5',
    description: 'Claude Opus 4.5 是 Anthropic 最强大的模型，具备顶级推理、搜索和结构化输出能力。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
    },
    pricing: {
      input: 5,
      output: 25,
      cachedInput: 1.5,
    },
    releasedAt: '2025-11-24',
  },
  {
    id: 'claude-sonnet-4-5-20250929',
    displayName: 'Claude Sonnet 4.5',
    description: 'Claude Sonnet 4.5 在智能和速度之间取得最佳平衡，是日常任务的理想选择。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
    },
    pricing: {
      input: 3,
      output: 15,
      cachedInput: 0.3,
    },
    releasedAt: '2025-09-29',
  },
  {
    id: 'claude-haiku-4-5-20251001',
    displayName: 'Claude Haiku 4.5',
    description: 'Claude Haiku 4.5 是最快速、最具成本效益的 Claude 4 系列模型。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
    },
    pricing: {
      input: 0.8,
      output: 4,
      cachedInput: 0.08,
    },
    releasedAt: '2025-10-01',
  },
  {
    id: 'claude-opus-4-1-20250805',
    displayName: 'Claude Opus 4.1',
    description: 'Claude Opus 4.1 是 Anthropic 最强大的 4.1 系列模型，具备顶级推理能力。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 32_000,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
    },
    pricing: {
      input: 15,
      output: 75,
      cachedInput: 1.5,
    },
    releasedAt: '2025-08-05',
  },
  {
    id: 'claude-opus-4-20250514',
    displayName: 'Claude Opus 4',
    description: 'Claude Opus 4 具备强大的推理、视觉和搜索能力。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 32_000,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
    },
    pricing: {
      input: 15,
      output: 75,
      cachedInput: 1.5,
    },
    releasedAt: '2025-05-14',
  },
  {
    id: 'claude-sonnet-4-20250514',
    displayName: 'Claude Sonnet 4',
    description: 'Claude Sonnet 4 在智能、速度和成本之间达到平衡。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    abilities: {
      functionCall: true,
      vision: true,
      reasoning: true,
      search: true,
    },
    pricing: {
      input: 3,
      output: 15,
      cachedInput: 0.3,
    },
    releasedAt: '2025-05-14',
  },
  {
    id: 'claude-3-7-sonnet-20250219',
    displayName: 'Claude 3.7 Sonnet',
    description: 'Claude 3.7 Sonnet 是强大的多模态模型，支持视觉理解、推理和搜索能力。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      vision: true,
    },
    pricing: {
      input: 3,
      output: 15,
      cachedInput: 0.3,
    },
    releasedAt: '2025-02-19',
  },
  {
    id: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet',
    description: 'Claude 3.5 Sonnet 是高性能的多功能模型，适合各种复杂任务。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    enabled: true,
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      input: 3,
      output: 15,
      cachedInput: 0.3,
    },
    releasedAt: '2024-10-22',
  },
  {
    id: 'claude-3-5-sonnet-20240620',
    displayName: 'Claude 3.5 Sonnet (June)',
    description: 'Claude 3.5 Sonnet 2024年6月版本。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      input: 3,
      output: 15,
      cachedInput: 0.3,
    },
    releasedAt: '2024-06-20',
    legacy: true,
  },
  {
    id: 'claude-3-5-haiku-20241022',
    displayName: 'Claude 3.5 Haiku',
    description: 'Claude 3.5 Haiku 是快速且经济的选择，适合高吞吐量场景。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    enabled: true,
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      input: 0.8,
      output: 4,
      cachedInput: 0.08,
    },
    releasedAt: '2024-10-22',
  },
  {
    id: 'claude-3-opus-20240229',
    displayName: 'Claude 3 Opus',
    description: 'Claude 3 Opus 是 Claude 3 系列中最强大的模型。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      input: 15,
      output: 75,
      cachedInput: 1.5,
    },
    releasedAt: '2024-02-29',
  },
  {
    id: 'claude-3-sonnet-20240229',
    displayName: 'Claude 3 Sonnet',
    description: 'Claude 3 Sonnet 在性能和成本之间取得平衡。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      input: 3,
      output: 15,
    },
    releasedAt: '2024-02-29',
  },
  {
    id: 'claude-3-haiku-20240307',
    displayName: 'Claude 3 Haiku',
    description: 'Claude 3 Haiku 是快速、紧凑的模型，适合即时响应场景。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      vision: true,
    },
    pricing: {
      input: 0.25,
      output: 1.25,
    },
    releasedAt: '2024-03-07',
  },
];

export default anthropicModels;
