import type { ChatModelCard } from '../types';

const bedrockModels: ChatModelCard[] = [
  {
    id: 'global.anthropic.claude-opus-4-5-20251101-v1:0',
    displayName: 'Claude Opus 4.5',
    description:
      'Claude Opus 4.5 是 Anthropic 的旗舰模型，结合了卓越的智能与可扩展性能，适合需要最高质量回应和推理能力的复杂任务。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 5, output: 25, cachedInput: 0.5 },
    releasedAt: '2025-11-24',
  },
  {
    id: 'us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    displayName: 'Claude Sonnet 4.5',
    description: 'Claude Sonnet 4.5 是 Anthropic 迄今为止最智能的模型。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { currency: 'USD', input: 3, output: 15 },
    releasedAt: '2025-09-29',
  },
  {
    id: 'us.anthropic.claude-haiku-4-5-20251001-v1:0',
    displayName: 'Claude Haiku 4.5',
    description:
      'Claude Haiku 4.5 是 Anthropic 最快且最智能的 Haiku 模型，具有闪电般的速度和扩展思考能力。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { currency: 'USD', input: 1, output: 5 },
    releasedAt: '2025-10-15',
  },
  {
    id: 'us.anthropic.claude-3-7-sonnet-20250219-v1:0',
    displayName: 'Claude 3.7 Sonnet',
    description:
      'Claude 3.7 Sonnet 是 Anthropic 最快的下一代模型。与 Claude 3 Haiku 相比，Claude 3.7 Sonnet 在各项技能上都有所提升，并在许多智力基准测试中超越了上一代最大的模型 Claude 3 Opus。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 3, output: 15 },
    releasedAt: '2025-02-24',
  },
  {
    id: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    displayName: 'Claude 3.5 Sonnet',
    description:
      'Claude 3.5 Sonnet 提升了行业标准，性能超过竞争对手模型和 Claude 3 Opus，在广泛的评估中表现出色。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3, output: 15 },
    releasedAt: '2024-10-22',
  },
  {
    id: 'us.anthropic.claude-3-5-sonnet-20241022-v2:0',
    displayName: 'Claude 3.5 Sonnet v2 (Inference profile)',
    description:
      'Claude 3.5 Sonnet 提升了行业标准，性能超过竞争对手模型和 Claude 3 Opus，在广泛的评估中表现出色。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3, output: 15 },
    releasedAt: '2024-10-22',
  },
  {
    id: 'anthropic.claude-3-5-sonnet-20240620-v1:0',
    displayName: 'Claude 3.5 Sonnet 0620',
    description:
      'Claude 3.5 Sonnet 提升了行业标准，性能超过竞争对手模型和 Claude 3 Opus，在广泛的评估中表现出色。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3, output: 15 },
    releasedAt: '2024-06-20',
  },
  {
    id: 'anthropic.claude-3-haiku-20240307-v1:0',
    displayName: 'Claude 3 Haiku',
    description:
      'Claude 3 Haiku 是 Anthropic 最快、最紧凑的模型，提供近乎即时的响应速度。它可以快速回答简单的查询和请求。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.25, output: 1.25 },
    releasedAt: '2024-03-07',
  },
  {
    id: 'anthropic.claude-3-sonnet-20240229-v1:0',
    displayName: 'Claude 3 Sonnet',
    description:
      'Anthropic 的 Claude 3 Sonnet 在智能和速度之间达到了理想的平衡——特别适合企业工作负载。',
    type: 'chat',
    contextWindowTokens: 200_000,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3, output: 15 },
  },
  {
    id: 'anthropic.claude-3-opus-20240229-v1:0',
    displayName: 'Claude 3 Opus',
    description: 'Claude 3 Opus 是 Anthropic 最强大的 AI 模型，具有在高度复杂任务上的最先进性能。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: { functionCall: true },
    pricing: { input: 15, output: 75 },
    releasedAt: '2024-02-29',
  },
  {
    id: 'anthropic.claude-v2:1',
    displayName: 'Claude 2.1',
    description:
      'Claude 2 的更新版，具有双倍的上下文窗口，以及在长文档和 RAG 上下文中的可靠性、幻觉率和基于证据的准确性的改进。',
    type: 'chat',
    contextWindowTokens: 200_000,
    pricing: { input: 8, output: 24 },
  },
  {
    id: 'anthropic.claude-v2',
    displayName: 'Claude 2.0',
    description:
      'Anthropic 在从复杂对话和创意内容生成到详细指令跟随的广泛任务中都表现出高度能力的模型。',
    type: 'chat',
    contextWindowTokens: 100_000,
    pricing: { input: 8, output: 24 },
  },
  {
    id: 'anthropic.claude-instant-v1',
    displayName: 'Claude Instant',
    description:
      '一款快速、经济且仍然非常有能力的模型，可以处理包括日常对话、文本分析、总结和文档问答在内的一系列任务。',
    type: 'chat',
    contextWindowTokens: 100_000,
    maxOutput: 4_096,
    pricing: { input: 0.8, output: 2.4 },
  },
  {
    id: 'meta.llama3-1-8b-instruct-v1:0',
    displayName: 'Llama 3.1 8B Instruct',
    description:
      'Meta Llama 3.1 8B Instruct 的更新版，包括扩展的 128K 上下文长度、多语言性和改进的推理能力。',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { input: 0.22, output: 0.22 },
  },
  {
    id: 'meta.llama3-1-70b-instruct-v1:0',
    displayName: 'Llama 3.1 70B Instruct',
    description:
      'Meta Llama 3.1 70B Instruct 的更新版，包括扩展的 128K 上下文长度、多语言性和改进的推理能力。',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { input: 0.99, output: 0.99 },
  },
  {
    id: 'meta.llama3-1-405b-instruct-v1:0',
    displayName: 'Llama 3.1 405B Instruct',
    description:
      'Meta Llama 3.1 405B Instruct 是 Llama 3.1 Instruct 模型中最大、最强大的模型，是一款高度先进的对话推理和合成数据生成模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { input: 5.32, output: 16 },
  },
  {
    id: 'meta.llama3-8b-instruct-v1:0',
    displayName: 'Llama 3 8B Instruct',
    description:
      'Meta Llama 3 是一款面向开发者、研究人员和企业的开放大型语言模型，非常适合计算能力和资源有限、边缘设备和更快的训练时间。',
    type: 'chat',
    contextWindowTokens: 8_000,
    pricing: { input: 0.3, output: 0.6 },
  },
  {
    id: 'meta.llama3-70b-instruct-v1:0',
    displayName: 'Llama 3 70B Instruct',
    description:
      'Meta Llama 3 是一款面向开发者、研究人员和企业的开放大型语言模型，非常适合内容创建、对话 AI、语言理解、研发和企业应用。',
    type: 'chat',
    contextWindowTokens: 8_000,
    pricing: { input: 2.65, output: 3.5 },
  },
  {
    id: 'global.anthropic.claude-opus-4-7',
    displayName: 'Claude Opus 4.7',
    description:
      "Claude Opus 4.7 is Anthropic's most capable generally available model for complex reasoning and agentic coding.",
    type: 'chat',
    contextWindowTokens: 1_000_000,
    maxOutput: 128_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 5, output: 25, cachedInput: 0.5 },
    releasedAt: '2026-04-16',
  },
  {
    id: 'global.anthropic.claude-opus-4-6-v1',
    displayName: 'Claude Opus 4.6',
    description:
      "Claude Opus 4.6 is Anthropic's most intelligent model for building agents and coding.",
    type: 'chat',
    contextWindowTokens: 1_000_000,
    maxOutput: 128_000,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 5, output: 25, cachedInput: 0.5 },
    releasedAt: '2026-02-05',
  },
  {
    id: 'global.anthropic.claude-sonnet-4-6',
    displayName: 'Claude Sonnet 4.6',
    description: 'Claude Sonnet 4.6 is Anthropic’s best combination of speed and intelligence.',
    type: 'chat',
    contextWindowTokens: 1_000_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 3, output: 15, cachedInput: 0.3 },
    releasedAt: '2026-02-17',
  },
  {
    id: 'global.anthropic.claude-sonnet-4-5-20250929-v1:0',
    displayName: 'Claude Sonnet 4.5',
    description: "Claude Sonnet 4.5 is Anthropic's most intelligent model to date.",
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 3, output: 15 },
    releasedAt: '2025-09-29',
  },
  {
    id: 'global.anthropic.claude-haiku-4-5-20251001-v1:0',
    displayName: 'Claude Haiku 4.5',
    description:
      "Claude Haiku 4.5 is Anthropic's fastest and most intelligent Haiku model, with lightning speed and extended thinking.",
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 64_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 1, output: 5 },
    releasedAt: '2025-10-15',
  },
];

export default bedrockModels;
