import type { ChatModelCard } from '../types';

const githubModels: ChatModelCard[] = [
  {
    id: 'openai/o4-mini',
    displayName: 'o4-mini',
    description: 'OpenAI最新小型推理模型，编程视觉任务高效高性能。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 100_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { input: 1.1, output: 4.4, cachedInput: 0.275 },
    releasedAt: '2025-04-17',
  },
  {
    id: 'openai/gpt-4.1',
    displayName: 'GPT-4.1',
    description: 'OpenAI复杂任务旗舰模型，跨领域问题解决能力强。',
    type: 'chat',
    contextWindowTokens: 1_047_576,
    maxOutput: 32_768,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 2, output: 8, cachedInput: 0.5 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'openai/gpt-4.1-mini',
    displayName: 'GPT-4.1 mini',
    description: 'GPT-4.1迷你版，智能速度成本平衡。',
    type: 'chat',
    contextWindowTokens: 1_047_576,
    maxOutput: 32_768,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.4, output: 1.6, cachedInput: 0.1 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'openai/o3-mini',
    displayName: 'o3-mini',
    description: 'OpenAI最新小型推理模型，与o1-mini同成本延迟提供高智能。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 100_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 1.1, output: 4.4, cachedInput: 0.55 },
    releasedAt: '2025-01-31',
  },
  {
    id: 'openai/o1',
    displayName: 'o1',
    description: 'OpenAI推理模型，支持图文输入，适合复杂任务。',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 100_000,
    abilities: { reasoning: true, vision: true },
    pricing: { input: 15, output: 60, cachedInput: 7.5 },
    releasedAt: '2024-12-17',
  },
  {
    id: 'openai/gpt-4o',
    displayName: 'GPT-4o',
    description: 'OpenAI GPT-4系列最先进多模态模型。',
    type: 'chat',
    contextWindowTokens: 134_144,
    maxOutput: 16_384,
    abilities: { functionCall: true, vision: true },
  },
  {
    id: 'openai/gpt-4o-mini',
    displayName: 'GPT-4o mini',
    description: 'OpenAI经济高效AI解决方案，适用多种任务。',
    type: 'chat',
    contextWindowTokens: 134_144,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true },
  },
  {
    id: 'xai/grok-3',
    displayName: 'Grok 3',
    description: 'xAI Grok 3模型，支持函数调用。',
    type: 'chat',
    contextWindowTokens: 134_144,
    maxOutput: 4_096,
    abilities: { functionCall: true },
  },
  {
    id: 'deepseek/DeepSeek-R1',
    displayName: 'DeepSeek R1',
    description: 'DeepSeek推理模型，GitHub托管版本。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: { reasoning: true },
  },
  {
    id: 'deepseek/DeepSeek-V3-0324',
    displayName: 'DeepSeek V3',
    description: 'DeepSeek V3通用模型，GitHub托管版本。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: { functionCall: true },
  },
  {
    id: 'meta/Llama-3.3-70B-Instruct',
    displayName: 'Llama 3.3 70B Instruct',
    description: 'Meta Llama 3.3多语言开源模型，性能媲美405B。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'meta/Meta-Llama-3.1-405B-Instruct',
    displayName: 'Meta Llama 3.1 405B',
    description: 'Meta Llama 3.1最大版本，GitHub托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-ai/Mistral-Large-2411',
    displayName: 'Mistral Large',
    description: 'Mistral旗舰模型，适合复杂任务和代码生成。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-4',
    displayName: 'Phi 4',
    description: 'Microsoft Phi-4模型，16K上下文。',
    type: 'chat',
    contextWindowTokens: 16_384,
    maxOutput: 16_384,
  },
  {
    id: 'openai/o3',
    displayName: 'o3',
    description: 'o3 is a powerful general-purpose model that excels across domains.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 100_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { input: 10, output: 40, cachedInput: 2.5 },
    releasedAt: '2025-04-17',
  },
  {
    id: 'openai/gpt-4.1-nano',
    displayName: 'GPT-4.1 nano',
    description: 'GPT-4.1 nano is the fastest and most cost-effective GPT-4.1 model.',
    type: 'chat',
    contextWindowTokens: 1_047_576,
    maxOutput: 32_768,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.1, output: 0.4, cachedInput: 0.025 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'openai/o1-mini',
    displayName: 'o1-mini',
    description:
      'o1-mini is a fast, cost-effective reasoning model designed for coding, math, and science use cases.',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 65_536,
    abilities: { reasoning: true },
    pricing: { input: 1.1, output: 4.4, cachedInput: 0.55 },
    releasedAt: '2024-09-12',
  },
  {
    id: 'openai/o1-preview',
    displayName: 'o1-preview',
    description: 'o1 is OpenAI’s new reasoning model for complex tasks requiring broad knowledge.',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 32_768,
    abilities: { reasoning: true },
    pricing: { input: 15, output: 60 },
    releasedAt: '2024-09-12',
  },
  {
    id: 'xai/grok-3-mini',
    displayName: 'Grok 3 mini',
    type: 'chat',
    contextWindowTokens: 134_144,
    maxOutput: 4_096,
    abilities: { functionCall: true, reasoning: true },
  },
  {
    id: 'microsoft/MAI-DS-R1',
    displayName: 'MAI DS R1',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: { reasoning: true },
  },
  {
    id: 'ai21-labs/AI21-Jamba-1.5-Mini',
    displayName: 'AI21 Jamba 1.5 Mini',
    description:
      'A 52B-parameter (12B active) multilingual model with a 256K context window, function calling, structured output, and grounded generation.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 4_096,
    abilities: { functionCall: true },
  },
  {
    id: 'ai21-labs/AI21-Jamba-1.5-Large',
    displayName: 'AI21 Jamba 1.5 Large',
    description:
      'A 398B-parameter (94B active) multilingual model with a 256K context window, function calling, structured output, and grounded generation.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 4_096,
    abilities: { functionCall: true },
  },
  {
    id: 'cohere/Cohere-command-r',
    displayName: 'Cohere Command R',
    description:
      'Command R is a scalable generative model designed for RAG and tool use, enabling production-grade AI.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'cohere/Cohere-command-r-plus',
    displayName: 'Cohere Command R+',
    description: 'Command R+ is an advanced RAG-optimized model built for enterprise workloads.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-ai/Mistral-Nemo',
    displayName: 'Mistral Nemo',
    description:
      'Mistral Nemo is a cutting-edge LLM with state-of-the-art reasoning, world knowledge, and coding for its size.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-ai/mistral-small-2503',
    displayName: 'Mistral Small',
    description:
      'Mistral Small is suitable for any language-based task requiring high efficiency and low latency.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-ai/Codestral-2501',
    displayName: 'Codestral',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 4_096,
  },
  {
    id: 'meta/Llama-3.2-11B-Vision-Instruct',
    displayName: 'Llama 3.2 11B Vision',
    description:
      'Strong image reasoning on high-resolution images, suited for visual understanding apps.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'meta/Llama-3.2-90B-Vision-Instruct',
    displayName: 'Llama 3.2 90B Vision',
    description: 'Advanced image reasoning for visual-understanding agent applications.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'llama-4-Scout-17B-16E-Instruct',
    displayName: 'Meta Llama 4 Scout 17B',
    type: 'chat',
    contextWindowTokens: 10_240_000,
    maxOutput: 4_096,
  },
  {
    id: 'meta/Llama-4-Maverick-17B-128E-Instruct-FP8',
    displayName: 'Meta Llama 4 Maverick 17B',
    type: 'chat',
    contextWindowTokens: 10_240_000,
    maxOutput: 4_096,
  },
  {
    id: 'meta/Meta-Llama-3.1-8B-Instruct',
    displayName: 'Meta Llama 3.1 8B',
    description:
      'Llama 3.1 instruction-tuned text model optimized for multilingual chat, performing strongly on common industry benchmarks among open and closed chat models.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'meta/Meta-Llama-3.1-70B-Instruct',
    displayName: 'Meta Llama 3.1 70B',
    description:
      'Llama 3.1 instruction-tuned text model optimized for multilingual chat, performing strongly on common industry benchmarks among open and closed chat models.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'meta/Meta-Llama-3-8B-Instruct',
    displayName: 'Meta Llama 3 8B',
    description: 'A versatile 8B-parameter model optimized for chat and text generation.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
  },
  {
    id: 'meta/Meta-Llama-3-70B-Instruct',
    displayName: 'Meta Llama 3 70B',
    description:
      'A powerful 70B-parameter model that excels at reasoning, coding, and broad language tasks.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3.5-MoE-instruct',
    displayName: 'Phi 3.5 MoE',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3.5-mini-instruct',
    displayName: 'Phi-3.5-mini 128K',
    description: 'An updated version of the Phi-3-mini model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3.5-vision-instruct',
    displayName: 'Phi-3.5-vision 128K',
    description: 'An updated version of the Phi-3-vision model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'microsoft/Phi-3-mini-4k-instruct',
    displayName: 'Phi-3-mini 4K',
    description: 'The smallest Phi-3 family member, optimized for quality and low latency.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3-mini-128k-instruct',
    displayName: 'Phi-3-mini 128K',
    description:
      'The same Phi-3-mini model with a larger context window for RAG or few-shot prompts.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3-small-8k-instruct',
    displayName: 'Phi-3-small 8K',
    description:
      'A 7B-parameter model with higher quality than Phi-3-mini, focused on high-quality, reasoning-intensive data.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3-small-128k-instruct',
    displayName: 'Phi-3-small 128K',
    description:
      'The same Phi-3-small model with a larger context window for RAG or few-shot prompts.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3-medium-4k-instruct',
    displayName: 'Phi-3-medium 4K',
    description:
      'A 14B-parameter model with higher quality than Phi-3-mini, focused on high-quality, reasoning-intensive data.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_096,
  },
  {
    id: 'microsoft/Phi-3-medium-128k-instruct',
    displayName: 'Phi-3-medium 128K',
    description:
      'The same Phi-3-medium model with a larger context window for RAG or few-shot prompts.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
];

export default githubModels;
