import type { ChatModelCard, ImageModelCard, VideoModelCard } from '../types';

const googleChatModels: ChatModelCard[] = [
  {
    id: 'gemini-3.5-flash',
    displayName: 'Gemini 3.5 Flash',
    description:
      'Gemini 3.5 Flash 是 Gemini 系列为速度打造的最智能模型，兼具前沿智能与卓越的搜索与事实关联能力。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    pricing: { input: 1.5, output: 9, cachedInput: 0.15 },
    releasedAt: '2026-05-19',
  },
  {
    id: 'gemini-3.1-flash-lite',
    displayName: 'Gemini 3.1 Flash-Lite',
    description:
      'Gemini 3.1 Flash-Lite 是 Google 最具性价比的多模态模型，针对高吞吐智能体任务、翻译与数据处理进行优化。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    pricing: { input: 0.25, output: 1.5, cachedInput: 0.025 },
    releasedAt: '2026-05-07',
  },
  {
    id: 'gemini-3.1-pro-preview',
    displayName: 'Gemini 3.1 Pro Preview',
    description:
      'Gemini 3.1 Pro 是 Google 最新的旗舰模型，具备增强的推理、结构化输出和多模态理解能力。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    pricing: { input: 2, output: 12, cachedInput: 0.2 },
    releasedAt: '2026-02-19',
  },
  {
    id: 'gemini-pro-latest',
    displayName: 'Gemini Pro Latest',
    description: 'Latest release of Gemini Pro',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    pricing: { input: 1.25, output: 10, cachedInput: 0.31 },
  },
  {
    id: 'gemini-flash-latest',
    displayName: 'Gemini Flash Latest',
    description: 'Latest release of Gemini Flash',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.3, output: 2.5, cachedInput: 0.075 },
  },
  {
    id: 'gemini-flash-lite-latest',
    displayName: 'Gemini Flash-Lite Latest',
    description: 'Latest release of Gemini Flash-Lite',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.1, output: 0.4, cachedInput: 0.025 },
  },
  {
    id: 'gemini-3-pro-preview',
    displayName: 'Gemini 3 Pro Preview',
    description:
      'Gemini 3 Pro 是全球最佳的多模态理解模型，也是 Google 迄今为止最强大的智能体模型。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    legacy: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 2, output: 12, cachedInput: 0.2 },
    releasedAt: '2025-11-18',
  },
  {
    id: 'gemini-3-pro-image-preview',
    displayName: 'Nano Banana Pro',
    description: 'Gemini 3 Pro Image（Nano Banana Pro）是 Google 的图像生成模型，支持多模态对话。',
    type: 'chat',
    contextWindowTokens: 163_840,
    maxOutput: 32_768,
    enabled: true,
    abilities: { imageOutput: true, reasoning: true, search: true, vision: true },
    pricing: { input: 2, output: 12 },
    releasedAt: '2025-11-20',
  },
  {
    id: 'gemini-3.1-flash-preview',
    displayName: 'Gemini 3.1 Flash Preview',
    description: 'Gemini 3.1 Flash 是 Google 最新的快速多模态模型，具备全面的推理和工具调用能力。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.3, output: 2.5, cachedInput: 0.075 },
    releasedAt: '2026-03-04',
  },
  {
    id: 'gemini-3.1-flash-image-preview',
    displayName: 'Nano Banana Flash',
    description:
      'Gemini 3.1 Flash Image（Nano Banana Flash）是 Google 的快速图像生成模型，支持多模态对话。',
    type: 'chat',
    contextWindowTokens: 163_840,
    maxOutput: 32_768,
    enabled: true,
    abilities: { imageOutput: true, vision: true },
    pricing: { input: 0.25, output: 1.5 },
    releasedAt: '2026-02-26',
  },
  {
    id: 'gemini-3-flash-preview',
    displayName: 'Gemini 3 Flash Preview',
    description: 'Gemini 3 Flash Preview 是 Google 最新的快速多模态模型。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    legacy: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.5, output: 3, cachedInput: 0.05 },
    releasedAt: '2025-12-17',
  },
  {
    id: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    description:
      'Gemini 2.5 Pro 是 Google 最先进的思维模型，能够对代码、数学和 STEM 领域的复杂问题进行推理。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 1.25, output: 10, cachedInput: 0.31 },
    releasedAt: '2025-06-17',
  },
  {
    id: 'gemini-2.5-pro-preview-06-05',
    displayName: 'Gemini 2.5 Pro Preview 06-05',
    description: 'Gemini 2.5 Pro Preview 版本。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 1.25, output: 10, cachedInput: 0.31 },
    releasedAt: '2025-06-05',
  },
  {
    id: 'gemini-2.5-pro-preview-05-06',
    displayName: 'Gemini 2.5 Pro Preview 05-06',
    description: 'Gemini 2.5 Pro Preview 版本。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 1.25, output: 10, cachedInput: 0.31 },
    releasedAt: '2025-05-06',
  },
  {
    id: 'gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    description: 'Gemini 2.5 Flash 是 Google 性价比最高的模型，提供全面的功能。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.3, output: 2.5, cachedInput: 0.075 },
    releasedAt: '2025-06-17',
  },
  {
    id: 'gemini-2.5-flash-preview-09-2025',
    displayName: 'Gemini 2.5 Flash Preview Sep 2025',
    description: 'Preview release (September 25th, 2025) of Gemini 2.5 Flash',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.3, output: 2.5, cachedInput: 0.075 },
    releasedAt: '2025-09-25',
  },
  {
    id: 'gemini-2.5-flash-image',
    displayName: 'Nano Banana',
    description:
      'Nano Banana 是 Google 最新、最快、最高效的原生多模态模型，允许通过对话生成和编辑图像。',
    type: 'chat',
    contextWindowTokens: 98_304,
    maxOutput: 32_768,
    enabled: true,
    abilities: { imageOutput: true, vision: true },
    pricing: { input: 0.3, output: 2.5 },
    releasedAt: '2025-08-26',
  },
  {
    id: 'gemini-2.5-flash-image-preview',
    displayName: 'Nano Banana (Preview)',
    description: 'Nano Banana Preview 版本。',
    type: 'chat',
    contextWindowTokens: 40_960,
    maxOutput: 8_192,
    abilities: { imageOutput: true, vision: true },
    pricing: { input: 0.3, output: 2.5 },
    releasedAt: '2025-08-26',
  },
  {
    id: 'gemini-2.5-flash-lite',
    displayName: 'Gemini 2.5 Flash-Lite',
    description: 'Gemini 2.5 Flash-Lite 是 Google 最小、性价比最高的模型，专为大规模使用而设计。',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.1, output: 0.4, cachedInput: 0.025 },
    releasedAt: '2025-07-22',
  },
  {
    id: 'gemini-2.5-flash-lite-preview-09-2025',
    displayName: 'Gemini 2.5 Flash-Lite Preview Sep 2025',
    description: 'Preview release (September 25th, 2025) of Gemini 2.5 Flash-Lite',
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { input: 0.1, output: 0.4, cachedInput: 0.025 },
    releasedAt: '2025-09-25',
  },
  {
    id: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    description:
      'Gemini 2.0 Flash 提供下一代功能，包括卓越的速度、原生工具使用和 1M 令牌上下文窗口。',
    type: 'chat',
    contextWindowTokens: 1_056_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, search: true, vision: true },
    pricing: { input: 0.1, output: 0.4, cachedInput: 0.025 },
    releasedAt: '2025-02-05',
  },
  {
    id: 'gemini-2.0-flash-001',
    displayName: 'Gemini 2.0 Flash 001',
    description: 'Gemini 2.0 Flash 001 版本。',
    type: 'chat',
    contextWindowTokens: 1_056_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, search: true, vision: true },
    pricing: { input: 0.1, output: 0.4, cachedInput: 0.025 },
    releasedAt: '2025-02-05',
  },
  {
    id: 'gemini-2.0-flash-exp',
    displayName: 'Gemini 2.0 Flash Exp',
    description: 'Gemini 2.0 Flash 实验版本。',
    type: 'chat',
    contextWindowTokens: 1_056_768,
    maxOutput: 8_192,
    enabled: true,
    abilities: { imageOutput: true, functionCall: true, vision: true, structuredOutput: true },
    pricing: { input: 0, output: 0 },
    releasedAt: '2025-02-05',
  },
  {
    id: 'gemini-2.0-flash-exp-image-generation',
    displayName: 'Gemini 2.0 Flash (Image Generation) Experimental',
    description: 'Gemini 2.0 Flash 实验模型，支持图像生成。',
    type: 'chat',
    contextWindowTokens: 1_056_768,
    maxOutput: 8_192,
    abilities: { imageOutput: true, vision: true },
    pricing: { input: 0, output: 0 },
    releasedAt: '2025-03-14',
  },
  {
    id: 'gemini-2.0-flash-lite',
    displayName: 'Gemini 2.0 Flash-Lite',
    description: 'Gemini 2.0 Flash 模型变体，针对成本效益和低延迟优化。',
    type: 'chat',
    contextWindowTokens: 1_056_768,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { input: 0.075, output: 0.3 },
    releasedAt: '2025-02-05',
  },
  {
    id: 'gemini-2.0-flash-lite-001',
    displayName: 'Gemini 2.0 Flash-Lite 001',
    description: 'Gemini 2.0 Flash-Lite 001 版本。',
    type: 'chat',
    contextWindowTokens: 1_056_768,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { input: 0.075, output: 0.3 },
    releasedAt: '2025-02-05',
  },
  {
    id: 'learnlm-2.0-flash-experimental',
    displayName: 'LearnLM 2.0 Flash Experimental',
    description: 'LearnLM 是实验性的语言模型，经过训练以符合学习科学原则，可充当专家导师。',
    type: 'chat',
    contextWindowTokens: 1_081_344,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { input: 0, output: 0 },
  },
  {
    id: 'learnlm-1.5-pro-experimental',
    displayName: 'LearnLM 1.5 Pro Experimental',
    description: 'LearnLM 1.5 Pro 实验版本。',
    type: 'chat',
    contextWindowTokens: 40_959,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { input: 0, output: 0 },
    releasedAt: '2024-11-19',
  },
  {
    id: 'gemini-1.5-pro',
    displayName: 'Gemini 1.5 Pro',
    description: 'Gemini 1.5 Pro 是具有超长上下文窗口的多模态模型。',
    type: 'chat',
    contextWindowTokens: 2_097_152,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true, video: true, structuredOutput: true },
    pricing: { input: 1.25, output: 5 },
  },
  {
    id: 'gemini-1.5-pro-002',
    displayName: 'Gemini 1.5 Pro 002',
    description:
      'Gemini 1.5 Pro 002 是最新的生产就绪模型，在数学、长上下文和视觉任务方面有显著提升。',
    type: 'chat',
    contextWindowTokens: 2_008_192,
    maxOutput: 8_192,
    legacy: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 1.25, output: 5, cachedInput: 0.3125 },
    releasedAt: '2024-09-24',
  },
  {
    id: 'gemini-1.5-flash',
    displayName: 'Gemini 1.5 Flash',
    description: 'Gemini 1.5 Flash 是快速、高效的多模态模型。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true, video: true, structuredOutput: true },
    pricing: { input: 0.075, output: 0.3 },
  },
  {
    id: 'gemini-1.5-flash-002',
    displayName: 'Gemini 1.5 Flash 002',
    description: 'Gemini 1.5 Flash 002 是高效的多模态模型。',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    legacy: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.018 },
    releasedAt: '2024-09-25',
  },
  {
    id: 'gemini-1.5-flash-8b',
    displayName: 'Gemini 1.5 Flash 8B',
    description: 'Gemini 1.5 Flash 8B 是更小、更快的版本。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true, structuredOutput: true },
    pricing: { input: 0.0375, output: 0.15 },
  },
  {
    id: 'gemini-1.5-flash-8b-latest',
    displayName: 'Gemini 1.5 Flash 8B Latest',
    description: 'Gemini 1.5 Flash 8B 最新版本。',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.0375, output: 0.15, cachedInput: 0.01 },
    releasedAt: '2024-10-03',
  },
  {
    id: 'gemma-3-1b-it',
    displayName: 'Gemma 3 1B',
    description: 'Gemma 3 1B 是 Google 开源的小型语言模型。',
    type: 'chat',
    contextWindowTokens: 40_960,
    maxOutput: 8_192,
    pricing: { input: 0, output: 0, cachedInput: 0 },
  },
  {
    id: 'gemma-3-4b-it',
    displayName: 'Gemma 3 4B',
    description: 'Gemma 3 4B 是 Google 开源的小型语言模型。',
    type: 'chat',
    contextWindowTokens: 40_960,
    maxOutput: 8_192,
    pricing: { input: 0, output: 0, cachedInput: 0 },
  },
  {
    id: 'gemma-3-12b-it',
    displayName: 'Gemma 3 12B',
    description: 'Gemma 3 12B 是 Google 开源的中型语言模型。',
    type: 'chat',
    contextWindowTokens: 40_960,
    maxOutput: 8_192,
    pricing: { input: 0, output: 0, cachedInput: 0 },
  },
  {
    id: 'gemma-3-27b-it',
    displayName: 'Gemma 3 27B',
    description: 'Gemma 3 27B 是 Google 开源的大型语言模型。',
    type: 'chat',
    contextWindowTokens: 139_264,
    maxOutput: 8_192,
    pricing: { input: 0, output: 0, cachedInput: 0 },
  },
  {
    id: 'gemma-3n-e2b-it',
    displayName: 'Gemma 3n E2B',
    description: 'Gemma 3n E2B 是高效的小型模型。',
    type: 'chat',
    contextWindowTokens: 10_240,
    maxOutput: 2_048,
    pricing: { input: 0, output: 0, cachedInput: 0 },
  },
  {
    id: 'gemma-3n-e4b-it',
    displayName: 'Gemma 3n E4B',
    description: 'Gemma 3n E4B 是高效的小型模型。',
    type: 'chat',
    contextWindowTokens: 10_240,
    maxOutput: 2_048,
    pricing: { input: 0, output: 0, cachedInput: 0 },
  },
  {
    id: 'gemini-3.1-flash-lite-preview',
    displayName: 'Gemini 3.1 Flash-Lite Preview',
    description:
      "Gemini 3.1 Flash-Lite Preview is Google's most cost-efficient multimodal model, optimized for high-volume agentic tasks, translation, and data processing.",
    type: 'chat',
    contextWindowTokens: 1_114_112,
    maxOutput: 65_536,
    enabled: true,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
      video: true,
      vision: true,
    },
    pricing: { input: 0.25, output: 1.5, cachedInput: 0.025 },
    releasedAt: '2026-03-04',
  },
];

const googleImageModels: ImageModelCard[] = [
  {
    id: 'imagen-4.0-generate-001',
    displayName: 'Imagen 4',
    description: 'Imagen 第四代文生图模型系列。',
    type: 'image',
    enabled: true,
    organization: 'Deepmind',
    resolutions: ['1024x1024'],
    releasedAt: '2025-08-15',
  },
  {
    id: 'imagen-4.0-ultra-generate-001',
    displayName: 'Imagen 4 Ultra',
    description: 'Imagen 第四代文生图模型系列的 Ultra 版本。',
    type: 'image',
    enabled: true,
    organization: 'Deepmind',
    resolutions: ['1024x1024'],
    releasedAt: '2025-08-15',
  },
  {
    id: 'imagen-4.0-fast-generate-001',
    displayName: 'Imagen 4 Fast',
    description: 'Imagen 第四代文生图模型系列的快速版本。',
    type: 'image',
    enabled: true,
    organization: 'Deepmind',
    resolutions: ['1024x1024'],
    releasedAt: '2025-08-15',
  },
  {
    id: 'gemini-3.1-flash-image-preview:image',
    displayName: 'Nano Banana 2',
    description:
      "Gemini 3.1 Flash Image (Nano Banana 2) is Google's fastest native image generation model with thinking support, conversational image generation and editing.",
    type: 'image',
    enabled: true,
    pricing: { input: 0.25, output: 1.5 },
    releasedAt: '2026-02-26',
  },
  {
    id: 'gemini-3-pro-image-preview:image',
    displayName: 'Nano Banana Pro',
    description:
      'Gemini 3 Pro Image (Nano Banana Pro) is Google’s image generation model and also supports multimodal chat.',
    type: 'image',
    enabled: true,
    pricing: { input: 2, output: 12 },
    releasedAt: '2025-11-18',
  },
  {
    id: 'gemini-2.5-flash-image:image',
    displayName: 'Nano Banana',
    description:
      'Nano Banana is Google’s newest, fastest, and most efficient native multimodal model, enabling conversational image generation and editing.',
    type: 'image',
    pricing: { input: 0.3, output: 2.5 },
    releasedAt: '2025-08-26',
  },
];

const googleVideoModels: VideoModelCard[] = [
  {
    id: 'google/veo-3.1',
    displayName: 'Google Veo 3.1',
    description:
      'Google 最新的视频生成模型，支持 720p、1080p、4K 分辨率，8 秒时长，原生音频生成，竖屏视频支持',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920', '3840x2160', '2160x3840'],
    fps: 24,
    maxDurationSeconds: 8,
    releasedAt: '2026-01-13',
  },
  {
    id: 'google/veo-3.1-audio',
    displayName: 'Google Veo 3.1 + Audio',
    description: 'Google Veo 3.1 带原生音频生成，支持自然对话和同步音效',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920', '3840x2160', '2160x3840'],
    fps: 24,
    maxDurationSeconds: 8,
    releasedAt: '2026-01-13',
  },
  {
    id: 'google/veo-3.1-fast',
    displayName: 'Google Veo 3.1 Fast',
    description: 'Google Veo 3.1 快速版本，优化生成速度同时保持高质量',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920', '3840x2160', '2160x3840'],
    fps: 24,
    maxDurationSeconds: 8,
    releasedAt: '2026-01-13',
  },
  {
    id: 'google/veo-3.1-fast-audio',
    displayName: 'Google Veo 3.1 Fast + Audio',
    description: 'Google Veo 3.1 Fast 带音频生成支持',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920', '3840x2160', '2160x3840'],
    fps: 24,
    maxDurationSeconds: 8,
    releasedAt: '2026-01-13',
  },
  {
    id: 'google/veo-3.0',
    displayName: 'Google Veo 3.0',
    description: 'Google latest video generation model with 8s duration',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
    fps: 24,
    maxDurationSeconds: 8,
  },
  {
    id: 'google/veo-3.0-audio',
    displayName: 'Google Veo 3.0 + Audio',
    description: 'Google Veo 3.0 with audio generation support',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
    fps: 24,
    maxDurationSeconds: 8,
  },
  {
    id: 'google/veo-3.0-fast',
    displayName: 'Google Veo 3.0 Fast',
    description: 'Google Veo 3.0 optimized for faster generation',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
    fps: 24,
    maxDurationSeconds: 8,
  },
  {
    id: 'google/veo-3.0-fast-audio',
    displayName: 'Google Veo 3.0 Fast + Audio',
    description: 'Google Veo 3.0 Fast with audio generation support',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
    fps: 24,
    maxDurationSeconds: 8,
  },
  {
    id: 'google/veo-2.0',
    displayName: 'Google Veo 2.0',
    description: 'Google Veo 2.0 video generation model',
    type: 'video',
    enabled: true,
    organization: 'Google',
    abilities: { videoOutput: true },
    resolutions: ['1280x720', '720x1280'],
    fps: 24,
    maxDurationSeconds: 5,
  },
  {
    id: 'veo-3.1-generate-preview',
    displayName: 'Veo 3.1 Generate Preview',
    description:
      'Our latest video generation model, available to developers on the paid tier of the Gemini API.',
    type: 'video',
    enabled: true,
    releasedAt: '2026-01-13',
  },
  {
    id: 'veo-3.1-fast-generate-preview',
    displayName: 'Veo 3.1 Fast Generate Preview',
    description:
      'Our latest video generation model, available to developers on the paid tier of the Gemini API.',
    type: 'video',
    enabled: true,
    releasedAt: '2026-01-13',
  },
  {
    id: 'veo-3.0-generate-001',
    displayName: 'Veo 3.0 Generate 001',
    description:
      'Our stable video generation model, available to developers on the paid tier of the Gemini API.',
    type: 'video',
    enabled: true,
    releasedAt: '2025-11-11',
  },
  {
    id: 'veo-3.0-fast-generate-001',
    displayName: 'Veo 3.0 Fast Generate 001',
    description:
      'Our stable video generation model, available to developers on the paid tier of the Gemini API.',
    type: 'video',
    enabled: true,
    releasedAt: '2025-11-11',
  },
  {
    id: 'veo-2.0-generate-001',
    displayName: 'Veo 2.0 Generate 001',
    description:
      'Our state-of-the-art video generation model, available to developers on the paid tier of the Gemini API.',
    type: 'video',
    releasedAt: '2025-04-09',
  },
];

export default {
  chat: googleChatModels,
  image: googleImageModels,
  video: googleVideoModels,
};
