import type { ChatModelCard } from '../types';

const higressModels: ChatModelCard[] = [
  {
    id: 'qwen-turbo',
    displayName: 'Qwen Turbo',
    description: 'Ultra-large Qwen model supporting Chinese, English, and other languages.',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'qwen-plus',
    displayName: 'Qwen Plus',
    description:
      'Enhanced ultra-large Qwen model supporting Chinese, English, and other languages.',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'qwen-max',
    displayName: 'Qwen Max',
    description:
      'Hundred-billion-scale ultra-large Qwen model supporting Chinese, English, and other languages; the API model behind current Qwen2.5 products.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 20, output: 60 },
  },
  {
    id: 'qwen-long',
    displayName: 'Qwen Long',
    description:
      'Ultra-large Qwen model with long context and chat across long- and multi-document scenarios.',
    type: 'chat',
    contextWindowTokens: 1_000_000,
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
  },
  {
    id: 'qwen-vl-plus-latest',
    displayName: 'Qwen VL Plus',
    description:
      'Enhanced large-scale Qwen vision-language model with major gains in detail and text recognition, supporting over one-megapixel resolution and arbitrary aspect ratios.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 8, output: 8 },
  },
  {
    id: 'qwen-vl-max-latest',
    displayName: 'Qwen VL Max',
    description: 'Ultra-large Qwen vision-language model.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 20, output: 20 },
  },
  {
    id: 'qwen-math-turbo-latest',
    displayName: 'Qwen Math Turbo',
    description: 'Qwen Math is a language model specialized for solving math problems.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'qwen-math-plus-latest',
    displayName: 'Qwen Math Plus',
    description: 'Qwen Math is a language model specialized for solving math problems.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'qwen-coder-turbo-latest',
    displayName: 'Qwen Coder Turbo',
    description: 'Qwen code model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'qwen2.5-7b-instruct',
    displayName: 'Qwen2.5 7B',
    description: 'Qwen2.5 open-source 7B model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 2 },
  },
  {
    id: 'qwen2.5-14b-instruct',
    displayName: 'Qwen2.5 14B',
    description: 'Qwen2.5 open-source 14B model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'qwen2.5-32b-instruct',
    displayName: 'Qwen2.5 32B',
    description: 'Qwen2.5 open-source 32B model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 3.5, output: 7 },
  },
  {
    id: 'qwen2.5-72b-instruct',
    displayName: 'Qwen2.5 72B',
    description: 'Qwen2.5 open-source 72B model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'qwen2.5-math-1.5b-instruct',
    displayName: 'Qwen2.5 Math 1.5B',
    description: 'Qwen-Math delivers strong math problem-solving.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'qwen2.5-math-7b-instruct',
    displayName: 'Qwen2.5 Math 7B',
    description: 'Qwen-Math delivers strong math problem-solving.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { currency: 'CNY', input: 1, output: 2 },
  },
  {
    id: 'qwen2.5-math-72b-instruct',
    displayName: 'Qwen2.5 Math 72B',
    description: 'Qwen-Math delivers strong math problem-solving.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'qwen2.5-coder-1.5b-instruct',
    displayName: 'Qwen2.5 Coder 1.5B',
    description: 'Open-source Qwen code model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'qwen2.5-coder-7b-instruct',
    displayName: 'Qwen2.5 Coder 7B',
    description: 'Open-source Qwen code model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    pricing: { currency: 'CNY', input: 1, output: 2 },
  },
  {
    id: 'qwen-vl-v1',
    displayName: 'Qwen VL',
    description:
      'Pretrained model initialized from Qwen-7B with an added vision module and 448 image resolution input.',
    type: 'chat',
    contextWindowTokens: 8_000,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'qwen-vl-chat-v1',
    displayName: 'Qwen VL Chat',
    description:
      'Qwen VL supports flexible interactions including multi-image input, multi-turn QA, and creative tasks.',
    type: 'chat',
    contextWindowTokens: 8_000,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'moonshot-v1-8k',
    displayName: 'Moonshot V1 8K',
    description:
      'Moonshot V1 8K is designed for short-text generation with efficient processing, handling 8,192 tokens for brief chats, quick notes, and fast content generation.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'moonshot-v1-32k',
    displayName: 'Moonshot V1 32K',
    description:
      'Moonshot V1 32K provides mid-length context handling up to 32,768 tokens, ideal for long documents and complex dialogues in content creation, report writing, and chat systems.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'moonshot-v1-128k',
    displayName: 'Moonshot V1 128K',
    description:
      'Moonshot V1 128K offers ultra-long context up to 128,000 tokens, suited for very long text generation and complex tasks in research, academia, and large document creation.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'Baichuan4',
    displayName: 'Baichuan 4',
    description:
      'Top domestic performance, surpassing leading overseas models on Chinese tasks like encyclopedic knowledge, long text, and creative generation.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 100, output: 100 },
  },
  {
    id: 'Baichuan4-Turbo',
    displayName: 'Baichuan 4 Turbo',
    type: 'chat',
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'Baichuan4-Air',
    displayName: 'Baichuan 4 Air',
    type: 'chat',
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'Baichuan3-Turbo',
    displayName: 'Baichuan 3 Turbo',
    description:
      'Optimized for high-frequency enterprise scenarios with major gains and strong value.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 12, output: 12 },
  },
  {
    id: 'Baichuan3-Turbo-128k',
    displayName: 'Baichuan 3 Turbo 128k',
    description:
      'With a 128K ultra-long context window, it is optimized for high-frequency enterprise scenarios with major gains and strong value.',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    enabled: true,
    pricing: { currency: 'CNY', input: 24, output: 24 },
  },
  {
    id: 'Baichuan2-Turbo',
    displayName: 'Baichuan 2 Turbo',
    description: 'Uses search augmentation to connect the model with domain and web knowledge.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 8, output: 8 },
  },
  {
    id: 'yi-lightning',
    displayName: 'Yi Lightning',
    description:
      'Latest high-performance model with high-quality output and much faster reasoning.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.99, output: 0.99 },
  },
  {
    id: 'yi-spark',
    displayName: 'Yi Spark',
    description:
      'Small but powerful, lightweight and ultra-fast, with enhanced math and coding capabilities.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 1, output: 1 },
  },
  {
    id: 'yi-medium',
    displayName: 'Yi Medium',
    description:
      'Upgraded mid-size model with balanced capabilities, strong value, and improved instruction following.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 2.5, output: 2.5 },
  },
  {
    id: 'yi-medium-200k',
    displayName: 'Yi Medium 200K',
    description: '200K ultra-long context window for deep long-text understanding and generation.',
    type: 'chat',
    contextWindowTokens: 200_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 12, output: 12 },
  },
  {
    id: 'yi-large-turbo',
    displayName: 'Yi Large Turbo',
    description:
      'Excellent value and performance, tuned to balance capability, reasoning speed, and cost.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 12, output: 12 },
  },
  {
    id: 'yi-large-rag',
    displayName: 'Yi Large RAG',
    description:
      'Advanced service based on the powerful yi-large model, combining retrieval and generation for precise answers with real-time web search.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 25, output: 25 },
  },
  {
    id: 'yi-large-fc',
    displayName: 'Yi Large FC',
    description:
      'Builds on yi-large with enhanced tool calling, suitable for agent or workflow business scenarios.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 20, output: 20 },
  },
  {
    id: 'yi-large',
    displayName: 'Yi Large',
    description: 'New 100B-parameter model with strong QA and text generation.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 20, output: 20 },
  },
  {
    id: 'yi-vision',
    displayName: 'Yi Vision',
    description:
      'Model for complex visual tasks with high-performance image understanding and analysis.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 6, output: 6 },
  },
  {
    id: 'yi-large-preview',
    displayName: 'Yi Large Preview',
    description: 'Early version; recommended to use yi-large (new version).',
    type: 'chat',
    contextWindowTokens: 16_384,
    pricing: { currency: 'CNY', input: 20, output: 20 },
  },
  {
    id: 'yi-lightning-lite',
    displayName: 'Yi Lightning Lite',
    description: 'Lightweight version; recommended to use yi-lightning.',
    type: 'chat',
    contextWindowTokens: 16_384,
    pricing: { currency: 'CNY', input: 0.99, output: 0.99 },
  },
  {
    id: 'glm-4-flash',
    displayName: 'GLM-4-Flash',
    description: 'GLM-4-Flash is ideal for simple tasks: fastest and free.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'glm-4-flashx',
    displayName: 'GLM-4-FlashX',
    description: 'GLM-4-FlashX is an enhanced Flash version with ultra-fast reasoning.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.1, output: 0.1 },
  },
  {
    id: 'glm-4-long',
    displayName: 'GLM-4-Long',
    description:
      'GLM-4-Long supports ultra-long inputs for memory-style tasks and large-scale document processing.',
    type: 'chat',
    contextWindowTokens: 1_024_000,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 1 },
  },
  {
    id: 'glm-4-air',
    displayName: 'GLM-4-Air',
    description:
      'GLM-4-Air is a high-value option with performance close to GLM-4, fast speed, and lower cost.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 1 },
  },
  {
    id: 'glm-4-airx',
    displayName: 'GLM-4-AirX',
    description:
      'GLM-4-AirX is a more efficient GLM-4-Air variant with up to 2.6x faster reasoning.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 10, output: 10 },
  },
  {
    id: 'glm-4-alltools',
    displayName: 'GLM-4-AllTools',
    description:
      'GLM-4-AllTools is a versatile agent model optimized for complex instruction planning and tool use such as web browsing, code explanation, and text generation, suitable for multi-task execution.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 100, output: 100 },
  },
  {
    id: 'glm-4-plus',
    displayName: 'GLM-4-Plus',
    description:
      'GLM-4-Plus is a high-intelligence flagship with strong long-text and complex-task handling and upgraded overall performance.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 50, output: 50 },
  },
  {
    id: 'glm-4-0520',
    displayName: 'GLM-4-0520',
    description:
      'GLM-4-0520 is the latest model version, designed for highly complex and diverse tasks with excellent performance.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 100, output: 100 },
  },
  {
    id: 'glm-4',
    displayName: 'GLM-4',
    description:
      'GLM-4 is the older flagship released in Jan 2024, now replaced by the stronger GLM-4-0520.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 100, output: 100 },
  },
  {
    id: 'glm-4v-plus',
    displayName: 'GLM-4V-Plus',
    description:
      'GLM-4V-Plus understands video and multiple images, suitable for multimodal tasks.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 10, output: 10 },
  },
  {
    id: 'glm-4v',
    displayName: 'GLM-4V',
    description: 'GLM-4V provides strong image understanding and reasoning across visual tasks.',
    type: 'chat',
    contextWindowTokens: 2_048,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 50, output: 50 },
  },
  {
    id: 'charglm-3',
    displayName: 'CharGLM-3',
    description:
      'CharGLM-3 is built for roleplay and emotional companionship, supporting ultra-long multi-turn memory and personalized dialogue.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { currency: 'CNY', input: 15, output: 15 },
  },
  {
    id: 'emohaa',
    displayName: 'Emohaa',
    description:
      'Emohaa is a mental health model with professional counseling abilities to help users understand emotional issues.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { currency: 'CNY', input: 15, output: 15 },
  },
  {
    id: '360gpt2-pro',
    displayName: '360GPT2 Pro',
    description:
      '360GPT2 Pro is an advanced NLP model from 360 with excellent text generation and understanding, especially for creative tasks, handling complex transformations and roleplay.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 7_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 5, output: 5 },
  },
  {
    id: '360gpt-pro',
    displayName: '360GPT Pro',
    description:
      '360GPT Pro is a key 360 AI model with efficient text processing for diverse NLP scenarios, supporting long-text understanding and multi-turn dialogue.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 7_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 5, output: 5 },
  },
  {
    id: '360gpt-turbo',
    displayName: '360GPT Turbo',
    description:
      '360GPT Turbo delivers strong compute and chat capability with excellent semantic understanding and generation efficiency, ideal for enterprise and developers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 7_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 2, output: 2 },
  },
  {
    id: '360gpt-turbo-responsibility-8k',
    displayName: '360GPT Turbo Responsibility 8K',
    description:
      '360GPT Turbo Responsibility 8K emphasizes semantic safety and responsibility for content-sensitive applications, ensuring accurate and robust user experiences.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    enabled: true,
    pricing: { currency: 'CNY', input: 2, output: 2 },
  },
  {
    id: 'ERNIE-3.5-8K',
    displayName: 'ERNIE 3.5 8K',
    description:
      'Baidu’s flagship large-scale LLM trained on massive Chinese/English corpora with strong general ability for chat, creation, and plugin use; supports automatic Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'ERNIE-3.5-8K-Preview',
    displayName: 'ERNIE 3.5 8K Preview',
    description:
      'Baidu’s flagship large-scale LLM trained on massive Chinese/English corpora with strong general ability for chat, creation, and plugin use; supports automatic Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'ERNIE-3.5-128K',
    displayName: 'ERNIE 3.5 128K',
    description:
      'Baidu’s flagship large-scale LLM trained on massive Chinese/English corpora with strong general ability for chat, creation, and plugin use; supports automatic Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'ERNIE-4.0-8K-Latest',
    displayName: 'ERNIE 4.0 8K',
    description:
      'Baidu’s flagship ultra-large LLM with comprehensive upgrades over ERNIE 3.5, suitable for complex tasks across domains; supports Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    pricing: { currency: 'CNY', input: 30, output: 90 },
  },
  {
    id: 'ERNIE-4.0-8K-Preview',
    displayName: 'ERNIE 4.0 8K Preview',
    description:
      'Baidu’s flagship ultra-large LLM with comprehensive upgrades over ERNIE 3.5, suitable for complex tasks across domains; supports Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { currency: 'CNY', input: 30, output: 90 },
  },
  {
    id: 'ERNIE-4.0-Turbo-8K-Latest',
    displayName: 'ERNIE 4.0 Turbo 8K',
    description:
      'Baidu’s flagship ultra-large LLM with strong overall performance for complex tasks, with Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    pricing: { currency: 'CNY', input: 20, output: 60 },
  },
  {
    id: 'ERNIE-4.0-Turbo-8K-Preview',
    displayName: 'ERNIE 4.0 Turbo 8K Preview',
    description:
      'Baidu’s flagship ultra-large LLM with strong overall performance for complex tasks, with Baidu Search plugin integration for fresh answers.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { currency: 'CNY', input: 20, output: 60 },
  },
  {
    id: 'ERNIE-Lite-Pro-128K',
    displayName: 'ERNIE Lite Pro 128K',
    description:
      'Baidu’s lightweight LLM balancing quality and inference performance, better than ERNIE Lite and suitable for low-compute accelerators.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.2, output: 0.4 },
  },
  {
    id: 'ERNIE-Speed-Pro-128K',
    displayName: 'ERNIE Speed Pro 128K',
    description:
      'Baidu’s latest high-performance LLM (2024) with strong general ability, better than ERNIE Speed, suitable as a base for fine-tuning with excellent reasoning performance.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'ERNIE-Speed-128K',
    displayName: 'ERNIE Speed 128K',
    description:
      'Baidu’s latest high-performance LLM (2024) with strong general ability, suitable as a base for fine-tuning to handle specific scenarios, with excellent reasoning performance.',
    type: 'chat',
    contextWindowTokens: 128_000,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'ERNIE-Character-8K',
    displayName: 'ERNIE Character 8K',
    description:
      'Baidu’s vertical-domain LLM for game NPCs, customer service, and roleplay, with clearer persona consistency, stronger instruction following, and better reasoning.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { currency: 'CNY', input: 4, output: 8 },
  },
  {
    id: 'hunyuan-lite',
    displayName: 'Hunyuan Lite',
    description:
      'Upgraded to an MoE architecture with a 256K context window, leading many open-source models across NLP, code, math, and domain benchmarks.',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 6_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'hunyuan-standard',
    displayName: 'Hunyuan Standard',
    description: 'Uses improved routing to mitigate load balancing and expert collapse.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 2_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 4.5, output: 5 },
  },
  {
    id: 'hunyuan-standard-256K',
    displayName: 'Hunyuan Standard 256K',
    description: 'Uses improved routing to mitigate load balancing and expert collapse.',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 6_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 15, output: 60 },
  },
  {
    id: 'hunyuan-turbo',
    displayName: 'Hunyuan Turbo',
    description:
      'Preview of Hunyuan’s next-gen LLM with a new MoE architecture, delivering faster reasoning and stronger results than hunyuan-pro.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 4_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 15, output: 50 },
  },
  {
    id: 'hunyuan-pro',
    displayName: 'Hunyuan Pro',
    description:
      'Trillion-parameter MOE-32K long-context model leading benchmarks, strong at complex instructions and reasoning, advanced math, function calling, and optimized for multilingual translation, finance, law, and medical domains.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 4_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 30, output: 100 },
  },
  {
    id: 'hunyuan-large',
    displayName: 'Hunyuan Large',
    type: 'chat',
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'hunyuan-vision',
    displayName: 'Hunyuan Vision',
    description: 'Hunyuan latest multimodal model supporting image + text inputs to generate text.',
    type: 'chat',
    contextWindowTokens: 8_000,
    maxOutput: 4_000,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 18, output: 18 },
  },
  {
    id: 'hunyuan-code',
    displayName: 'Hunyuan Code',
    description:
      'Hunyuan’s latest code model trained on 200B high-quality code data plus six months of SFT data, with 8K context.',
    type: 'chat',
    contextWindowTokens: 8_000,
    maxOutput: 4_000,
    pricing: { currency: 'CNY', input: 4, output: 8 },
  },
  {
    id: 'hunyuan-functioncall',
    displayName: 'Hunyuan FunctionCall',
    description:
      'Hunyuan’s latest MoE FunctionCall model trained on high-quality tool-call data, with a 32K context window and leading benchmarks across dimensions.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 4_000,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 8 },
  },
  {
    id: 'hunyuan-role',
    displayName: 'Hunyuan Role',
    description:
      'Hunyuan’s latest roleplay model, officially fine-tuned with roleplay data, delivering stronger base performance in roleplay scenarios.',
    type: 'chat',
    contextWindowTokens: 8_000,
    maxOutput: 4_000,
    pricing: { currency: 'CNY', input: 4, output: 8 },
  },
  {
    id: 'step-1-flash',
    displayName: 'Step 1 Flash',
    description: 'High-speed model suitable for real-time chat.',
    type: 'chat',
    contextWindowTokens: 8_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'step-1-8k',
    displayName: 'Step 1 8K',
    description: 'Small model suited for lightweight tasks.',
    type: 'chat',
    contextWindowTokens: 8_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 5, output: 20 },
  },
  {
    id: 'step-1-32k',
    displayName: 'Step 1 32K',
    description: 'Supports mid-length conversations for a wide range of scenarios.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 15, output: 70 },
  },
  {
    id: 'step-1-128k',
    displayName: 'Step 1 128K',
    description: 'Balances performance and cost for general scenarios.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 40, output: 200 },
  },
  {
    id: 'step-1-256k',
    displayName: 'Step 1 256K',
    description: 'Extra-long context handling, ideal for long-document analysis.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 95, output: 300 },
  },
  {
    id: 'step-2-16k',
    displayName: 'Step 2 16K',
    description: 'Supports large-context interactions for complex dialogues.',
    type: 'chat',
    contextWindowTokens: 16_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 38, output: 120 },
  },
  {
    id: 'step-1v-8k',
    displayName: 'Step 1V 8K',
    description: 'Small vision model for basic image-and-text tasks.',
    type: 'chat',
    contextWindowTokens: 8_000,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 5, output: 20 },
  },
  {
    id: 'step-1v-32k',
    displayName: 'Step 1V 32K',
    description: 'Supports vision inputs for richer multimodal interaction.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 15, output: 70 },
  },
  {
    id: 'step-1.5v-mini',
    displayName: 'Step 1.5V Mini',
    description: 'Strong video understanding capabilities.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 8, output: 35 },
  },
  {
    id: 'lite',
    displayName: 'Spark Lite',
    description:
      'Spark Lite is a lightweight LLM with ultra-low latency and efficient processing, fully free and supporting real-time web search.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
    enabled: true,
  },
  {
    id: 'generalv3',
    displayName: 'Spark Pro',
    description:
      'Spark Pro is a high-performance LLM optimized for professional domains like math, coding, healthcare, and education, with web search and built-in plugins such as weather and date.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 8_192,
    enabled: true,
  },
  {
    id: 'pro-128k',
    displayName: 'Spark Pro 128K',
    description:
      'Spark Pro 128K supports up to 128K context, ideal for full-document analysis and long-range reasoning, providing coherent logic and rich citations in complex text communication.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    enabled: true,
  },
  {
    id: 'generalv3.5',
    displayName: 'Spark Max',
    description:
      'Spark Max is the most full-featured version, with web search and many built-in plugins.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 8_192,
    enabled: true,
  },
  {
    id: 'max-32k',
    displayName: 'Spark Max 32K',
    description:
      'Spark Max 32K offers large-context processing with stronger understanding and logical reasoning, supporting 32K input for long documents and private knowledge QA.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    enabled: true,
  },
  {
    id: '4.0Ultra',
    displayName: 'Spark 4.0 Ultra',
    description:
      'Spark Ultra is the most powerful Spark model, improving web search integration and text understanding/summarization.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 8_192,
    enabled: true,
  },
  {
    id: 'o1-mini',
    displayName: 'OpenAI o1-mini',
    description:
      'o1-mini is a fast, cost-effective reasoning model designed for coding, math, and science.',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 65_536,
    enabled: true,
    pricing: { input: 3, output: 12 },
    releasedAt: '2024-09-12',
  },
  {
    id: 'o1-preview',
    displayName: 'OpenAI o1-preview',
    description: 'o1 is OpenAI’s new reasoning model for complex tasks requiring broad knowledge.',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 32_768,
    enabled: true,
    pricing: { input: 15, output: 60 },
    releasedAt: '2024-09-12',
  },
  {
    id: 'gpt-4o-mini',
    displayName: 'GPT-4o mini',
    description:
      'GPT-4o mini is OpenAI’s latest model after GPT-4 Omni, supporting image+text input with text output.',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 16_385,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.15, output: 0.6 },
  },
  {
    id: 'gpt-4o',
    displayName: 'GPT-4o',
    description: 'ChatGPT-4o is a dynamic model updated in real time.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 2.5, output: 10 },
  },
  {
    id: 'gpt-4o-2024-08-06',
    displayName: 'GPT-4o 0806',
    description: 'ChatGPT-4o is a dynamic model updated in real time.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 2.5, output: 10 },
  },
  {
    id: 'gpt-4o-2024-05-13',
    displayName: 'GPT-4o 0513',
    description: 'ChatGPT-4o is a dynamic model updated in real time.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 5, output: 15 },
  },
  {
    id: 'chatgpt-4o-latest',
    displayName: 'ChatGPT-4o',
    description: 'ChatGPT-4o is a dynamic model updated in real time.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { vision: true },
    pricing: { input: 5, output: 15 },
  },
  {
    id: 'gpt-4-turbo',
    displayName: 'GPT-4 Turbo',
    description: 'The latest GPT-4 Turbo model includes vision.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 10, output: 30 },
  },
  {
    id: 'gpt-4-turbo-2024-04-09',
    displayName: 'GPT-4 Turbo Vision 0409',
    description: 'The latest GPT-4 Turbo model includes vision.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 10, output: 30 },
  },
  {
    id: 'gpt-4-turbo-preview',
    displayName: 'GPT-4 Turbo Preview',
    description: 'The latest GPT-4 Turbo model includes vision.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { input: 10, output: 30 },
  },
  {
    id: 'gpt-4-0125-preview',
    displayName: 'GPT-4 Turbo Preview 0125',
    description: 'The latest GPT-4 Turbo model includes vision.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { input: 10, output: 30 },
  },
  {
    id: 'gpt-4-1106-preview',
    displayName: 'GPT-4 Turbo Preview 1106',
    description: 'The latest GPT-4 Turbo model includes vision.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
    pricing: { input: 10, output: 30 },
  },
  {
    id: 'gpt-4',
    displayName: 'GPT-4',
    description:
      'GPT-4 provides a larger context window to handle longer inputs for scenarios needing broad information integration and data analysis.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 30, output: 60 },
  },
  {
    id: 'gpt-4-0613',
    displayName: 'GPT-4 0613',
    description:
      'GPT-4 provides a larger context window to handle longer inputs for scenarios needing broad information integration and data analysis.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 30, output: 60 },
  },
  {
    id: 'gpt-4-32k',
    displayName: 'GPT-4 32K',
    description:
      'GPT-4 provides a larger context window to handle longer inputs for scenarios needing broad information integration and data analysis.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { input: 60, output: 120 },
  },
  {
    id: 'gpt-4-32k-0613',
    displayName: 'GPT-4 32K 0613',
    description:
      'GPT-4 provides a larger context window to handle longer inputs for scenarios needing broad information integration and data analysis.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { input: 60, output: 120 },
  },
  {
    id: 'gpt-3.5-turbo',
    displayName: 'GPT-3.5 Turbo',
    description: 'GPT-3.5 Turbo for text generation and understanding.',
    type: 'chat',
    contextWindowTokens: 16_385,
    abilities: { functionCall: true },
    pricing: { input: 0.5, output: 1.5 },
  },
  {
    id: 'gpt-3.5-turbo-0125',
    displayName: 'GPT-3.5 Turbo 0125',
    description: 'GPT-3.5 Turbo for text generation and understanding.',
    type: 'chat',
    contextWindowTokens: 16_385,
    abilities: { functionCall: true },
    pricing: { input: 0.5, output: 1.5 },
  },
  {
    id: 'gpt-3.5-turbo-1106',
    displayName: 'GPT-3.5 Turbo 1106',
    description: 'GPT-3.5 Turbo for text generation and understanding.',
    type: 'chat',
    contextWindowTokens: 16_385,
    abilities: { functionCall: true },
    pricing: { input: 1, output: 2 },
  },
  {
    id: 'gpt-3.5-turbo-instruct',
    displayName: 'GPT-3.5 Turbo Instruct',
    description: 'GPT-3.5 Turbo for text generation and understanding.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { input: 1.5, output: 2 },
  },
  {
    id: 'gpt-35-turbo',
    displayName: 'GPT 3.5 Turbo',
    description:
      'GPT-3.5 Turbo is OpenAI’s efficient model for chat and text generation, supporting parallel function calling.',
    type: 'chat',
    contextWindowTokens: 16_385,
    maxOutput: 4_096,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'gpt-35-turbo-16k',
    displayName: 'GPT 3.5 Turbo',
    description: 'GPT-3.5 Turbo 16k is a high-capacity text generation model for complex tasks.',
    type: 'chat',
    contextWindowTokens: 16_384,
    abilities: { functionCall: true },
  },
  {
    id: 'gpt-4-vision-preview',
    displayName: 'GPT 4 Turbo with Vision Preview',
    description: 'GPT-4 Vision preview, designed for image analysis and processing tasks.',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { vision: true },
  },
  {
    id: 'ai21-jamba-1.5-mini',
    displayName: 'AI21 Jamba 1.5 Mini',
    description:
      'A 52B-parameter (12B active) multilingual model with a 256K context window, function calling, structured output, and grounded generation.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 4_096,
    abilities: { functionCall: true },
  },
  {
    id: 'ai21-jamba-1.5-large',
    displayName: 'AI21 Jamba 1.5 Large',
    description:
      'A 398B-parameter (94B active) multilingual model with a 256K context window, function calling, structured output, and grounded generation.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 4_096,
    abilities: { functionCall: true },
  },
  {
    id: 'cohere-command-r',
    displayName: 'Cohere Command R',
    description:
      'Command R is a scalable generative model designed for RAG and tool use, enabling production-grade AI.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'cohere-command-r-plus',
    displayName: 'Cohere Command R+',
    description: 'Command R+ is an advanced RAG-optimized model built for enterprise workloads.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-nemo',
    displayName: 'Mistral Nemo',
    description:
      'Mistral Nemo is a cutting-edge LLM with state-of-the-art reasoning, world knowledge, and coding for its size.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-small',
    displayName: 'Mistral Small',
    description:
      'Mistral Small is suitable for any language-based task requiring high efficiency and low latency.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'mistral-large',
    displayName: 'Mistral Large',
    description:
      'Mistral’s flagship model for complex tasks needing large-scale reasoning or specialization (synthetic text, code, RAG, or agents).',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'llama-3.2-11b-vision-instruct',
    displayName: 'Llama 3.2 11B Vision',
    description:
      'Strong image reasoning on high-resolution images, suited for visual understanding apps.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'llama-3.2-90b-vision-instruct',
    displayName: 'Llama 3.2 90B Vision',
    description: 'Advanced image reasoning for visual-understanding agent applications.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'meta-llama-3.1-8b-instruct',
    displayName: 'Meta Llama 3.1 8B',
    description:
      'Llama 3.1 instruction-tuned text model optimized for multilingual chat, performing strongly on common industry benchmarks among open and closed chat models.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'meta-llama-3.1-70b-instruct',
    displayName: 'Meta Llama 3.1 70B',
    description:
      'Llama 3.1 instruction-tuned text model optimized for multilingual chat, performing strongly on common industry benchmarks among open and closed chat models.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'meta-llama-3.1-405b-instruct',
    displayName: 'Meta Llama 3.1 405B',
    description:
      'Llama 3.1 instruction-tuned text model optimized for multilingual chat, performing strongly on common industry benchmarks among open and closed chat models.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'meta-llama-3-8b-instruct',
    displayName: 'Meta Llama 3 8B',
    description: 'A versatile 8B-parameter model optimized for chat and text generation.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
  },
  {
    id: 'meta-llama-3-70b-instruct',
    displayName: 'Meta Llama 3 70B',
    description:
      'A powerful 70B-parameter model that excels at reasoning, coding, and broad language tasks.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3.5-mini-instruct',
    displayName: 'Phi-3.5-mini 128K',
    description: 'An updated version of the Phi-3-mini model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3.5-vision-instrust',
    displayName: 'Phi-3.5-vision 128K',
    description: 'An updated version of the Phi-3-vision model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'Phi-3-mini-4k-instruct',
    displayName: 'Phi-3-mini 4K',
    description: 'The smallest Phi-3 family member, optimized for quality and low latency.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3-mini-128k-instruct',
    displayName: 'Phi-3-mini 128K',
    description:
      'The same Phi-3-mini model with a larger context window for RAG or few-shot prompts.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3-small-8k-instruct',
    displayName: 'Phi-3-small 8K',
    description:
      'A 7B-parameter model with higher quality than Phi-3-mini, focused on high-quality, reasoning-intensive data.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3-small-128k-instruct',
    displayName: 'Phi-3-small 128K',
    description:
      'The same Phi-3-small model with a larger context window for RAG or few-shot prompts.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3-medium-4k-instruct',
    displayName: 'Phi-3-medium 4K',
    description:
      'A 14B-parameter model with higher quality than Phi-3-mini, focused on high-quality, reasoning-intensive data.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_096,
  },
  {
    id: 'Phi-3-medium-128k-instruct',
    displayName: 'Phi-3-medium 128K',
    description:
      'The same Phi-3-medium model with a larger context window for RAG or few-shot prompts.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
  },
  {
    id: 'llama-3.2-11b-vision-preview',
    displayName: 'Llama 3.2 11B Vision (Preview)',
    description:
      'Llama 3.2 is designed for tasks combining vision and text, excelling at image captioning and visual QA to bridge language generation and visual reasoning.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { vision: true },
    pricing: { input: 0.05, output: 0.08 },
  },
  {
    id: 'llama-3.2-90b-vision-preview',
    displayName: 'Llama 3.2 90B Vision (Preview)',
    description:
      'Llama 3.2 is designed for tasks combining vision and text, excelling at image captioning and visual QA to bridge language generation and visual reasoning.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { vision: true },
    pricing: { input: 0.59, output: 0.79 },
  },
  {
    id: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B',
    description:
      'Llama 3.1 8B is a high-efficiency model with fast text generation, ideal for large-scale, cost-effective applications.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 0.05, output: 0.08 },
  },
  {
    id: 'llama-3.1-70b-versatile',
    displayName: 'Llama 3.1 70B',
    description:
      'Llama 3.1 70B delivers stronger AI reasoning for complex applications, supporting heavy compute with high efficiency and accuracy.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 0.59, output: 0.79 },
  },
  {
    id: 'llama3-groq-8b-8192-tool-use-preview',
    displayName: 'Llama 3 Groq 8B Tool Use (Preview)',
    description:
      'Llama 3 Groq 8B Tool Use is optimized for efficient tool use with fast parallel compute.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 0.19, output: 0.19 },
  },
  {
    id: 'llama3-groq-70b-8192-tool-use-preview',
    displayName: 'Llama 3 Groq 70B Tool Use (Preview)',
    description:
      'Llama 3 Groq 70B Tool Use provides strong tool-calling for efficient handling of complex tasks.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 0.89, output: 0.89 },
  },
  {
    id: 'llama3-8b-8192',
    displayName: 'Meta Llama 3 8B',
    description: 'Meta Llama 3 8B delivers strong reasoning performance for diverse scenarios.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 0.05, output: 0.08 },
  },
  {
    id: 'llama3-70b-8192',
    displayName: 'Meta Llama 3 70B',
    description: 'Meta Llama 3 70B offers exceptional complexity handling for demanding projects.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 0.59, output: 0.79 },
  },
  {
    id: 'gemma2-9b-it',
    displayName: 'Gemma 2 9B',
    description: 'Gemma 2 9B is optimized for specific tasks and tool integration.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 0.2, output: 0.2 },
  },
  {
    id: 'gemma-7b-it',
    displayName: 'Gemma 7B',
    description: 'Gemma 7B is cost-effective for small to mid-scale tasks.',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 0.07, output: 0.07 },
  },
  {
    id: 'mixtral-8x7b-32768',
    displayName: 'Mixtral 8x7B',
    description: 'Mixtral 8x7B provides fault-tolerant parallel compute for complex tasks.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { input: 0.24, output: 0.24 },
  },
  {
    id: 'llava-v1.5-7b-4096-preview',
    displayName: 'LLaVA 1.5 7B',
    description:
      'LLaVA 1.5 7B fuses visual processing to generate complex outputs from visual inputs.',
    type: 'chat',
    contextWindowTokens: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'deepseek-chat',
    displayName: 'DeepSeek V2.5',
    description: 'A new open-source model combining general and code abilities.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 0.14, output: 0.28, cachedInput: 0.014 },
    releasedAt: '2024-09-05',
  },
  {
    id: 'claude-3-5-haiku-20241022',
    displayName: 'Claude 3.5 Haiku',
    description: 'Claude 3.5 Haiku is Anthropic’s fastest next-gen model.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 1, output: 5, cachedInput: 0.1 },
    releasedAt: '2024-11-05',
  },
  {
    id: 'claude-3-haiku-20240307',
    displayName: 'Claude 3 Haiku',
    description:
      'Claude 3 Haiku is Anthropic’s fastest and most compact model, designed for near-instant responses with fast, accurate performance.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.25, output: 1.25 },
    releasedAt: '2024-03-07',
  },
  {
    id: 'claude-3-sonnet-20240229',
    displayName: 'Claude 3 Sonnet',
    description:
      'Claude 3 Sonnet balances intelligence and speed for enterprise workloads, delivering high utility at lower cost and reliable large-scale deployment.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3, output: 15 },
    releasedAt: '2024-02-29',
  },
  {
    id: 'claude-3-opus-20240229',
    displayName: 'Claude 3 Opus',
    description:
      'Claude 3 Opus is Anthropic’s most powerful model for highly complex tasks, excelling in performance, intelligence, fluency, and comprehension.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 15, output: 75 },
    releasedAt: '2024-02-29',
  },
  {
    id: 'claude-2.1',
    displayName: 'Claude 2.1',
    description:
      'Claude 2 delivers key enterprise improvements, including a leading 200K-token context, reduced hallucinations, system prompts, and a new test feature: tool calling.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 4_096,
    pricing: { input: 8, output: 24 },
    releasedAt: '2023-11-21',
  },
  {
    id: 'claude-2.0',
    displayName: 'Claude 2.0',
    description:
      'Claude 2 delivers key enterprise improvements, including a leading 200K-token context, reduced hallucinations, system prompts, and a new test feature: tool calling.',
    type: 'chat',
    contextWindowTokens: 100_000,
    maxOutput: 4_096,
    pricing: { input: 8, output: 24 },
    releasedAt: '2023-07-11',
  },
  {
    id: 'gemini-1.5-flash-latest',
    displayName: 'Gemini 1.5 Flash',
    description:
      'Gemini 1.5 Flash is Google’s latest multimodal AI model with fast processing, supporting text, image, and video inputs for efficient scaling across tasks.',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.018 },
  },
  {
    id: 'gemini-1.5-flash-002',
    displayName: 'Gemini 1.5 Flash 002',
    description:
      'Gemini 1.5 Flash 002 is an efficient multimodal model for broad application scaling.',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.018 },
    releasedAt: '2024-09-25',
  },
  {
    id: 'gemini-1.5-flash-001',
    displayName: 'Gemini 1.5 Flash 001',
    description:
      'Gemini 1.5 Flash 001 is an efficient multimodal model for broad application scaling.',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.018 },
  },
  {
    id: 'gemini-1.5-flash-exp-0827',
    displayName: 'Gemini 1.5 Flash 0827',
    description:
      'Gemini 1.5 Flash 0827 delivers optimized multimodal processing for complex tasks.',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.018 },
    releasedAt: '2024-08-27',
  },
  {
    id: 'gemini-1.5-flash-8b',
    displayName: 'Gemini 1.5 Flash 8B',
    description:
      'Gemini 1.5 Flash 8B is an efficient multimodal model for broad application scaling.',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.02 },
    releasedAt: '2024-10-03',
  },
  {
    id: 'gemini-1.5-flash-8b-exp-0924',
    displayName: 'Gemini 1.5 Flash 8B 0924',
    description:
      'Gemini 1.5 Flash 8B 0924 is the latest experimental model with notable gains across text and multimodal use cases.',
    type: 'chat',
    contextWindowTokens: 1_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.075, output: 0.3, cachedInput: 0.018 },
    releasedAt: '2024-09-24',
  },
  {
    id: 'gemini-1.5-pro-latest',
    displayName: 'Gemini 1.5 Pro',
    description:
      'Gemini 1.5 Pro supports up to 2 million tokens, an ideal mid-sized multimodal model for complex tasks.',
    type: 'chat',
    contextWindowTokens: 2_008_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3.5, output: 10.5, cachedInput: 0.875 },
    releasedAt: '2024-02-15',
  },
  {
    id: 'gemini-1.5-pro-002',
    displayName: 'Gemini 1.5 Pro 002',
    description:
      'Gemini 1.5 Pro 002 is the latest production-ready model with higher-quality outputs, especially improved in math, long context, and vision tasks.',
    type: 'chat',
    contextWindowTokens: 2_008_192,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 1.25, output: 2.5, cachedInput: 0.315 },
    releasedAt: '2024-09-24',
  },
  {
    id: 'gemini-1.5-pro-001',
    displayName: 'Gemini 1.5 Pro 001',
    description: 'Gemini 1.5 Pro 001 is a scalable multimodal AI solution for complex tasks.',
    type: 'chat',
    contextWindowTokens: 2_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3.5, output: 10.5, cachedInput: 0.875 },
    releasedAt: '2024-02-15',
  },
  {
    id: 'gemini-1.5-pro-exp-0827',
    displayName: 'Gemini 1.5 Pro 0827',
    description:
      'Gemini 1.5 Pro 0827 applies latest optimizations for more efficient multimodal processing.',
    type: 'chat',
    contextWindowTokens: 2_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3.5, output: 10.5, cachedInput: 0.875 },
    releasedAt: '2024-08-27',
  },
  {
    id: 'gemini-1.5-pro-exp-0801',
    displayName: 'Gemini 1.5 Pro 0801',
    description:
      'Gemini 1.5 Pro 0801 provides strong multimodal processing with greater flexibility for app development.',
    type: 'chat',
    contextWindowTokens: 2_008_192,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 3.5, output: 10.5, cachedInput: 0.875 },
    releasedAt: '2024-08-01',
  },
  {
    id: 'gemini-1.0-pro-latest',
    displayName: 'Gemini 1.0 Pro',
    description:
      'Gemini 1.0 Pro is Google’s high-performance AI model designed for broad task scaling.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 2_048,
    pricing: { input: 0.5, output: 1.5 },
    releasedAt: '2023-12-06',
  },
  {
    id: 'gemini-1.0-pro-001',
    displayName: 'Gemini 1.0 Pro 001 (Tuning)',
    description:
      'Gemini 1.0 Pro 001 (Tuning) provides stable, tunable performance for complex tasks.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 2_048,
    abilities: { functionCall: true },
    pricing: { input: 0.5, output: 1.5 },
    releasedAt: '2023-12-06',
  },
  {
    id: 'gemini-1.0-pro-002',
    displayName: 'Gemini 1.0 Pro 002 (Tuning)',
    description:
      'Gemini 1.0 Pro 002 (Tuning) provides strong multimodal support for complex tasks.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 2_048,
    pricing: { input: 0.5, output: 1.5 },
    releasedAt: '2023-12-06',
  },
  {
    id: 'open-mistral-nemo',
    displayName: 'Mistral Nemo',
    description:
      'Mistral Nemo is a 12B model co-developed with Nvidia, offering strong reasoning and coding performance with easy integration.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 0.15, output: 0.15 },
  },
  {
    id: 'mistral-small-latest',
    displayName: 'Mistral Small',
    description:
      'Mistral Small is a cost-effective, fast, and reliable option for translation, summarization, and sentiment analysis.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 0.2, output: 0.6 },
  },
  {
    id: 'mistral-large-latest',
    displayName: 'Mistral Large',
    description:
      'Mistral Large is the flagship model, excelling at multilingual tasks, complex reasoning, and code generation for high-end applications.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { input: 2, output: 6 },
  },
  {
    id: 'codestral-latest',
    displayName: 'Codestral',
    description:
      'Codestral is a cutting-edge code generation model optimized for fill-in-the-middle and code completion.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { input: 0.2, output: 0.6 },
  },
  {
    id: 'pixtral-12b-2409',
    displayName: 'Pixtral 12B',
    description:
      'Pixtral performs strongly on chart/diagram understanding, document QA, multimodal reasoning, and instruction following.',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    abilities: { vision: true },
    pricing: { input: 0.15, output: 0.15 },
  },
  {
    id: 'ministral-3b-latest',
    displayName: 'Ministral 3B',
    description: 'Ministral 3B is Mistral’s top-tier edge model.',
    type: 'chat',
    contextWindowTokens: 128_000,
    pricing: { input: 0.04, output: 0.04 },
  },
  {
    id: 'ministral-8b-latest',
    displayName: 'Ministral 8B',
    description: 'Ministral 8B is Mistral’s high-value edge model.',
    type: 'chat',
    contextWindowTokens: 128_000,
    pricing: { input: 0.1, output: 0.1 },
  },
  {
    id: 'open-mistral-7b',
    displayName: 'Mistral 7B',
    description:
      'Mistral 7B is compact but high-performing, strong for batch processing and simple tasks like classification and text generation, with solid reasoning.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { input: 0.25, output: 0.25 },
  },
  {
    id: 'open-mixtral-8x7b',
    displayName: 'Mixtral 8x7B',
    description:
      'Mixtral 8x7B is a sparse MoE model that boosts inference speed, suitable for multilingual and code generation tasks.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { input: 0.7, output: 0.7 },
  },
  {
    id: 'open-mixtral-8x22b',
    displayName: 'Mixtral 8x22B',
    description:
      'Mixtral 8x22B is a larger MoE model for complex tasks, offering strong reasoning and higher throughput.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true },
    pricing: { input: 2, output: 6 },
  },
  {
    id: 'open-codestral-mamba',
    displayName: 'Codestral Mamba',
    description:
      'Codestral Mamba is a Mamba-2 language model focused on code generation, supporting advanced code and reasoning tasks.',
    type: 'chat',
    contextWindowTokens: 256_000,
    pricing: { input: 0.15, output: 0.15 },
  },
  {
    id: 'abab6.5s-chat',
    displayName: 'abab6.5s',
    description:
      'Suitable for a wide range of NLP tasks, including text generation and dialogue systems.',
    type: 'chat',
    contextWindowTokens: 245_760,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'abab6.5g-chat',
    displayName: 'abab6.5g',
    description:
      'Designed for multilingual persona chat, supporting high-quality dialogue generation in English and other languages.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'abab6.5t-chat',
    displayName: 'abab6.5t',
    description:
      'Optimized for Chinese persona chat, providing fluent dialogue that fits Chinese expression habits.',
    type: 'chat',
    contextWindowTokens: 8_192,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'abab5.5-chat',
    displayName: 'abab5.5',
    description:
      'Built for productivity scenarios with complex task handling and efficient text generation for professional use.',
    type: 'chat',
    contextWindowTokens: 16_384,
  },
  {
    id: 'abab5.5s-chat',
    displayName: 'abab5.5s',
    description:
      'Designed for Chinese persona chat, delivering high-quality Chinese dialogue for various applications.',
    type: 'chat',
    contextWindowTokens: 8_192,
  },
  {
    id: 'command-r',
    displayName: 'command-r',
    type: 'chat',
  },
  {
    id: 'command-r-plus',
    displayName: 'command-r-plus',
    type: 'chat',
  },
  {
    id: 'command-light',
    displayName: 'command-light',
    type: 'chat',
  },
  {
    id: 'Doubao-lite-4k',
    displayName: 'Doubao-lite-4k',
    description:
      'Doubao-lite offers ultra-fast responses and better value, with flexible options across scenarios.',
    type: 'chat',
  },
  {
    id: 'Doubao-lite-32k',
    displayName: 'Doubao-lite-32k',
    description:
      'Doubao-lite offers ultra-fast responses and better value, with flexible options across scenarios.',
    type: 'chat',
  },
  {
    id: 'Doubao-lite-128k',
    displayName: 'Doubao-lite-128k',
    description:
      'Doubao-lite offers ultra-fast responses and better value, with flexible options across scenarios.',
    type: 'chat',
  },
  {
    id: 'Doubao-pro-4k',
    displayName: 'Doubao-pro-4k',
    description:
      'Best-performing flagship model for complex tasks, strong in reference QA, summarization, creation, classification, and roleplay.',
    type: 'chat',
  },
  {
    id: 'Doubao-pro-32k',
    displayName: 'Doubao-pro-32k',
    description:
      'Best-performing flagship model for complex tasks, strong in reference QA, summarization, creation, classification, and roleplay.',
    type: 'chat',
  },
  {
    id: 'Doubao-pro-128k',
    displayName: 'Doubao-pro-128k',
    description:
      'Best-performing flagship model for complex tasks, strong in reference QA, summarization, creation, classification, and roleplay.',
    type: 'chat',
  },
  {
    id: 'Skylark2-pro-character-4k',
    displayName: 'Skylark2-pro-character-4k',
    description: 'Skylark 2nd-gen model.',
    type: 'chat',
  },
  {
    id: 'Skylark2-pro-32k',
    displayName: 'Skylark2-pro-32k',
    description: 'Skylark 2nd-gen model.',
    type: 'chat',
  },
  {
    id: 'Skylark2-pro-4k',
    displayName: 'Skylark2-pro-4k',
    description: 'Skylark 2nd-gen model.',
    type: 'chat',
  },
  {
    id: 'Skylark2-pro-turbo-8k',
    displayName: 'Skylark2-pro-turbo-8k',
    description: 'Skylark 2nd-gen model.',
    type: 'chat',
  },
  {
    id: 'Skylark2-lite-8k',
    displayName: 'Skylark2-lite-8k',
    description: 'Skylark 2nd-gen model.',
    type: 'chat',
  },
];

export default higressModels;
