import type { ChatModelCard } from '../types';

const infiniaiModels: ChatModelCard[] = [
  {
    id: 'deepseek-v4-pro',
    displayName: 'DeepSeek V4 Pro',
    description:
      'DeepSeek-V4-Pro 是 DeepSeek V4 系列旗舰 MoE 模型，总参数约 1.6T、激活约 49B，支持 1M 上下文，面向复杂推理、代码生成与智能体工作流。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 393_216,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 12, output: 24 },
    releasedAt: '2026-04-24',
  },
  {
    id: 'deepseek-v4-flash',
    displayName: 'DeepSeek V4 Flash',
    description:
      'DeepSeek-V4-Flash 是 DeepSeek V4 系列高吞吐 MoE 模型，总参数约 284B、激活约 13B，支持 1M 上下文，兼顾推理成本、响应速度与部署友好性。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 393_216,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 2 },
    releasedAt: '2026-04-24',
  },
  {
    id: 'kimi-k2.6',
    displayName: 'Kimi K2.6',
    description:
      'Kimi K2.6 是月之暗面开源原生多模态智能体模型，MoE 架构总参数约 1T、激活 32B，支持 256K 上下文，面向长程编程、代码驱动设计与自主任务执行。',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 131_072,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 6.5, output: 27 },
    releasedAt: '2026-04-17',
  },
  {
    id: 'mimo-v2-pro',
    displayName: 'MiMo-V2 Pro',
    description:
      'MiMo-V2-Pro 是小米旗舰基础模型，万亿参数 MoE 架构、激活 32B，支持 256K 上下文，面向复杂推理、长文档处理与智能体工作流优化。',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 262_144,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 7, output: 2.1 },
    releasedAt: '2026-04-15',
  },
  {
    id: 'glm-5.1',
    displayName: 'GLM-5.1',
    description:
      'GLM-5.1 是智谱新一代面向智能体工程的旗舰文本模型，在代码生成、仓库级工程任务、终端执行与长程智能体交互上进一步增强。',
    type: 'chat',
    contextWindowTokens: 198_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 8, output: 28 },
    releasedAt: '2026-04-08',
  },
  {
    id: 'kimi-k2.5',
    displayName: 'Kimi K2.5',
    description:
      'Kimi K2.5 是基于 Kimi-K2-Base 的开源原生多模态智能体模型，融合视觉理解与智能体能力，支持即时与思考两种模式。',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 4, output: 21 },
    releasedAt: '2026-04-02',
  },
  {
    id: 'qwen3-8b',
    displayName: 'Qwen3 8B',
    description: 'Qwen3 8B 是通义千问 3 系列的轻量级模型，提供出色的性能表现。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'qwen3-32b',
    displayName: 'Qwen3 32B',
    description: 'Qwen3 32B 是一款中等规模的高性能模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.9, output: 11.6 },
  },
  {
    id: 'deepseek-r1',
    displayName: 'DeepSeek R1',
    description: 'DeepSeek R1 是一款具备强大推理能力的先进模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek-v3',
    displayName: 'DeepSeek V3',
    description: 'DeepSeek V3 是一款高性能的通用语言模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'llama-3.1-70b-instruct',
    displayName: 'Llama 3.1 70B Instruct',
    description: 'Llama 3.1 70B Instruct 是 Meta 的大规模开源语言模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
  },
  {
    id: 'llama-3.1-8b-instruct',
    displayName: 'Llama 3.1 8B Instruct',
    description: 'Llama 3.1 8B Instruct 是一款轻量高效的指令模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
  },
  {
    id: 'glm-4',
    displayName: 'GLM-4',
    description: 'GLM-4 是智谱 AI 的旗舰对话模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { functionCall: true },
  },
  {
    id: 'minimax-m2.7',
    displayName: 'MiniMax M2.7',
    description:
      'MiniMax-M2.7 has reached or refreshed the latest SOTA benchmark in programming, tool calling and search, office productivity and many other scenarios, officially starting the journey of model recursive self-improvement.',
    type: 'chat',
    contextWindowTokens: 204_800,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
    releasedAt: '2026-03-17',
  },
  {
    id: 'deepseek-v3.2',
    displayName: 'DeepSeek V3.2',
    description:
      'DeepSeek-V3.2 is a model that balances high computational efficiency with excellent reasoning and agent performance.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 3 },
    releasedAt: '2025-12-02',
  },
  {
    id: 'deepseek-v3.2-thinking',
    displayName: 'DeepSeek V3.2 Thinking',
    description:
      'DeepSeek-V3.2 Thinking is the thinking mode variant of DeepSeek-V3.2, focused on reasoning tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 3 },
    releasedAt: '2025-12-02',
  },
  {
    id: 'glm-4.6v',
    displayName: 'GLM-4.6V',
    description:
      'GLM-4.6V (106B) is a foundational model designed for cloud and high-performance cluster scenarios.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'glm-5',
    displayName: 'GLM-5',
    description:
      'A strong reasoning and agentic model from Z.ai with 744B total parameters (40B active), built for complex systems engineering and long-horizon tasks.',
    type: 'chat',
    contextWindowTokens: 198_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 6, output: 22 },
    releasedAt: '2026-02-13',
  },
  {
    id: 'minimax-m2.5',
    displayName: 'MiniMax M2.5',
    description:
      'MiniMax-M2.5 is a state-of-the-art large language model designed for real-world productivity and coding tasks.',
    type: 'chat',
    contextWindowTokens: 204_800,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
    releasedAt: '2026-02-13',
  },
  {
    id: 'kimi-k2-thinking',
    displayName: 'Kimi K2 Thinking',
    description: 'Kimi K2 Thinking is the latest and most powerful open-source reasoning model.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
    releasedAt: '2025-11-07',
  },
  {
    id: 'deepseek-ocr',
    displayName: 'DeepSeek OCR',
    description:
      'DeepSeek-OCR is a vision-language model from DeepSeek AI focused on OCR and "contextual optical compression." It explores compressing contextual information from images, efficiently processes documents, and converts them into structured tex...',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-10-20',
  },
  {
    id: 'minimax-m2.1',
    displayName: 'MiniMax M2.1',
    description:
      'MiniMax-M2.1 is the latest version of the MiniMax series, optimized for multilingual programming and real-world complex tasks.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 200_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
  },
  {
    id: 'minimax-m2',
    displayName: 'MiniMax M2',
    description:
      'MiniMax-M2 is a Mixture of Experts (MoE) language model optimized for coding and agent workflows, with approximately 230B total parameters and approximately 10B active parameters.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 200_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
  },
  {
    id: 'glm-4.7',
    displayName: 'GLM-4.7',
    description:
      'GLM-4.7 is the latest large language model launched by Zhipu AI, with enhanced reasoning and generation capabilities.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 3, output: 14 },
  },
  {
    id: 'glm-4.6',
    displayName: 'GLM-4.6',
    description:
      'GLM-4.6 is the latest large language model launched by Zhipu AI, with enhanced reasoning and generation capabilities.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 3, output: 14 },
  },
  {
    id: 'deepseek-v3.2-exp',
    displayName: 'DeepSeek V3.2 Exp',
    description:
      'DeepSeek-V3.2-Exp is an experimental DeepSeek LLM with stronger reasoning and generation.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 3 },
  },
  {
    id: 'qwen3-vl-235b-a22b-instruct',
    displayName: 'Qwen3 VL 235B A22B Instruct',
    description:
      'Qwen3 VL 235B A22B Instruct is a multimodal model from Qwen, supporting vision understanding and reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen3-vl-235b-a22b-thinking',
    displayName: 'Qwen3 VL 235B A22B Thinking',
    description:
      'Qwen3 VL 235B A22B Thinking is a multimodal reasoning model from Qwen, supporting vision understanding and reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 2, output: 20 },
  },
  {
    id: 'deepseek-v3.1-terminus',
    displayName: 'DeepSeek V3.1 Terminus',
    description:
      'DeepSeek-V3.1-Terminus is a terminal-optimized LLM from DeepSeek, tailored for terminal devices.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'qwen3-next-80b-a3b-thinking',
    displayName: 'Qwen3 Next 80B A3B Thinking',
    description: 'A next-generation thinking-mode open-source model based on Qwen3.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 10 },
  },
  {
    id: 'qwen3-next-80b-a3b-instruct',
    displayName: 'Qwen3 Next 80B A3B Instruct',
    description: 'A next-generation non-thinking open-source model based on Qwen3.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 10 },
  },
  {
    id: 'deepseek-v3.1',
    displayName: 'DeepSeek V3.1',
    description:
      'DeepSeek V3.1 uses a hybrid reasoning architecture with both thinking and non-thinking modes.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'baichuan-m2-32b',
    displayName: 'Baichuan M2 32B',
    description: 'Baichuan M2 32B is a MoE model from Baichuan Intelligence with strong reasoning.',
    type: 'chat',
    contextWindowTokens: 64_000,
    maxOutput: 8_192,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2.9, output: 11.6 },
  },
  {
    id: 'glm-4.5v',
    displayName: 'GLM-4.5V',
    description:
      'GLM-4.5V is a multimodal model from Zhipu AI for vision understanding and reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'glm-4.5',
    displayName: 'GLM-4.5',
    description:
      'GLM-4.5 is a hybrid reasoning model from Zhipu AI built for agents, with thinking and non-thinking modes.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'glm-4.5-air',
    displayName: 'GLM-4.5-Air',
    description: 'GLM-4.5-Air is a lightweight LLM from Zhipu AI with efficient reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.6, output: 4 },
  },
  {
    id: 'qwen3-coder-480b-a35b-instruct',
    displayName: 'Qwen3 Coder 480B A35B',
    description: 'The open-source Qwen code model.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 9, output: 36 },
  },
  {
    id: 'qwen3-235b-a22b-instruct-2507',
    displayName: 'Qwen3 235B A22B Instruct 2507',
    description: 'A non-thinking open-source model based on Qwen3.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'kimi-k2-instruct',
    displayName: 'Kimi K2 Instruct',
    description: 'Kimi K2 Instruct is a Moonshot AI LLM with ultra-long context handling.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'ernie-4.5-300b-a47b',
    displayName: 'ERNIE 4.5 300B A47B',
    description:
      'ERNIE 4.5 300B A47B is Baidu ERNIE’s ultra-large MoE model with excellent reasoning.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 8_192,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2.9, output: 2.9 },
  },
  {
    id: 'ernie-4.5-21b-a3b',
    displayName: 'ERNIE 4.5 21B A3B',
    description:
      'ERNIE 4.5 21B A3B is Baidu ERNIE’s MoE model with strong reasoning and multilingual abilities.',
    type: 'chat',
    contextWindowTokens: 120_000,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 1, output: 1 },
  },
  {
    id: 'qwen3-14b',
    displayName: 'Qwen3 14B',
    description:
      'Qwen3-14B is the third-generation Qwen LLM with 14.8B parameters, designed for efficient reasoning and multilingual tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen3-30b-a3b',
    displayName: 'Qwen3 30B A3B',
    description:
      'Qwen3-30B-A3B is a third-generation Qwen LLM using a MoE architecture with 30.5B total parameters and 3.3B active per token.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.2, output: 8.7 },
  },
  {
    id: 'qwen3-235b-a22b',
    displayName: 'Qwen3 235B A22B',
    description:
      'Qwen3-235B-A22B is a third-generation Qwen LLM using a MoE architecture with 235B total parameters and 22B active per token.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 5, output: 20 },
  },
  {
    id: 'qwen2.5-vl-72b-instruct',
    displayName: 'Qwen2.5 VL 72B Instruct',
    description:
      'The Qwen2.5-VL series improves intelligence, practicality, and applicability, performing better in natural dialogue, content creation, professional knowledge services, and code development.',
    type: 'chat',
    contextWindowTokens: 125_000,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 10, output: 10 },
  },
  {
    id: 'qwen2.5-vl-32b-instruct',
    displayName: 'Qwen2.5 VL 32B Instruct',
    description:
      'The Qwen2.5-VL series improves intelligence, practicality, and applicability, performing better in natural dialogue, content creation, professional knowledge services, and code development.',
    type: 'chat',
    contextWindowTokens: 125_000,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 5.8, output: 5.8 },
  },
  {
    id: 'qwen2.5-vl-7b-instruct',
    displayName: 'Qwen2.5 VL 7B Instruct',
    description:
      'The Qwen2.5-VL series improves intelligence, practicality, and applicability, performing better in natural dialogue, content creation, professional knowledge services, and code development.',
    type: 'chat',
    contextWindowTokens: 125_000,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 2 },
  },
  {
    id: 'qwq-32b',
    displayName: 'QwQ 32B',
    description: 'QwQ 32B is a Qwen reasoning-focused model built for reasoning tasks.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 8_192,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2.9, output: 2.9 },
  },
  {
    id: 'deepseek-r1-distill-qwen-32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description: 'DeepSeek R1 Distill Qwen 32B is a DeepSeek distilled model based on Qwen.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 8_192,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2.9, output: 2.9 },
  },
  {
    id: 'megrez-3b-instruct',
    displayName: 'Megrez 3B Instruct',
    description: 'Megrez 3B Instruct is a small, efficient model from Wuwen Xinqiong.',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'qwen2.5-32b-instruct',
    displayName: 'Qwen2.5 32B Instruct',
    description: 'Qwen2.5 is the latest in the Qwen LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2.9, output: 2.9 },
  },
  {
    id: 'qwen2.5-72b-instruct',
    displayName: 'Qwen2.5 72B Instruct',
    description: 'Qwen2.5 is the latest in the Qwen LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 5, output: 5 },
  },
  {
    id: 'qwen2.5-14b-instruct',
    displayName: 'Qwen2.5 14B Instruct',
    description: 'Qwen2.5 is the latest in the Qwen LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 2, output: 2 },
  },
  {
    id: 'qwen2.5-7b-instruct',
    displayName: 'Qwen2.5 7B Instruct',
    description: 'Qwen2.5 is the latest in the Qwen LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 1 },
  },
  {
    id: 'qwen2.5-coder-32b-instruct',
    displayName: 'Qwen2.5 Coder 32B Instruct',
    description: 'Qwen2.5-Coder is the latest code-focused Qwen LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2.9, output: 2.9 },
  },
  {
    id: 'gpt-oss-120b',
    displayName: 'GPT-OSS-120B',
    description: 'Access requires an application.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    pricing: { currency: 'CNY', input: 0.8, output: 3.2 },
  },
  {
    id: 'gpt-oss-20b',
    displayName: 'GPT-OSS-20B',
    description: 'Access requires an application.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    pricing: { currency: 'CNY', input: 0.4, output: 1.6 },
  },
  {
    id: 'pro-deepseek-r1',
    displayName: 'DeepSeek R1 (Pro)',
    description: 'Enterprise dedicated service model with bundled concurrency.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'pro-deepseek-v3',
    displayName: 'DeepSeek V3 (Pro)',
    description: 'Enterprise dedicated service model with bundled concurrency.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
];

export default infiniaiModels;
