import type { ChatModelCard } from '../types';

const mistralModels: ChatModelCard[] = [
  {
    id: 'mistral-medium-3.1-latest',
    displayName: 'Mistral Medium 3.1',
    description: 'Mistral Medium 3.1 是 Mistral 最新的中型模型，在复杂推理和编码任务上表现出色。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 8_192,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 0.4,
      output: 2,
    },
    releasedAt: '2025-05-14',
  },
  {
    id: 'magistral-medium-latest',
    displayName: 'Magistral Medium 1.2',
    description: 'Magistral Medium 是 Mistral 的旗舰推理模型，专为复杂推理任务设计。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 32_000,
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 2,
      output: 5,
    },
    releasedAt: '2025-05-14',
  },
  {
    id: 'magistral-small-2509',
    displayName: 'Magistral Small 2509',
    description: 'Magistral Small 是轻量级推理模型，在速度和推理能力之间取得平衡。',
    type: 'chat',
    contextWindowTokens: 32_000,
    maxOutput: 16_000,
    abilities: {
      functionCall: true,
      reasoning: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 0.2,
      output: 0.6,
    },
    releasedAt: '2025-09-25',
  },
  {
    id: 'mistral-large-latest',
    displayName: 'Mistral Large',
    description: 'Mistral Large 是 Mistral 最强大的模型，适合复杂任务。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 8_192,
    enabled: true,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 2,
      output: 6,
    },
  },
  {
    id: 'mistral-large-2411',
    displayName: 'Mistral Large 2411',
    description: 'Mistral Large 2411 版本。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 8_192,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 2,
      output: 6,
    },
    releasedAt: '2024-11-01',
  },
  {
    id: 'mistral-large-2407',
    displayName: 'Mistral Large 2407',
    description: 'Mistral Large 2407 版本。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 8_192,
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    pricing: {
      input: 2,
      output: 6,
    },
    releasedAt: '2024-07-01',
  },
  {
    id: 'mistral-small-latest',
    displayName: 'Mistral Small',
    description: 'Mistral Small 是快速、经济的选择，适合简单任务。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    enabled: true,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 0.2,
      output: 0.6,
    },
  },
  {
    id: 'mistral-small-2503',
    displayName: 'Mistral Small 2503',
    description: 'Mistral Small 2503 版本。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 0.2,
      output: 0.6,
    },
    releasedAt: '2025-03-01',
  },
  {
    id: 'mistral-small-2409',
    displayName: 'Mistral Small 2409',
    description: 'Mistral Small 2409 版本。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    pricing: {
      input: 0.2,
      output: 0.6,
    },
    releasedAt: '2024-09-01',
  },
  {
    id: 'open-mistral-nemo',
    displayName: 'Mistral Nemo',
    description: 'Mistral Nemo 是开源的高性能模型，支持函数调用和结构化输出。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    pricing: {
      input: 0.15,
      output: 0.15,
    },
    releasedAt: '2024-07-18',
  },
  {
    id: 'codestral-latest',
    displayName: 'Codestral 2508',
    description: 'Codestral 专门针对代码生成和理解优化。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 8_192,
    enabled: true,
    abilities: {
      functionCall: true,
    },
    pricing: {
      input: 0.2,
      output: 0.6,
    },
    releasedAt: '2025-07-30',
  },
  {
    id: 'codestral-2501',
    displayName: 'Codestral 2501',
    description: 'Codestral 2501 版本，针对代码任务优化。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 8_192,
    abilities: {
      functionCall: true,
    },
    pricing: {
      input: 0.3,
      output: 0.9,
    },
    releasedAt: '2025-01-01',
  },
  {
    id: 'open-codestral-mamba',
    displayName: 'Codestral Mamba',
    description: 'Codestral Mamba 是基于 Mamba 架构的开源代码模型。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
    },
    pricing: {
      input: 0.25,
      output: 0.25,
    },
  },
  {
    id: 'pixtral-large-latest',
    displayName: 'Pixtral Large',
    description: 'Pixtral Large 是 Mistral 的大型多模态视觉模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 8_192,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 2,
      output: 6,
    },
  },
  {
    id: 'pixtral-12b-2409',
    displayName: 'Pixtral 12B',
    description: 'Pixtral 12B 是 Mistral 的中型多模态视觉模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: {
      input: 0.15,
      output: 0.15,
    },
    releasedAt: '2024-09-01',
  },
  {
    id: 'ministral-3b-latest',
    displayName: 'Ministral 3B',
    description: 'Ministral 3B 是 Mistral 最轻量的模型，适合边缘部署和低延迟场景。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    pricing: {
      input: 0.04,
      output: 0.04,
    },
    releasedAt: '2024-10-01',
  },
  {
    id: 'ministral-8b-latest',
    displayName: 'Ministral 8B',
    description: 'Ministral 8B 是轻量级模型，在效率和性能之间取得良好平衡。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    pricing: {
      input: 0.1,
      output: 0.1,
    },
    releasedAt: '2024-10-01',
  },
  {
    id: 'mistral-medium-latest',
    displayName: 'Mistral Medium',
    description: 'Mistral Medium 在性能和成本之间取得平衡。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: {
      functionCall: true,
      structuredOutput: true,
    },
    pricing: {
      input: 2.7,
      output: 8.1,
    },
    legacy: true,
  },
];

export default mistralModels;
