import type { ChatModelCard } from '../types';

const nebiusModels: ChatModelCard[] = [
  {
    id: 'moonshotai/Kimi-K2-Instruct',
    displayName: 'Kimi-K2-Instruct',
    description: 'Moonshot Kimi K2模型，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'moonshotai',
    abilities: { functionCall: true },
    pricing: { input: 0.5, output: 2.4 },
  },
  {
    id: 'openai/gpt-oss-120b',
    displayName: 'GPT OSS 120B',
    description: 'OpenAI开源120B模型，Nebius高速托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    organization: 'openai',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.15, output: 0.6 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1-0528',
    displayName: 'DeepSeek R1 0528',
    description: 'DeepSeek R1最新版，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 163_840,
    organization: 'deepseek',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.8, output: 2.4 },
  },
  {
    id: 'deepseek-ai/DeepSeek-V3-0324',
    displayName: 'DeepSeek V3 0324',
    description: 'DeepSeek V3最新版，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 163_840,
    organization: 'deepseek',
    abilities: { functionCall: true },
    pricing: { input: 0.5, output: 1.5 },
  },
  {
    id: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
    displayName: 'Qwen3 235B Instruct',
    description: 'Qwen3 235B大模型，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { input: 0.2, output: 0.6 },
  },
  {
    id: 'Qwen/Qwen3-32B',
    displayName: 'Qwen3 32B',
    description: 'Qwen3 32B模型，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 40_960,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.1, output: 0.3 },
  },
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct',
    displayName: 'Llama 3.3 70B Instruct',
    description: 'Meta Llama 3.3 70B，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'meta',
    abilities: { functionCall: true },
    pricing: { input: 0.13, output: 0.4 },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-405B-Instruct',
    displayName: 'Llama 3.1 405B Instruct',
    description: 'Meta Llama 3.1 405B，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { input: 1, output: 3 },
  },
  {
    id: 'Qwen/Qwen2.5-72B-Instruct',
    displayName: 'Qwen2.5 72B Instruct',
    description: 'Qwen2.5 72B模型，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { input: 0.13, output: 0.4 },
  },
  {
    id: 'Qwen/QwQ-32B',
    displayName: 'QwQ 32B',
    description: 'Qwen QwQ推理模型，Nebius托管。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.15, output: 0.45 },
  },
  {
    id: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    displayName: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { input: 0.4, output: 1.8 },
  },
  {
    id: 'openai/gpt-oss-20b',
    displayName: 'gpt-oss-20b',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'openai',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.05, output: 0.2 },
  },
  {
    id: 'zai-org/GLM-4.5',
    displayName: 'GLM-4.5',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'zai-org',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.6, output: 2.2 },
  },
  {
    id: 'zai-org/GLM-4.5-Air',
    displayName: 'GLM-4.5-Air',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'zai-org',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.2, output: 1.2 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1-0528-fast',
    displayName: 'DeepSeek-R1-0528 (fast)',
    type: 'chat',
    contextWindowTokens: 32_768,
    organization: 'deepseek',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 2, output: 6 },
  },
  {
    id: 'Qwen/Qwen3-32B-fast',
    displayName: 'Qwen3-32B (fast)',
    type: 'chat',
    contextWindowTokens: 40_960,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.2, output: 0.6 },
  },
  {
    id: 'nvidia/Llama-3_1-Nemotron-Ultra-253B-v1',
    displayName: 'Llama-3_1-Nemotron-Ultra-253B-v1',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'nvidia',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.6, output: 1.8 },
  },
  {
    id: 'deepseek-ai/DeepSeek-V3-0324-fast',
    displayName: 'DeepSeek-V3-0324 (fast)',
    type: 'chat',
    contextWindowTokens: 32_768,
    organization: 'deepseek',
    abilities: { functionCall: true },
    pricing: { input: 0.75, output: 2.25 },
  },
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct-fast',
    displayName: 'Llama-3.3-70B-Instruct (fast)',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'meta',
    abilities: { functionCall: true },
    pricing: { input: 0.25, output: 0.75 },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    displayName: 'Meta-Llama-3.1-8B-Instruct',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'meta',
    abilities: { functionCall: true },
    pricing: { input: 0.02, output: 0.06 },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-8B-Instruct-fast',
    displayName: 'Meta-Llama-3.1-8B-Instruct (fast)',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'meta',
    abilities: { functionCall: true },
    pricing: { input: 0.03, output: 0.09 },
  },
  {
    id: 'Qwen/Qwen2.5-Coder-7B-fast',
    displayName: 'Qwen2.5-Coder-7B (fast)',
    type: 'chat',
    contextWindowTokens: 32_768,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { input: 0.03, output: 0.09 },
  },
  {
    id: 'google/gemma-2-2b-it',
    displayName: 'Gemma-2-2b-it',
    type: 'chat',
    contextWindowTokens: 8_192,
    organization: 'google',
    pricing: { input: 0.02, output: 0.06 },
  },
  {
    id: 'google/gemma-2-9b-it-fast',
    displayName: 'Gemma-2-9b-it (fast)',
    type: 'chat',
    contextWindowTokens: 8_192,
    organization: 'google',
    abilities: { functionCall: true },
    pricing: { input: 0.03, output: 0.09 },
  },
  {
    id: 'Qwen/QwQ-32B-fast',
    displayName: 'QwQ-32B (fast)',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.5, output: 1.5 },
  },
  {
    id: 'NousResearch/Hermes-4-70B',
    displayName: 'Hermes-4-70B',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'NousResearch',
    abilities: { functionCall: true },
    pricing: { input: 0.13, output: 0.4 },
  },
  {
    id: 'NousResearch/Hermes-4-405B',
    displayName: 'Hermes-4-405B',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'NousResearch',
    abilities: { functionCall: true },
    pricing: { input: 1, output: 3 },
  },
  {
    id: 'Qwen/Qwen3-30B-A3B-Thinking-2507',
    displayName: 'Qwen3-30B-A3B-Thinking-2507',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.1, output: 0.3 },
  },
  {
    id: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
    displayName: 'Qwen3-30B-A3B-Instruct-2507',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { input: 0.1, output: 0.3 },
  },
  {
    id: 'Qwen/Qwen3-Coder-30B-A3B-Instruct',
    displayName: 'Qwen3-Coder-30B-A3B-Instruct',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { input: 0.1, output: 0.3 },
  },
  {
    id: 'meta-llama/Llama-Guard-3-8B',
    displayName: 'Meta-Llama-Guard-3-8B',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'meta',
    abilities: { functionCall: true },
    pricing: { input: 0.02, output: 0.06 },
  },
  {
    id: 'google/gemma-3-27b-it',
    displayName: 'Gemma-3-27b-it',
    type: 'chat',
    contextWindowTokens: 110_000,
    organization: 'google',
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.1, output: 0.3 },
  },
  {
    id: 'google/gemma-3-27b-it-fast',
    displayName: 'Gemma-3-27b-it (fast)',
    type: 'chat',
    contextWindowTokens: 110_000,
    organization: 'google',
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.2, output: 0.6 },
  },
  {
    id: 'Qwen/Qwen2.5-VL-72B-Instruct',
    displayName: 'Qwen2.5-VL-72B-Instruct',
    type: 'chat',
    contextWindowTokens: 32_000,
    organization: 'Qwen',
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.25, output: 0.75 },
  },
];

export default nebiusModels;
