import type { ChatModelCard } from '../types';

const novitaModels: ChatModelCard[] = [
  {
    id: 'deepseek/deepseek-chat-v3-0324',
    displayName: 'DeepSeek V3 0324',
    description: 'Novita托管的DeepSeek V3最新版本。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: { functionCall: true },
  },
  {
    id: 'deepseek/deepseek-r1',
    displayName: 'DeepSeek R1',
    description: 'Novita托管的DeepSeek推理模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: { reasoning: true },
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    displayName: 'Qwen 2.5 72B Instruct',
    description: 'Novita托管的Qwen2.5 72B模型。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 0.38, output: 0.4 },
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    displayName: 'Llama 3.3 70B Instruct',
    description: 'Novita托管的Meta Llama 3.3 70B模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { input: 0.13, output: 0.39 },
  },
  {
    id: 'qwen/qwen3-vl-235b-a22b-instruct',
    displayName: 'Qwen3 VL 235B A22B Instruct',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.3, output: 3 },
  },
  {
    id: 'qwen/qwen3-vl-235b-a22b-thinking',
    displayName: 'Qwen3 VL 235B A22B Thinking',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { reasoning: true, vision: true },
    pricing: { input: 0.98, output: 3.95 },
  },
  {
    id: 'qwen/qwen3-next-80b-a3b-thinking',
    displayName: 'Qwen3 Next 80B A3B Thinking',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.15, output: 1.5 },
  },
  {
    id: 'qwen/qwen3-next-80b-a3b-instruct',
    displayName: 'Qwen3 Next 80B A3B Instruct',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { input: 0.15, output: 1.5 },
  },
  {
    id: 'qwen/qwen-mt-plus',
    displayName: 'Qwen MT Plus',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 2_048,
    pricing: { input: 0.25, output: 0.75 },
  },
  {
    id: 'moonshotai/kimi-k2-0905',
    displayName: 'Kimi K2 0905',
    description:
      'kimi-k2-0905-preview offers a 256k context window, stronger agentic coding, better front-end code quality, and improved context understanding.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true },
    pricing: { input: 0.6, output: 2.5 },
    releasedAt: '2025-09-05',
  },
  {
    id: 'deepseek/deepseek-v3.2-exp',
    displayName: 'Deepseek V3.2 Exp',
    type: 'chat',
    contextWindowTokens: 163_840,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.27, output: 0.41 },
  },
  {
    id: 'deepseek/deepseek-v3.1-terminus',
    displayName: 'DeepSeek V3.1 Terminus',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.27, output: 1 },
  },
  {
    id: 'deepseek/deepseek-v3.1',
    displayName: 'DeepSeek V3.1',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.27, output: 1 },
  },
  {
    id: 'qwen/qwen3-coder-480b-a35b-instruct',
    displayName: 'Qwen3 Coder 480B A35B Instruct',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true },
    pricing: { input: 0.29, output: 1.2 },
  },
  {
    id: 'openai/gpt-oss-120b',
    displayName: 'OpenAI GPT OSS 120B',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.05, output: 0.25 },
  },
  {
    id: 'openai/gpt-oss-20b',
    displayName: 'OpenAI: GPT OSS 20B',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { input: 0.04, output: 0.15 },
  },
  {
    id: 'zai-org/glm-4.5v',
    displayName: 'GLM-4.5V',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 16_384,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { input: 0.6, output: 1.8 },
  },
  {
    id: 'zai-org/glm-4.5',
    displayName: 'GLM-4.5',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 98_304,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.6, output: 2.2 },
  },
  {
    id: 'qwen/qwen3-235b-a22b-instruct-2507',
    displayName: 'Qwen3 235B A22B Instruct 2507',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    abilities: { functionCall: true },
    pricing: { input: 0.15, output: 0.8 },
  },
  {
    id: 'qwen/qwen3-235b-a22b-thinking-2507',
    displayName: 'Qwen3 235B A22b Thinking 2507',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.3, output: 3 },
  },
  {
    id: 'baichuan/baichuan-m2-32b',
    displayName: 'BaiChuan M2 32B',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { input: 0.07, output: 0.07 },
  },
  {
    id: 'moonshotai/kimi-k2-instruct',
    displayName: 'Kimi K2 0711',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { input: 0.57, output: 2.3 },
  },
  {
    id: 'thudm/glm-4.1v-9b-thinking',
    displayName: 'GLM 4.1V 9B Thinking',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { reasoning: true, vision: true },
    pricing: { input: 0.035, output: 0.138 },
  },
  {
    id: 'baidu/ernie-4.5-21B-a3b',
    displayName: 'ERNIE 4.5 21B A3B',
    type: 'chat',
    contextWindowTokens: 120_000,
    abilities: { functionCall: true },
    pricing: { input: 0.07, output: 0.28 },
  },
  {
    id: 'baidu/ernie-4.5-21B-a3b-thingking',
    displayName: 'ERNIE 4.5 21B A3B Thinking',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.07, output: 0.28 },
  },
  {
    id: 'baidu/ernie-4.5-300b-a47b-paddle',
    displayName: 'ERNIE 4.5 300B A47B Paddle',
    type: 'chat',
    contextWindowTokens: 123_000,
    abilities: { reasoning: true },
    pricing: { input: 0.28, output: 1.1 },
  },
  {
    id: 'baidu/ernie-4.5-vl-28b-a3b',
    displayName: 'ERNIE 4.5 VL 28B A3B',
    type: 'chat',
    contextWindowTokens: 30_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { input: 0.14, output: 0.56 },
  },
  {
    id: 'baidu/ernie-4.5-vl-424b-a47b',
    displayName: 'ERNIE 4.5 VL 424B A47B',
    type: 'chat',
    contextWindowTokens: 123_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { input: 0.42, output: 1.25 },
  },
  {
    id: 'minimaxai/minimax-m1-80k',
    displayName: 'MiniMax M1 80K',
    type: 'chat',
    contextWindowTokens: 1_000_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.55, output: 2.2 },
  },
  {
    id: 'qwen/qwen3-4b-fp8',
    displayName: 'Qwen3 4B FP8',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { reasoning: true },
    pricing: { input: 0.03, output: 0.03 },
  },
  {
    id: 'qwen/qwen3-235b-a22b-fp8',
    displayName: 'Qwen3 235B A22B FP8',
    type: 'chat',
    contextWindowTokens: 40_960,
    abilities: { reasoning: true },
    pricing: { input: 0.2, output: 0.8 },
  },
  {
    id: 'qwen/qwen3-30b-a3b-fp8',
    displayName: 'Qwen3 30B A3B FP8',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { reasoning: true },
    pricing: { input: 0.09, output: 0.45 },
  },
  {
    id: 'qwen/qwen3-32b-fp8',
    displayName: 'Qwen3 32B FP8',
    type: 'chat',
    contextWindowTokens: 40_960,
    abilities: { reasoning: true },
    pricing: { input: 0.1, output: 0.45 },
  },
  {
    id: 'qwen/qwen3-8b-fp8',
    displayName: 'Qwen3 8B FP8',
    type: 'chat',
    contextWindowTokens: 128_000,
    pricing: { input: 0.035, output: 0.138 },
  },
  {
    id: 'meta-llama/llama-4-scout-17b-16e-instruct',
    displayName: 'Llama 4 Scout 17B Instruct',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.1, output: 0.5 },
  },
  {
    id: 'meta-llama/llama-4-maverick-17b-128e-instruct-fp8',
    displayName: 'Llama 4 Maverick 17B Instruct',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 8_192,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 0.17, output: 0.85 },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    displayName: 'Llama 3.1 8B Instruct',
    description:
      'Llama 3.1 8B Instruct is optimized for high-quality dialogue, outperforming many leading closed models.',
    type: 'chat',
    contextWindowTokens: 16_384,
    pricing: { input: 0.02, output: 0.05 },
  },
  {
    id: 'meta-llama/llama-3-8b-instruct',
    displayName: 'Llama 3 8B Instruct',
    description:
      'Llama 3 8B Instruct is optimized for high-quality dialogue, outperforming many closed models.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { input: 0.04, output: 0.04 },
  },
  {
    id: 'meta-llama/llama-3-70b-instruct',
    displayName: 'Llama 3 70B Instruct',
    description:
      'Llama 3 70B Instruct is optimized for high-quality dialogue and performs strongly in human evaluations.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { input: 0.51, output: 0.74 },
  },
  {
    id: 'google/gemma-3-27b-it',
    displayName: 'Gemma 3 27B',
    description:
      'Gemma 3 27B is a Google open-source language model setting a new bar for efficiency and performance.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { input: 0.119, output: 0.2 },
  },
  {
    id: 'google/gemma-3-12b-it',
    displayName: 'Gemma 3 12B',
    description:
      'Gemma 3 12B is a Google open-source language model setting a new bar for efficiency and performance.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    pricing: { input: 0.05, output: 0.1 },
  },
  {
    id: 'mistralai/mistral-nemo',
    displayName: 'Mistral Nemo',
    description:
      'Mistral Nemo is a 7.3B model with multilingual support and strong coding performance.',
    type: 'chat',
    contextWindowTokens: 60_288,
    pricing: { input: 0.04, output: 0.17 },
  },
  {
    id: 'microsoft/wizardlm-2-8x22b',
    displayName: 'WizardLM-2 8x22B',
    description:
      'WizardLM-2 8x22B is Microsoft AI’s most advanced Wizard model with highly competitive performance.',
    type: 'chat',
    contextWindowTokens: 65_535,
    pricing: { input: 0.62, output: 0.62 },
  },
  {
    id: 'nousresearch/hermes-2-pro-llama-3-8b',
    displayName: 'Hermes 2 Pro Llama 3 8B',
    description:
      'Hermes 2 Pro Llama 3 8B is an updated Nous Hermes 2 version with the latest internally developed datasets.',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { input: 0.14, output: 0.14 },
  },
  {
    id: 'gryphe/mythomax-l2-13b',
    displayName: 'MythoMax l2 13B',
    description:
      'MythoMax L2 13B is a creative, intelligent language model merged from multiple top models.',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { input: 0.09, output: 0.09 },
  },
  {
    id: 'deepseek/deepseek-prover-v2-671b',
    displayName: 'Deepseek Prover V2 671B',
    type: 'chat',
    contextWindowTokens: 160_000,
    pricing: { input: 0.7, output: 2.5 },
  },
  {
    id: 'deepseek/deepseek-v3-turbo',
    displayName: 'Deepseek V3 Turbo',
    type: 'chat',
    contextWindowTokens: 64_000,
    abilities: { functionCall: true },
    pricing: { input: 0.4, output: 1.3 },
  },
  {
    id: 'deepseek/deepseek-v3-0324',
    displayName: 'Deepseek V3 0324',
    type: 'chat',
    contextWindowTokens: 163_840,
    abilities: { functionCall: true },
    pricing: { input: 0.28, output: 1.14 },
  },
  {
    id: 'deepseek/deepseek-r1-0528',
    displayName: 'Deepseek R1 0528',
    type: 'chat',
    contextWindowTokens: 163_840,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.7, output: 2.5 },
  },
  {
    id: 'deepseek/deepseek-r1-0528-qwen3-8b',
    displayName: 'DeepSeek R1 0528 Qwen3 8B',
    type: 'chat',
    contextWindowTokens: 128_000,
    abilities: { reasoning: true },
    pricing: { input: 0.06, output: 0.09 },
  },
  {
    id: 'deepseek/deepseek-r1-turbo',
    displayName: 'Deepseek R1 Turbo',
    type: 'chat',
    contextWindowTokens: 64_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.7, output: 2.5 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-llama-70b',
    displayName: 'Deepseek R1 Distill Llama 70B',
    type: 'chat',
    contextWindowTokens: 32_000,
    abilities: { reasoning: true },
    pricing: { input: 0.8, output: 0.8 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-qwen-14b',
    displayName: 'Deepseek R1 Distill Qwen 14B',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 16_384,
    abilities: { reasoning: true },
    pricing: { input: 0.15, output: 0.15 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-qwen-32b',
    displayName: 'Deepseek R1 Distill Qwen 32B',
    type: 'chat',
    contextWindowTokens: 64_000,
    abilities: { reasoning: true },
    pricing: { input: 0.3, output: 0.3 },
  },
  {
    id: 'Sao10K/L3-8B-Stheno-v3.2',
    displayName: 'L3 8B Stheno v3.2',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { input: 0.05, output: 0.05 },
  },
  {
    id: 'sao10k/l3-70b-euryale-v2.1',
    displayName: 'L3 70B Euryale v2.1',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 1.48, output: 1.48 },
  },
  {
    id: 'sophosympatheia/midnight-rose-70b',
    displayName: 'Midnight Rose 70B',
    type: 'chat',
    contextWindowTokens: 4_096,
    pricing: { input: 0.8, output: 0.8 },
  },
  {
    id: 'sao10k/l3-8b-lunaris',
    displayName: 'L3 8B Lunaris',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { input: 0.05, output: 0.05 },
  },
  {
    id: 'qwen/qwen2.5-vl-72b-instruct',
    displayName: 'Qwen2.5 VL 72B Instruct',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { vision: true },
    pricing: { input: 0.8, output: 0.8 },
  },
  {
    id: 'meta-llama/llama-3.2-3b-instruct',
    displayName: 'Llama 3.2 3B Instruct',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { input: 0.03, output: 0.05 },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct-bf16',
    displayName: 'Llama 3.1 8B Instruct BF16',
    type: 'chat',
    contextWindowTokens: 8_192,
    pricing: { input: 0.06, output: 0.06 },
  },
  {
    id: 'sao10k/l31-70b-euryale-v2.2',
    displayName: 'L31 70B Euryale v2.2',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { functionCall: true },
    pricing: { input: 1.48, output: 1.48 },
  },
  {
    id: 'qwen/qwen2.5-7b-instruct',
    displayName: 'Qwen2.5 7B Instruct',
    type: 'chat',
    contextWindowTokens: 32_000,
    abilities: { functionCall: true },
    pricing: { input: 0.07, output: 0.07 },
  },
];

export default novitaModels;
