import type { ChatModelCard } from '../types';

const ppioModels: ChatModelCard[] = [
  {
    id: 'deepseek/deepseek-r1',
    displayName: 'DeepSeek R1',
    description: 'DeepSeek R1 是一款具备强大推理能力的先进模型，擅长处理复杂逻辑和数学问题。',
    type: 'chat',
    contextWindowTokens: 65_536,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek/deepseek-v3',
    displayName: 'DeepSeek V3',
    description: 'DeepSeek V3 是一款高性能通用大语言模型，提供卓越的生成和理解能力。',
    type: 'chat',
    contextWindowTokens: 65_536,
    enabled: true,
    pricing: { currency: 'CNY', input: 1, output: 2 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-qwen-32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description: 'DeepSeek R1 Distill Qwen 32B 是优化后的轻量级推理模型。',
    type: 'chat',
    contextWindowTokens: 64_000,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2.18, output: 2.18 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-llama-70b',
    displayName: 'DeepSeek R1 Distill Llama 70B',
    description: 'DeepSeek R1 Distill Llama 70B 是基于 Llama 架构的蒸馏模型。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 5.8, output: 5.8 },
  },
  {
    id: 'qwen/qwen2.5-72b-instruct',
    displayName: 'Qwen2.5 72B Instruct',
    description: 'Qwen2.5 72B Instruct 是通义千问的旗舰大模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    pricing: { input: 0.3, output: 0.9 },
  },
  {
    id: 'meta-llama/llama-3.1-70b-instruct',
    displayName: 'Llama 3.1 70B Instruct',
    description: 'Llama 3.1 70B Instruct 是 Meta 发布的高性能开源模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 2.45, output: 2.82 },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    displayName: 'Llama 3.1 8B Instruct',
    description: 'Llama 3.1 8B Instruct 是一款轻量高效的指令模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.4, output: 0.4 },
  },
  {
    id: 'deepseek/deepseek-r1/community',
    displayName: 'DeepSeek: DeepSeek R1 (Community)',
    description:
      'DeepSeek R1 is the latest open-source model released by the DeepSeek team, with very strong reasoning performance, especially in math, coding, and reasoning tasks, comparable to OpenAI o1.',
    type: 'chat',
    contextWindowTokens: 64_000,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek/deepseek-v3/community',
    displayName: 'DeepSeek: DeepSeek V3 (Community)',
    description:
      'DeepSeek-V3 delivers a major breakthrough in reasoning speed over previous models.',
    type: 'chat',
    contextWindowTokens: 64_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 1, output: 2 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-qwen-14b',
    displayName: 'DeepSeek: DeepSeek R1 Distill Qwen 14B',
    description:
      'DeepSeek R1 Distill Qwen 14B is a distilled LLM based on Qwen 2.5 14B, trained using DeepSeek R1 outputs.',
    type: 'chat',
    contextWindowTokens: 64_000,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 1 },
  },
  {
    id: 'deepseek/deepseek-r1-distill-llama-8b',
    displayName: 'DeepSeek: DeepSeek R1 Distill Llama 8B',
    description:
      'DeepSeek R1 Distill Llama 8B is a distilled LLM based on Llama-3.1-8B-Instruct, trained using DeepSeek R1 outputs.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 0.3, output: 0.3 },
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    displayName: 'qwen/qwen-2.5-72b-instruct',
    description: 'Qwen2.5-72B-Instruct is one of Alibaba Cloud’s latest LLM releases.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    pricing: { currency: 'CNY', input: 2.75, output: 2.88 },
  },
  {
    id: 'qwen/qwen-2-vl-72b-instruct',
    displayName: 'qwen/qwen-2-vl-72b-instruct',
    description:
      'Qwen2-VL is the latest iteration of Qwen-VL, reaching state-of-the-art performance on vision benchmarks such as MathVista, DocVQA, RealWorldQA, and MTVQA.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 4.5, output: 4.5 },
  },
  {
    id: 'meta-llama/llama-3.2-3b-instruct',
    displayName: 'meta-llama/llama-3.2-3b-instruct',
    description: 'meta-llama/llama-3.2-3b-instruct',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.216, output: 0.36 },
  },
  {
    id: 'qwen/qwen2.5-32b-instruct',
    displayName: 'qwen/qwen2.5-32b-instruct',
    description: 'Qwen2.5-32B-Instruct is one of Alibaba Cloud’s latest LLM releases.',
    type: 'chat',
    contextWindowTokens: 32_000,
    enabled: true,
    pricing: { currency: 'CNY', input: 1.26, output: 1.26 },
  },
  {
    id: 'baichuan/baichuan2-13b-chat',
    displayName: 'baichuan/baichuan2-13b-chat',
    description:
      'Baichuan-13B is an open-source, commercially usable 13B-parameter LLM from Baichuan, achieving best-in-class results for its size on authoritative Chinese and English benchmarks.',
    type: 'chat',
    contextWindowTokens: 14_336,
    enabled: true,
    pricing: { currency: 'CNY', input: 1.75, output: 1.75 },
  },
  {
    id: '01-ai/yi-1.5-34b-chat',
    displayName: '01-ai/yi-1.5-34b-chat',
    description:
      '01.AI’s latest open-source fine-tuned model with 34B parameters, supporting multiple dialogue scenarios, trained on high-quality data and aligned with human preferences.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 1.1, output: 1.1 },
  },
  {
    id: '01-ai/yi-1.5-9b-chat',
    displayName: '01-ai/yi-1.5-9b-chat',
    description:
      '01.AI’s latest open-source fine-tuned model with 9B parameters, supporting multiple dialogue scenarios, trained on high-quality data and aligned with human preferences.',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.4, output: 0.4 },
  },
  {
    id: 'thudm/glm-4-9b-chat',
    displayName: 'thudm/glm-4-9b-chat',
    description: 'The open-source release of Zhipu AI’s latest GLM-4 pretraining model.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.5, output: 0.5 },
  },
  {
    id: 'qwen/qwen-2-7b-instruct',
    displayName: 'qwen/qwen-2-7b-instruct',
    description: 'Qwen2 is the new Qwen LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    pricing: { currency: 'CNY', input: 0.32, output: 0.32 },
  },
];

export default ppioModels;
