import type { ChatModelCard } from '../types';

const qiniuModels: ChatModelCard[] = [
  {
    id: 'deepseek-r1',
    displayName: 'DeepSeek R1',
    description: 'DeepSeek R1 是 DeepSeek 推出的深度推理模型，在复杂问题求解方面表现卓越。',
    type: 'chat',
    contextWindowTokens: 65_536,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek-v3',
    displayName: 'DeepSeek V3',
    description: 'DeepSeek V3 是一款高性能通用语言模型，适合多种应用场景。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'deepseek-r1-distill-qwen-32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description: 'DeepSeek R1 Distill Qwen 32B 是经过蒸馏优化的推理模型。',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    displayName: 'DeepSeek R1 Distill Llama 70B',
    description: 'DeepSeek R1 Distill Llama 70B 是基于 Llama 架构的蒸馏推理模型。',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen2.5-72b-instruct',
    displayName: 'Qwen2.5 72B Instruct',
    description: 'Qwen2.5 72B Instruct 是通义千问的旗舰指令遵循模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'qwen2.5-32b-instruct',
    displayName: 'Qwen2.5 32B Instruct',
    description: 'Qwen2.5 32B Instruct 提供优秀的性价比。',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'llama-3.1-70b-instruct',
    displayName: 'Llama 3.1 70B Instruct',
    description: 'Llama 3.1 70B Instruct 是 Meta 的高性能开源模型。',
    type: 'chat',
    contextWindowTokens: 128_000,
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'minimax/minimax-m2.1',
    displayName: 'MiniMax M2.1',
    description:
      'MiniMax-M2.1 is a lightweight, cutting-edge large language model optimized for coding, proxy workflows, and modern application development, providing cleaner, more concise output and faster perceptual response times.',
    type: 'chat',
    contextWindowTokens: 204_800,
    maxOutput: 131_072,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
    releasedAt: '2025-12-24',
  },
  {
    id: 'minimax/minimax-m2',
    displayName: 'MiniMax M2',
    description: 'Built for efficient coding and agent workflows.',
    type: 'chat',
    contextWindowTokens: 204_800,
    maxOutput: 131_072,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
    releasedAt: '2025-10-27',
  },
  {
    id: 'deepseek/deepseek-math-v2',
    displayName: 'DeepSeek Math V2',
    description:
      'DeepSeek Math V2 is a model that has made significant breakthroughs in mathematical reasoning capabilities.',
    type: 'chat',
    contextWindowTokens: 163_840,
    maxOutput: 131_072,
    enabled: true,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
    releasedAt: '2025-11-27',
  },
  {
    id: 'meituan/longcat-flash-chat',
    displayName: 'LongCat Flash Chat',
    description:
      'An open-source non-thinking base model from Meituan optimized for dialogue and agent tasks, strong in tool use and complex multi-turn interactions.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-09-01',
  },
  {
    id: 'z-ai/glm-4.7',
    displayName: 'GLM-4.7',
    description:
      "GLM-4.7 is Zhipu's latest flagship model, offering improved general capabilities, simpler and more natural replies, and a more immersive writing experience.",
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 128_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 3.168, output: 12.528 },
    releasedAt: '2025-12-23',
  },
  {
    id: 'z-ai/glm-4.6',
    displayName: 'GLM-4.6',
    description:
      'The flagship model of Zhipu, GLM-4.6, surpasses its predecessor in all aspects of advanced coding, long text processing, reasoning, and intelligent agent capabilities.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 128_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 7.2, output: 12.6 },
    releasedAt: '2025-09-30',
  },
  {
    id: 'x-ai/grok-4-fast',
    displayName: 'Grok 4 Fast',
    description:
      'We’re excited to release Grok 4 Fast, our latest progress in cost-effective reasoning models.',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, vision: true },
    pricing: { currency: 'CNY', input: 7.2, output: 12.6 },
    releasedAt: '2025-09-09',
  },
  {
    id: 'x-ai/grok-code-fast-1',
    displayName: 'Grok Code Fast 1',
    description:
      'We’re excited to launch grok-code-fast-1, a fast and cost-effective reasoning model that excels at agentic coding.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.2, output: 1.5, cachedInput: 0.02 },
    releasedAt: '2025-08-27',
  },
];

export default qiniuModels;
