import type { ChatModelCard, ImageModelCard, VideoModelCard } from '../types';

const siliconChatModels: ChatModelCard[] = [
  {
    id: 'deepseek-ai/DeepSeek-V4-Pro',
    displayName: 'DeepSeek V4 Pro',
    description:
      'DeepSeek-V4-Pro 是 DeepSeek-V4 系列旗舰 MoE 模型，总参数 1.6T、激活 49B，原生支持 1M 上下文，采用 CSA 与 HCA 混合注意力架构，是当前最强的开源模型之一。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    enabled: true,
    organization: 'DeepSeek',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 3, output: 6, cachedInput: 0.025 },
    releasedAt: '2026-04-24',
  },
  {
    id: 'deepseek-ai/DeepSeek-V4-Flash',
    displayName: 'DeepSeek V4 Flash',
    description:
      'DeepSeek-V4-Flash 是 DeepSeek-V4 系列预览版 MoE 模型，总参数 284B、激活 13B，支持 1M 上下文，长上下文推理效率与整体性能出色。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    enabled: true,
    organization: 'DeepSeek',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 2, cachedInput: 0.02 },
    releasedAt: '2026-04-24',
  },
  {
    id: 'Qwen/Qwen3.6-27B',
    displayName: 'Qwen3.6 27B',
    description:
      'Qwen3.6-27B 是 Qwen3.6 系列首个开源中等规模稠密模型，在前端开发、仓库级推理、工具调用与复杂问题求解上显著提升。',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.6, output: 4.8 },
    releasedAt: '2026-04-23',
  },
  {
    id: 'Pro/moonshotai/Kimi-K2.6',
    displayName: 'Kimi-K2.6 (Pro)',
    description:
      'Kimi K2.6 是月之暗面开源原生多模态智能体模型，MoE 架构总参数 1T、激活 32B，支持 256K 上下文，在 HLE、SWE-Bench Pro、BrowseComp 等多项主流基准达到开源最先进水平。',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 6.5, output: 27, cachedInput: 1.1 },
    releasedAt: '2026-04-21',
  },
  {
    id: 'Pro/zai-org/glm-5.1',
    displayName: 'GLM-5.1 (Pro)',
    description:
      'GLM-5.1 是智谱新一代旗舰智能体模型，754B MoE 架构，支持原生工具调用、前缀补全与 FIM，提供 200K 上下文的长程工作流能力。',
    type: 'chat',
    contextWindowTokens: 198_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 6, output: 24, cachedInput: 1.3 },
    releasedAt: '2026-04-08',
  },
  {
    id: 'MiniMaxAI/MiniMax-M2.5',
    displayName: 'MiniMax-M2.5',
    description:
      'MiniMax-M2.5 通过数十万真实环境的大规模强化学习训练，MoE 架构总参数 2290 亿，在编程、智能体工具调用、搜索与办公场景表现行业领先。',
    type: 'chat',
    contextWindowTokens: 192_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4, cachedInput: 0.21 },
    releasedAt: '2026-02-13',
  },
  {
    id: 'stepfun-ai/Step-3.5-Flash',
    displayName: 'Step 3.5 Flash',
    description:
      'Step 3.5 Flash 是阶跃星辰最强开源基础模型，稀疏 MoE 架构总参数 196B、激活 11B，支持 256K 上下文，通过 MTP-3 实现 100-300 tok/s 生成吞吐，编程与智能体任务表现出色。',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2026-02-02',
  },
  {
    id: 'Qwen/Qwen2.5-72B-Instruct',
    displayName: 'Qwen2.5 72B Instruct',
    description: 'Qwen2.5 72B 是阿里云通义千问系列的大参数版本。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, structuredOutput: true },
    pricing: { currency: 'CNY', input: 4.13, output: 4.13 },
  },
  {
    id: 'Qwen/Qwen2.5-7B-Instruct',
    displayName: 'Qwen2.5 7B Instruct',
    description: 'Qwen2.5 7B 是高效的中型模型，性价比出色。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, structuredOutput: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'deepseek-ai/DeepSeek-V2.5',
    displayName: 'DeepSeek V2.5',
    description: 'DeepSeek V2.5 是 SiliconFlow 提供的 DeepSeek 模型。',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 8_192,
    enabled: true,
    abilities: { functionCall: true, structuredOutput: true },
    pricing: { currency: 'CNY', input: 1.33, output: 1.33 },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    displayName: 'Llama 3.1 70B',
    description: 'Meta Llama 3.1 70B 是开源大型语言模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.99, output: 0.99 },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    displayName: 'Llama 3.1 8B',
    description: 'Meta Llama 3.1 8B 是轻量级开源模型。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'Qwen/Qwen3.6-35B-A3B',
    displayName: 'Qwen3.6 35B A3B',
    description:
      'Qwen3.6-35B-A3B is a large language model from the Qwen team in the Qwen3.6 series, using a Mixture-of-Experts (MoE) architecture with 35B total parameters and 3B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.4, output: 3.2 },
    releasedAt: '2026-04-17',
  },
  {
    id: 'Qwen/Qwen3.5-397B-A17B',
    displayName: 'Qwen3.5 397B A17B',
    description:
      'Qwen3.5-397B-A17B is the latest vision-language model in the Qwen3.5 series, using a Mixture-of-Experts (MoE) architecture with 397B total parameters and 17B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 4.8 },
    releasedAt: '2026-02-16',
  },
  {
    id: 'Qwen/Qwen3.5-122B-A10B',
    displayName: 'Qwen3.5 122B A10B',
    description:
      'Qwen3.5-122B-A10B is a native multimodal large language model from the Qwen team with 122B total parameters and only 10B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 6.4 },
    releasedAt: '2026-02-26',
  },
  {
    id: 'Qwen/Qwen3.5-35B-A3B',
    displayName: 'Qwen3.5 35B A3B',
    description:
      'Qwen3.5-35B-A3B is a native multimodal large language model from the Qwen team with 35B total parameters and only 3B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.4, output: 3.2 },
    releasedAt: '2026-02-25',
  },
  {
    id: 'Qwen/Qwen3.5-27B',
    displayName: 'Qwen3.5 27B',
    description:
      'Qwen3.5-27B is a native multimodal large language model from the Qwen team with 27B parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.6, output: 4.8 },
    releasedAt: '2026-02-25',
  },
  {
    id: 'Qwen/Qwen3.5-9B',
    displayName: 'Qwen3.5 9B',
    description:
      'Qwen3.5-9B is a native multimodal large language model from the Qwen team with 9B parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 4 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'Qwen/Qwen3.5-4B',
    displayName: 'Qwen3.5 4B',
    description:
      'Qwen3.5-4B is a native multimodal large language model from the Qwen team with 4B parameters, the most lightweight Dense model in the Qwen3.5 series.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'Pro/MiniMaxAI/MiniMax-M2.5',
    displayName: 'MiniMax-M2.5 (Pro)',
    description:
      'MiniMax-M2.5 is the latest large language model developed by MiniMax, trained through large-scale reinforcement learning across hundreds of thousands of complex, real-world environments.',
    type: 'chat',
    contextWindowTokens: 192_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4, cachedInput: 0.21 },
    releasedAt: '2026-02-13',
  },
  {
    id: 'Pro/zai-org/glm-5',
    displayName: 'GLM-5 (Pro)',
    description:
      "GLM-5 is Zhipu's next-generation large language model, focusing on complex system engineering and long-duration Agent tasks.",
    type: 'chat',
    contextWindowTokens: 198_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 18, cachedInput: 1 },
    releasedAt: '2026-02-12',
  },
  {
    id: 'Pro/zai-org/GLM-5.1',
    displayName: 'GLM-5.1 (Pro)',
    description:
      'GLM-5.1 is a next-generation flagship model designed for agent engineering, using a Mixture of Experts (MoE) architecture with 754B parameters.',
    type: 'chat',
    contextWindowTokens: 198_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 6, output: 24, cachedInput: 1.3 },
    releasedAt: '2026-04-08',
  },
  {
    id: 'zai-org/GLM-4.6V',
    displayName: 'GLM-4.6V',
    description:
      'GLM-4.6V achieves state-of-the-art visual understanding accuracy at its parameter scale, and for the first time natively integrates Function Call capability into the visual model architecture, bridging the path from "visual perception" to "...',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 1, output: 3 },
    releasedAt: '2025-12-08',
  },
  {
    id: 'deepseek-ai/DeepSeek-V3.2',
    displayName: 'DeepSeek V3.2',
    description:
      'DeepSeek-V3.2 is a model that combines high computational efficiency with excellent reasoning and Agent performance.',
    type: 'chat',
    contextWindowTokens: 163_840,
    enabled: true,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 3 },
    releasedAt: '2025-12-01',
  },
  {
    id: 'Pro/deepseek-ai/DeepSeek-V3.2',
    displayName: 'DeepSeek V3.2 (Pro)',
    description:
      'DeepSeek-V3.2 is a model that combines high computational efficiency with excellent reasoning and Agent performance.',
    type: 'chat',
    contextWindowTokens: 163_840,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 3 },
    releasedAt: '2025-12-01',
  },
  {
    id: 'Pro/moonshotai/Kimi-K2.5',
    displayName: 'Kimi-K2.5 (Pro)',
    description:
      'Kimi K2.5 is an open-source native multimodal agent model, built on Kimi-K2-Base, trained on approximately 1.5 trillion mixed vision and text tokens.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 21 },
    releasedAt: '2026-01-27',
  },
  {
    id: 'qwen/qwen3.5-397b-a17b',
    displayName: 'Qwen3.5 397B A17B',
    description:
      'Qwen3.5-397B-A17B is the latest vision-language model in the Qwen series, featuring a Mixture of Experts (MoE) architecture with 397B total parameters and 17B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 4.8 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'qwen/qwen3.5-122b-a10b',
    displayName: 'Qwen3.5 122B A10B',
    description:
      'Qwen3.5-122B-A10B is a native multimodal large language model developed by the Qwen team, with 122B total parameters and only 10B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 6.4 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'qwen/qwen3.5-35b-a3b',
    displayName: 'Qwen3.5 35B A3B',
    description:
      'Qwen3.5-35B-A3B is a native multimodal large language model developed by the Qwen team, with 35B total parameters and only 3B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.4, output: 3.2 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'qwen/qwen3.5-27b',
    displayName: 'Qwen3.5 27B',
    description:
      'Qwen3.5-27B is a native multimodal large language model developed by the Qwen team with 27B parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.6, output: 4.8 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'qwen/qwen3.5-9b',
    displayName: 'Qwen3.5 9B',
    description:
      'Qwen3.5-9B is a native multimodal large language model developed by the Qwen team with 9B parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 4 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'qwen/qwen3.5-4b',
    displayName: 'Qwen3.5 4B',
    description:
      'Qwen3.5-4B is a native multimodal large language model developed by the Qwen team with 4B parameters, making it the lightest Dense model in the Qwen3.5 series.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2026-03-03',
  },
  {
    id: 'PaddlePaddle/PaddleOCR-VL-1.5',
    displayName: 'PaddleOCR-VL 1.5',
    description:
      'PaddleOCR-VL-1.5 is an upgraded version of the PaddleOCR-VL series, achieving 94.5% accuracy on the OmniDocBench v1.5 document parsing benchmark, surpassing leading general large models and specialized document parsing models.',
    type: 'chat',
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2026-01-29',
  },
  {
    id: 'Pro/zai-org/glm-4.7',
    displayName: 'GLM-4.7 (Pro)',
    description:
      "GLM-4.7 is Zhipu's new generation flagship model with 355B total parameters and 32B active parameters, fully upgraded in general dialogue, reasoning, and agent capabilities.",
    type: 'chat',
    contextWindowTokens: 200_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8, cachedInput: 0.4 },
    releasedAt: '2025-12-22',
  },
  {
    id: 'moonshotai/Kimi-K2-Thinking',
    displayName: 'Kimi K2 Thinking',
    description: 'Kimi K2 Thinking is the latest and most powerful open-source thinking model.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
    releasedAt: '2025-11-07',
  },
  {
    id: 'Pro/moonshotai/Kimi-K2-Thinking',
    displayName: 'Kimi K2 Thinking (Pro)',
    description:
      'Kimi K2 Thinking Turbo is the Turbo variant optimized for reasoning speed and throughput while retaining K2 Thinking’s multi-step reasoning and tool use.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 8, output: 32 },
    releasedAt: '2025-11-07',
  },
  {
    id: 'MiniMaxAI/MiniMax-M2',
    displayName: 'MiniMax-M2',
    description: 'MiniMax-M2 redefines agent efficiency.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.1, output: 8.4 },
    releasedAt: '2025-10-28',
  },
  {
    id: 'Qwen/Qwen3-VL-32B-Instruct',
    displayName: 'Qwen3 VL 32B Instruct',
    description:
      'Qwen3-VL-32B-Instruct is a vision-language model from the Qwen team with leading SOTA results on multiple VL benchmarks.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-10-21',
  },
  {
    id: 'Qwen/Qwen3-VL-32B-Thinking',
    displayName: 'Qwen3 VL 32B Thinking',
    description: 'Qwen3-VL-32B-Thinking is optimized for complex visual reasoning.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 1, output: 10 },
    releasedAt: '2025-10-21',
  },
  {
    id: 'deepseek-ai/DeepSeek-OCR',
    displayName: 'DeepSeek OCR',
    description:
      'DeepSeek-OCR is a vision-language model from DeepSeek AI focused on OCR and "context optical compression." It explores compressing context from images, efficiently processes documents, and converts them to structured text (e.g., Markdown).',
    type: 'chat',
    contextWindowTokens: 8_192,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-10-20',
  },
  {
    id: 'Qwen/Qwen3-Omni-30B-A3B-Instruct',
    displayName: 'Qwen3 Omni 30B A3B Instruct',
    description:
      'Qwen3-Omni-30B-A3B-Instruct is a Qwen3-series MoE model with 30B total and 3B active parameters, delivering strong performance at lower inference cost.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
    releasedAt: '2025-09-22',
  },
  {
    id: 'Qwen/Qwen3-Omni-30B-A3B-Thinking',
    displayName: 'Qwen3 Omni 30B A3B Thinking',
    description: 'Qwen3-Omni-30B-A3B-Thinking is the core "Thinker" component of Qwen3-Omni.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
    releasedAt: '2025-09-22',
  },
  {
    id: 'Qwen/Qwen3-Omni-30B-A3B-Captioner',
    displayName: 'Qwen3 Omni 30B A3B Captioner',
    description:
      'Qwen3-Omni-30B-A3B-Captioner is a Qwen3-series VLM built for high-quality, detailed, accurate image captions.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
    releasedAt: '2025-09-22',
  },
  {
    id: 'tencent/Hunyuan-MT-7B',
    displayName: 'Hunyuan MT 7B',
    description:
      'Hunyuan Translation Model includes Hunyuan-MT-7B and the ensemble Hunyuan-MT-Chimera.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-09-01',
  },
  {
    id: 'Kwaipilot/KAT-Dev',
    displayName: 'KAT-Dev 32B',
    description: 'KAT-Dev (32B) is an open-source 32B model for software engineering tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-09-27',
  },
  {
    id: 'zai-org/GLM-4.6',
    displayName: 'GLM-4.6',
    description:
      'Compared to GLM-4.5, GLM-4.6 expands context from 128K to 200K for more complex agent tasks.',
    type: 'chat',
    contextWindowTokens: 198_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 3.5, output: 14 },
    releasedAt: '2025-09-30',
  },
  {
    id: 'Qwen/Qwen3-VL-30B-A3B-Instruct',
    displayName: 'Qwen3 VL 30B A3B Instruct',
    description:
      'Qwen3-VL-30B-A3B-Instruct is the instruction-tuned Qwen3-VL model with strong vision-language understanding and generation.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
  },
  {
    id: 'Qwen/Qwen3-VL-30B-A3B-Thinking',
    displayName: 'Qwen3 VL 30B A3B Thinking',
    description:
      'Qwen3-VL-30B-A3B-Thinking is the reasoning-enhanced version of Qwen3-VL, optimized for multimodal reasoning, image-to-code, and complex visual understanding.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
  },
  {
    id: 'Qwen/Qwen3-VL-235B-A22B-Instruct',
    displayName: 'Qwen3 VL 235B A22B Instruct',
    description:
      'Qwen3-VL-235B-A22B-Instruct is a large instruction-tuned Qwen3-VL model built on MoE, delivering excellent multimodal understanding and generation.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 2.5, output: 10 },
  },
  {
    id: 'Qwen/Qwen3-VL-235B-A22B-Thinking',
    displayName: 'Qwen3 VL 235B A22B Thinking',
    description:
      'Qwen3-VL-235B-A22B-Thinking is the flagship thinking version of Qwen3-VL, optimized for complex multimodal reasoning, long-context reasoning, and agent interaction in enterprise scenarios.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 2.5, output: 10 },
  },
  {
    id: 'deepseek-ai/DeepSeek-V3.1-Terminus',
    displayName: 'DeepSeek V3.1 Terminus',
    description:
      'DeepSeek-V3.1-Terminus is an updated V3.1 model positioned as a hybrid agent LLM.',
    type: 'chat',
    contextWindowTokens: 163_840,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'Pro/deepseek-ai/DeepSeek-V3.1-Terminus',
    displayName: 'DeepSeek V3.1 Terminus (Pro)',
    description:
      'DeepSeek-V3.1-Terminus is an updated V3.1 model positioned as a hybrid agent LLM.',
    type: 'chat',
    contextWindowTokens: 163_840,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'Qwen/Qwen3-VL-8B-Instruct',
    displayName: 'Qwen3 VL 8B Instruct',
    description:
      'Qwen3-VL-8B-Instruct is a Qwen3 vision-language model built on Qwen3-8B-Instruct and trained on large image-text data.',
    type: 'chat',
    contextWindowTokens: 256_000,
    organization: 'Qwen',
    abilities: { functionCall: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
    releasedAt: '2025-10-15',
  },
  {
    id: 'Qwen/Qwen3-VL-8B-Thinking',
    displayName: 'Qwen3 VL 8B Thinking',
    description:
      'Qwen3-VL-8B-Thinking is the visual thinking version of Qwen3, optimized for complex multi-step reasoning.',
    type: 'chat',
    contextWindowTokens: 256_000,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 5 },
    releasedAt: '2025-10-15',
  },
  {
    id: 'inclusionAI/Ring-flash-2.0',
    displayName: 'Ring Flash 2.0',
    description:
      'Ring-flash-2.0 is a high-performance thinking model optimized from Ling-flash-2.0-base.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-09-19',
  },
  {
    id: 'inclusionAI/Ling-flash-2.0',
    displayName: 'Ling Flash 2.0',
    description:
      'Ling-flash-2.0 is the third Ling 2.0 architecture model from Ant Group’s Bailing team.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-09-17',
  },
  {
    id: 'inclusionAI/Ling-mini-2.0',
    displayName: 'Ling Mini 2.0',
    description:
      'Ling-mini-2.0 is a small, high-performance MoE LLM with 16B total parameters and only 1.4B active per token (789M non-embedding), delivering very fast generation.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
    releasedAt: '2025-09-09',
  },
  {
    id: 'ByteDance-Seed/Seed-OSS-36B-Instruct',
    displayName: 'Seed OSS 36B Instruct',
    description:
      'Seed-OSS is a family of open-source LLMs from ByteDance Seed, designed for strong long-context handling, reasoning, agent, and general abilities.',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1.5, output: 4 },
    releasedAt: '2025-08-20',
  },
  {
    id: 'stepfun-ai/step3',
    displayName: 'Step 3',
    description:
      'Step3 is a cutting-edge multimodal reasoning model from StepFun, built on an MoE architecture with 321B total and 38B active parameters.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 4, output: 10 },
    releasedAt: '2025-07-31',
  },
  {
    id: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    displayName: 'Qwen3 Coder 480B A35B Instruct',
    description: 'Qwen3-Coder-480B-A35B-Instruct is Alibaba’s most agentic code model to date.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 8, output: 16 },
    releasedAt: '2025-07-23',
  },
  {
    id: 'Qwen/Qwen3-Coder-30B-A3B-Instruct',
    displayName: 'Qwen3 Coder 30B A3B Instruct',
    description: 'Qwen3-Coder-30B-A3B-Instruct is a Qwen3 code model from the Qwen team.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
    releasedAt: '2025-07-31',
  },
  {
    id: 'zai-org/GLM-4.5V',
    displayName: 'GLM-4.5V',
    description:
      'GLM-4.5V is Zhipu AI’s latest VLM, built on the GLM-4.5-Air flagship text model (106B total, 12B active) with an MoE architecture for strong performance at lower cost.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 1, output: 6 },
    releasedAt: '2025-08-11',
  },
  {
    id: 'zai-org/GLM-4.5-Air',
    displayName: 'GLM-4.5-Air',
    description:
      'GLM-4.5-Air is a base model for agent applications using a Mixture-of-Experts architecture.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 6 },
    releasedAt: '2025-07-28',
  },
  {
    id: 'ascend-tribe/pangu-pro-moe',
    displayName: 'Pangu Pro MoE 72B A16B',
    description:
      'Pangu-Pro-MoE 72B-A16B is a sparse LLM with 72B total and 16B active parameters, based on a grouped MoE (MoGE) architecture.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-06-17',
  },
  {
    id: 'baidu/ERNIE-4.5-300B-A47B',
    displayName: 'ERNIE 4.5 300B A47B',
    description:
      'ERNIE-4.5-300B-A47B is a Baidu MoE LLM with 300B total parameters and 47B active per token, balancing strong performance and compute efficiency.',
    type: 'chat',
    contextWindowTokens: 131_072,
    pricing: { currency: 'CNY', input: 2, output: 8 },
    releasedAt: '2025-06-30',
  },
  {
    id: 'moonshotai/Kimi-K2-Instruct-0905',
    displayName: 'Kimi K2 0905',
    description: 'Kimi K2-Instruct-0905 is the newest and most powerful Kimi K2.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
    releasedAt: '2025-09-05',
  },
  {
    id: 'Pro/moonshotai/Kimi-K2-Instruct-0905',
    displayName: 'Kimi K2 0905 (Pro)',
    description: 'Kimi K2-Instruct-0905 is the newest and most powerful Kimi K2.',
    type: 'chat',
    contextWindowTokens: 262_144,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
    releasedAt: '2025-09-05',
  },
  {
    id: 'moonshotai/Kimi-Dev-72B',
    displayName: 'Kimi Dev 72B',
    description:
      'Kimi-Dev-72B is an open-source code LLM optimized with large-scale RL to produce robust, production-ready patches.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
    releasedAt: '2025-06-17',
  },
  {
    id: 'tencent/Hunyuan-A13B-Instruct',
    displayName: 'Hunyuan A13B Instruct',
    description:
      'Hunyuan-A13B-Instruct uses 80B total parameters with 13B active to match larger models.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-06-27',
  },
  {
    id: 'MiniMaxAI/MiniMax-M1-80k',
    displayName: 'MiniMax M1 80K',
    description:
      'MiniMax-M1 is an open-weights large-scale hybrid-attention reasoning model with 456B total parameters and ~45.9B active per token.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
    releasedAt: '2025-06-16',
  },
  {
    id: 'Tongyi-Zhiwen/QwenLong-L1-32B',
    displayName: 'QwenLong L1 32B',
    description:
      'QwenLong-L1-32B is the first long-context reasoning model (LRM) trained with RL, optimized for long-text reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-05-26',
  },
  {
    id: 'Qwen/Qwen3-235B-A22B-Thinking-2507',
    displayName: 'Qwen3 235B A22B Thinking 2507',
    description:
      'Qwen3-235B-A22B-Thinking-2507 is a Qwen3 model focused on hard complex reasoning.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2.5, output: 10 },
    releasedAt: '2025-07-25',
  },
  {
    id: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
    displayName: 'Qwen3 235B A22B Instruct 2507',
    description:
      'Qwen3-235B-A22B-Instruct-2507 is a flagship Qwen3 MoE model with 235B total and 22B active parameters.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2.5, output: 10 },
    releasedAt: '2025-07-21',
  },
  {
    id: 'Qwen/Qwen3-30B-A3B-Thinking-2507',
    displayName: 'Qwen3 30B A3B Thinking 2507',
    description: 'Qwen3-30B-A3B-Thinking-2507 is the latest thinking model in the Qwen3 series.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
    releasedAt: '2025-07-30',
  },
  {
    id: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
    displayName: 'Qwen3 30B A3B Instruct 2507',
    description:
      'Qwen3-30B-A3B-Instruct-2507 is the updated non-thinking version of Qwen3-30B-A3B.',
    type: 'chat',
    contextWindowTokens: 262_144,
    organization: 'Qwen',
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.7, output: 2.8 },
    releasedAt: '2025-07-29',
  },
  {
    id: 'Qwen/Qwen3-32B',
    displayName: 'Qwen3 32B',
    description:
      'Qwen3 is a next-gen Tongyi Qwen model with major gains in reasoning, general ability, agent capability, and multilingual performance, and supports switching thinking modes.',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-04-28',
  },
  {
    id: 'Qwen/Qwen3-14B',
    displayName: 'Qwen3 14B',
    description:
      'Qwen3 is a next-gen Tongyi Qwen model with major gains in reasoning, general ability, agent capability, and multilingual performance, and supports switching thinking modes.',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
    releasedAt: '2025-04-28',
  },
  {
    id: 'Qwen/Qwen3-8B',
    displayName: 'Qwen3 8B (Free)',
    description:
      'Qwen3 is a next-gen Tongyi Qwen model with major gains in reasoning, general ability, agent capability, and multilingual performance, and supports switching thinking modes.',
    type: 'chat',
    contextWindowTokens: 131_072,
    organization: 'Qwen',
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-04-28',
  },
  {
    id: 'THUDM/GLM-4.1V-9B-Thinking',
    displayName: 'GLM-4.1V 9B Thinking (Free)',
    description:
      'GLM-4.1V-9B-Thinking is an open-source VLM from Zhipu AI and Tsinghua KEG Lab, designed for complex multimodal cognition.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-07-02',
  },
  {
    id: 'Pro/THUDM/GLM-4.1V-9B-Thinking',
    displayName: 'GLM-4.1V 9B Thinking (Pro)',
    description:
      'GLM-4.1V-9B-Thinking is an open-source VLM from Zhipu AI and Tsinghua KEG Lab, designed for complex multimodal cognition.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.25, output: 1 },
    releasedAt: '2025-07-02',
  },
  {
    id: 'THUDM/GLM-Z1-32B-0414',
    displayName: 'GLM-Z1 32B 0414',
    description:
      'GLM-Z1-32B-0414 is a deep-thinking reasoning model built from GLM-4-32B-0414 with cold-start data and expanded RL, further trained on math, code, and logic.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'THUDM/GLM-Z1-9B-0414',
    displayName: 'GLM-Z1 9B 0414 (Free)',
    description:
      'GLM-Z1-9B-0414 is a small 9B-parameter GLM model that retains open-source strengths while delivering impressive capability.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'THUDM/GLM-4-32B-0414',
    displayName: 'GLM-4 32B 0414',
    description:
      'GLM-4-32B-0414 is a next-gen open GLM model with 32B parameters, comparable to OpenAI GPT and DeepSeek V3/R1 series in performance.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1.89, output: 1.89 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'THUDM/GLM-4-9B-0414',
    displayName: 'GLM-4 9B 0414 (Free)',
    description:
      'GLM-4-9B-0414 is a 9B GLM model that inherits GLM-4-32B techniques while offering a lighter deployment.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
    releasedAt: '2025-04-14',
  },
  {
    id: 'deepseek-ai/DeepSeek-R1-0528-Qwen3-8B',
    displayName: 'DeepSeek R1 0528 Qwen3 8B (Free)',
    description:
      'DeepSeek-R1-0528-Qwen3-8B distills chain-of-thought from DeepSeek-R1-0528 into Qwen3 8B Base.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1',
    displayName: 'DeepSeek R1',
    description:
      'DeepSeek-R1 is an RL-driven reasoning model that reduces repetition and improves readability.',
    type: 'chat',
    contextWindowTokens: 98_304,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek-ai/DeepSeek-V3',
    displayName: 'DeepSeek V3',
    description:
      'DeepSeek-V3 is a 671B-parameter MoE model using MLA and DeepSeekMoE with loss-free load balancing for efficient inference and training.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'Pro/deepseek-ai/DeepSeek-R1',
    displayName: 'DeepSeek R1 (Pro)',
    description:
      'DeepSeek-R1 is an RL-driven reasoning model that reduces repetition and improves readability.',
    type: 'chat',
    contextWindowTokens: 98_304,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'Pro/deepseek-ai/DeepSeek-V3',
    displayName: 'DeepSeek V3 (Pro)',
    description:
      'DeepSeek-V3 is a 671B-parameter MoE model using MLA and DeepSeekMoE with loss-free load balancing for efficient inference and training.',
    type: 'chat',
    contextWindowTokens: 65_536,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description:
      'DeepSeek-R1-Distill-Qwen-32B is distilled from Qwen2.5-32B and fine-tuned on 800K curated DeepSeek-R1 samples.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1.26, output: 1.26 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',
    displayName: 'DeepSeek R1 Distill Qwen 14B',
    description:
      'DeepSeek-R1-Distill-Qwen-14B is distilled from Qwen2.5-14B and fine-tuned on 800K curated DeepSeek-R1 samples.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.7, output: 0.7 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
    displayName: 'DeepSeek R1 Distill Qwen 7B (Free)',
    description:
      'DeepSeek-R1-Distill-Qwen-7B is distilled from Qwen2.5-Math-7B and fine-tuned on 800K curated DeepSeek-R1 samples.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'Pro/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
    displayName: 'DeepSeek R1 Distill Qwen 7B (Pro)',
    description:
      'DeepSeek-R1-Distill-Qwen-7B is distilled from Qwen2.5-Math-7B and fine-tuned on 800K curated DeepSeek-R1 samples.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.35, output: 0.35 },
  },
  {
    id: 'Qwen/QVQ-72B-Preview',
    displayName: 'QVQ 72B Preview',
    description:
      'QVQ-72B-Preview is a research model from Qwen focused on visual reasoning, with strengths in complex scene understanding and visual math problems.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 9.9, output: 9.9 },
  },
  {
    id: 'Qwen/QwQ-32B',
    displayName: 'QwQ 32B',
    description: 'QwQ is a reasoning model in the Qwen family.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'Pro/Qwen/Qwen2.5-7B-Instruct',
    displayName: 'Qwen2.5 7B Instruct (Pro)',
    description: 'Qwen2.5-7B-Instruct is part of Alibaba Cloud’s latest LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.35, output: 0.35 },
  },
  {
    id: 'Qwen/Qwen2.5-14B-Instruct',
    displayName: 'Qwen2.5 14B Instruct',
    description: 'Qwen2.5-14B-Instruct is part of Alibaba Cloud’s latest LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.7, output: 0.7 },
  },
  {
    id: 'Qwen/Qwen2.5-32B-Instruct',
    displayName: 'Qwen2.5 32B Instruct',
    description: 'Qwen2.5-32B-Instruct is part of Alibaba Cloud’s latest LLM series.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 1.26, output: 1.26 },
  },
  {
    id: 'Qwen/Qwen2.5-72B-Instruct-128K',
    displayName: 'Qwen2.5 72B Instruct 128K',
    description: 'Qwen2.5-72B-Instruct is part of Alibaba Cloud’s latest LLM series.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4.13, output: 4.13 },
  },
  {
    id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    displayName: 'Qwen2.5 Coder 32B Instruct',
    description: 'Qwen2.5-Coder-32B-Instruct is a code-focused model built on Qwen2.5.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 1.26, output: 1.26 },
  },
  {
    id: 'Qwen/Qwen2-VL-72B-Instruct',
    displayName: 'Qwen2 VL 72B Instruct',
    description:
      'Qwen2-VL is the latest Qwen-VL model, reaching SOTA on vision benchmarks like MathVista, DocVQA, RealWorldQA, and MTVQA.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 4.13, output: 4.13 },
  },
  {
    id: 'Qwen/Qwen2.5-VL-32B-Instruct',
    displayName: 'Qwen2.5 VL 32B Instruct',
    description: 'Qwen2.5-VL-32B-Instruct is a multimodal model from the Qwen team.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 1.89, output: 1.89 },
  },
  {
    id: 'Qwen/Qwen2.5-VL-72B-Instruct',
    displayName: 'Qwen2.5 VL 72B Instruct',
    description:
      'Qwen2.5-VL is the vision-language model in the Qwen2.5 series with major upgrades: stronger visual understanding for objects, text, charts, and layouts; reasoning as a visual agent with dynamic tool use; understanding videos over 1 hour and...',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 4.13, output: 4.13 },
  },
  {
    id: 'internlm/internlm2_5-7b-chat',
    displayName: 'InternLM2.5 7B Chat (Free)',
    description:
      'InternLM2.5-7B-Chat is an open-source chat model based on the InternLM2 architecture.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
];

const siliconImageModels: ImageModelCard[] = [
  {
    id: 'Kwai-Kolors/Kolors',
    displayName: 'Kolors',
    description:
      'Kolors is a large-scale latent-diffusion text-to-image model by the Kuaishou Kolors team.',
    type: 'image',
    releasedAt: '2024-07-06',
  },
  {
    id: 'Qwen/Qwen-Image',
    displayName: 'Qwen-Image',
    description:
      'Qwen-Image is a 20B-parameter image generation foundation model from the Qwen team.',
    type: 'image',
    releasedAt: '2025-08-04',
  },
  {
    id: 'Qwen/Qwen-Image-Edit-2509',
    displayName: 'Qwen-Image-Edit (2509)',
    description:
      'Qwen-Image-Edit-2509 is the latest editing version of Qwen-Image from the Qwen team.',
    type: 'image',
    releasedAt: '2025-09-22',
  },
];

const siliconVideoModels: VideoModelCard[] = [
  {
    id: 'Wan-AI/Wan2.2-I2V-A14B',
    displayName: 'Wan-AI/Wan2.2-I2V-A14B',
    description:
      'Wan2.2-I2V-A14B is one of the first open-source image-to-video (I2V) generation models released by Wan-AI, an AI initiative under Alibaba, to adopt a Mixture of Experts (MoE) architecture.',
    type: 'video',
    enabled: true,
    releasedAt: '2026-01-28',
  },
  {
    id: 'Wan-AI/Wan2.2-T2V-A14B',
    displayName: 'Wan-AI/Wan2.2-T2V-A14B',
    description:
      'Wan2.2-T2V-A14B is the first open-source video generation model released by Alibaba to adopt a Mixture of Experts (MoE) architecture.',
    type: 'video',
    enabled: true,
    releasedAt: '2026-01-28',
  },
];

export default {
  chat: siliconChatModels,
  image: siliconImageModels,
  video: siliconVideoModels,
};
