import type { ChatModelCard } from '../types';

const taichuModels: ChatModelCard[] = [
  {
    id: 'taichu_llm',
    displayName: 'Taichu LLM',
    description: '紫东太初大模型是中科院自动化研究所推出的多模态大模型，支持全面的问答和创作任务。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'taichu_vl',
    displayName: 'Taichu VL',
    description: 'Taichu VL 是紫东太初的多模态视觉语言模型，支持图像理解和分析。',
    type: 'chat',
    contextWindowTokens: 4_096,
    abilities: { vision: true },
  },
  {
    id: 'taichu2.0',
    displayName: 'Taichu 2.0',
    description: 'Taichu 2.0 是新一代紫东太初大模型，具有更强的认知和创作能力。',
    type: 'chat',
    contextWindowTokens: 8_192,
  },
  {
    id: 'taichu_o1',
    displayName: 'Taichu-O1',
    description:
      'taichu_o1 is a next-generation reasoning large model that achieves human-like chain-of-thought through multimodal interaction and reinforcement learning.',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'taichu4_vl_2b_nothinking',
    displayName: 'Taichu4.0-VL-2B-NoThinking',
    description:
      'The No-Thinking version of the Taichu4.0-VL 2B model features lower memory usage, a lightweight design, fast response speed, and strong multimodal understanding capabilities.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.2, output: 2 },
  },
  {
    id: 'taichu4_vl_3b',
    displayName: 'Taichu4.0-VL-3B-Thinking',
    description:
      'The Thinking version of the Taichu4.0-VL 3B model efficiently performs multimodal understanding and reasoning tasks, with comprehensive upgrades in visual comprehension, visual localization, OCR recognition, and related capabilities.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.3, output: 3 },
  },
  {
    id: 'taichu4_vl_32b_nothinking',
    displayName: 'Taichu4.0-VL-32B-NoThinking',
    description:
      'The No-Thinking version of the Taichu4.0-VL 32B model is designed for complex image-and-text understanding and visual knowledge QA scenarios, excelling in image captioning, visual question answering, video comprehension, and visual localiza...',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 7 },
  },
  {
    id: 'taichu4_vl_32b',
    displayName: 'Taichu4.0-VL-32B-Thinking',
    description:
      'The Thinking version of the Taichu4.0-VL 32B model is suited for complex multimodal understanding and reasoning tasks, demonstrating outstanding performance in multimodal mathematical reasoning, multimodal agent capabilities, and general im...',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.7, output: 7 },
  },
  {
    id: 'taichu_llm_2b',
    displayName: 'Taichu-LLM-2B',
    description:
      'The Zidong Taichu large language model is a high-performance text-generation model developed using fully domestic full-stack technologies.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 0.3, output: 0.9 },
  },
  {
    id: 'taichu_llm_14b',
    displayName: 'Taichu-LLM-14B',
    description:
      'The Zidong Taichu large language model is a high-performance text-generation model developed using fully domestic full-stack technologies.',
    type: 'chat',
    contextWindowTokens: 32_768,
    pricing: { currency: 'CNY', input: 1, output: 3 },
  },
  {
    id: 'deepseek_r1',
    displayName: 'DeepSeek R1',
    description:
      'DeepSeek-R1 is a reinforcement-learning-driven reasoning model that addresses repetition and readability issues.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
  },
  {
    id: 'deepseek_r1_distill_qwen_14b',
    displayName: 'DeepSeek R1 Distill Qwen 14B',
    description:
      'DeepSeek-R1-Distill-Qwen-14B is distilled from Qwen2.5-14B and fine-tuned on 800K curated samples generated by DeepSeek-R1, delivering strong reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
  },
  {
    id: 'deepseek_r1_distill_qwen_32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description:
      'DeepSeek-R1-Distill-Qwen-32B is distilled from Qwen2.5-32B and fine-tuned on 800K curated samples generated by DeepSeek-R1, excelling in math, coding, and reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
  },
  {
    id: 'deepseek_r1_distill_llama_70b',
    displayName: 'DeepSeek R1 Distill Llama 70B',
    description: 'DeepSeek-R1-Distill-Llama-70B is distilled from Llama-3.3-70B-Instruct.',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { reasoning: true },
  },
  {
    id: 'qwq_32b',
    displayName: 'QwQ 32B',
    description: 'Mid-sized reasoning model in the Qwen family.',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { reasoning: true },
  },
];

export default taichuModels;
