import type { ChatModelCard, ImageModelCard, VideoModelCard } from '../types';

const volcengineChatModels: ChatModelCard[] = [
  {
    id: 'deepseek-v4-pro',
    displayName: 'DeepSeek V4 Pro',
    description:
      'DeepSeek-V4-Pro 是火山方舟上的 DeepSeek 旗舰 MoE 模型，支持思考与非思考两种模式，面向高级推理、代码生成与复杂智能体工作流。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 393_216,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 12, output: 24, cachedInput: 1 },
    releasedAt: '2026-04-24',
  },
  {
    id: 'deepseek-v4-flash',
    displayName: 'DeepSeek V4 Flash',
    description:
      'DeepSeek-V4-Flash 是火山方舟上的 DeepSeek 高效 1M 上下文模型，在保持强推理与智能体能力的同时兼顾速度与成本。',
    type: 'chat',
    contextWindowTokens: 1_048_576,
    maxOutput: 393_216,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 1, output: 2, cachedInput: 0.2 },
    releasedAt: '2026-04-24',
  },
  {
    id: 'doubao-seed-code',
    displayName: 'Doubao Seed Code',
    description:
      'Doubao-Seed-Code 面向 Agentic 编程任务进行了深度优化，支持多模态（文字/图片/视频）与 256k 长上下文，兼容 Anthropic API。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 32_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 1.2, output: 8, cachedInput: 0.24 },
  },
  {
    id: 'deepseek-v3.1',
    displayName: 'DeepSeek V3.1',
    description:
      'DeepSeek-V3.1 是深度求索全新推出的混合推理模型，支持思考与非思考2种推理模式，较 DeepSeek-R1-0528 思考效率更高。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 12, cachedInput: 0.8 },
  },
  {
    id: 'kimi-k2',
    displayName: 'Kimi K2',
    description:
      'Kimi-K2 是 Moonshot AI 推出的具备超强代码和 Agent 能力的 MoE 架构基础模型，总参数 1T，激活参数 32B。',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 16, cachedInput: 0.8 },
  },
  {
    id: 'deepseek-r1',
    displayName: 'DeepSeek R1',
    description:
      'DeepSeek-R1 在后训练阶段大规模使用了强化学习技术，在数学、代码、自然语言推理等任务上性能比肩 OpenAI o1。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek-r1-distill-qwen-32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description: 'DeepSeek-R1-Distill 模型是通过微调训练得到的，使用 DeepSeek-R1 生成的样本数据。',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1.5, output: 6 },
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    displayName: 'DeepSeek R1 Distill Qwen 7B',
    description: 'DeepSeek-R1-Distill 7B 版本。',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.6, output: 2.4 },
  },
  {
    id: 'deepseek-v3',
    displayName: 'DeepSeek V3',
    description:
      'DeepSeek-V3 是深度求索公司自研的 MoE 模型，多项评测成绩超越 Qwen2.5-72B 和 Llama-3.1-405B。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'doubao-seed-1.6-vision',
    displayName: 'Doubao Seed 1.6 Vision',
    description:
      'Doubao-Seed-1.6-vision 视觉深度思考模型，在教育、图像审核、巡检与安防和 AI 搜索问答等场景下展现出更强的通用多模态理解和推理能力。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 32_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 8, cachedInput: 0.16 },
  },
  {
    id: 'doubao-seed-1.6',
    displayName: 'Doubao Seed 1.6',
    description: '豆包全新多模态深度思考模型，同时支持 auto/thinking/non-thinking 三种思考模式。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 32_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 2, cachedInput: 0.16 },
  },
  {
    id: 'doubao-seed-1.6-thinking',
    displayName: 'Doubao Seed 1.6 Thinking',
    description: '豆包深度思考模型，在 Coding、Math、逻辑推理上大幅提升。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 32_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 8, cachedInput: 0.16 },
  },
  {
    id: 'doubao-seed-1.6-lite',
    displayName: 'Doubao Seed 1.6 Lite',
    description: 'Doubao-Seed-1.6-lite 全新多模态深度思考模型，支持思考程度可调节，更强性价比。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 32_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.3, output: 0.6, cachedInput: 0.06 },
  },
  {
    id: 'doubao-seed-1.6-flash',
    displayName: 'Doubao Seed 1.6 Flash',
    description: '豆包极速多模态思考模型，TPOT 仅需 10ms。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 32_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 0.15, output: 1.5, cachedInput: 0.03 },
  },
  {
    id: 'doubao-1.5-ui-tars',
    displayName: 'Doubao 1.5 UI TARS',
    description:
      'Doubao-1.5-UI-TARS 是一款原生面向图形界面交互（GUI）的 Agent 模型，通过感知、推理和行动等类人的能力与 GUI 进行无缝交互。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 3.5, output: 12 },
  },
  {
    id: 'doubao-1.5-thinking-vision-pro',
    displayName: 'Doubao 1.5 Thinking Vision Pro',
    description:
      '全新视觉深度思考模型，具备更强的通用多模态理解和推理能力，在 59 个公开评测基准中的 37 个上取得 SOTA 表现。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9 },
  },
  {
    id: 'doubao-1.5-thinking-pro',
    displayName: 'Doubao 1.5 Thinking Pro',
    description: '豆包深度思考模型，在数学、编程、科学推理等领域表现突出。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'doubao-1.5-thinking-pro-m',
    displayName: 'Doubao 1.5 Thinking Pro M',
    description: 'Doubao-1.5 深度思考模型 M 版本，自带原生多模态深度推理能力。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_000,
    abilities: { functionCall: true, reasoning: true, vision: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'doubao-1.5-pro-32k',
    displayName: 'Doubao 1.5 Pro 32k',
    description: '豆包全新主力模型，在知识、代码、推理等方面表现卓越。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'doubao-1.5-pro-256k',
    displayName: 'Doubao 1.5 Pro 256k',
    description: 'Doubao-1.5-pro-256k 基于 Doubao-1.5-Pro 全面升级版，整体效果大幅提升 10%。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 12_288,
    pricing: { currency: 'CNY', input: 5, output: 9 },
  },
  {
    id: 'doubao-1.5-lite-32k',
    displayName: 'Doubao 1.5 Lite 32k',
    description: '豆包轻量版模型，极致响应速度，效果与时延均达一流水平。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 12_288,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'doubao-1.5-vision-pro-32k',
    displayName: 'Doubao 1.5 Vision Pro 32k',
    description: '豆包多模态大模型，支持任意分辨率图像识别。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 12_288,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9 },
    releasedAt: '2025-01-15',
  },
  {
    id: 'doubao-1.5-vision-pro',
    displayName: 'Doubao 1.5 Vision Pro',
    description: '豆包全新升级的多模态大模型，支持 128k 上下文，增强视觉推理和文档识别能力。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9 },
    releasedAt: '2025-03-28',
  },
  {
    id: 'doubao-1.5-vision-lite',
    displayName: 'Doubao 1.5 Vision Lite',
    description: '豆包轻量版多模态大模型，支持 128k 上下文。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 16_384,
    abilities: { functionCall: true, vision: true },
    pricing: { currency: 'CNY', input: 1.5, output: 4.5 },
    releasedAt: '2025-03-15',
  },
  {
    id: 'doubao-vision-pro-32k',
    displayName: 'Doubao Vision Pro 32k',
    description: '豆包多模态大模型，具备强大的图片理解与推理能力。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9 },
    releasedAt: '2024-10-28',
  },
  {
    id: 'doubao-vision-lite-32k',
    displayName: 'Doubao Vision Lite 32k',
    description: '豆包轻量版多模态大模型。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 1.5, output: 4.5 },
    releasedAt: '2024-10-15',
  },
  {
    id: 'doubao-pro-32k',
    displayName: 'Doubao Pro 32k',
    description: '豆包效果最好的主力模型，适合处理复杂任务。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'doubao-pro-256k',
    displayName: 'Doubao Pro 256k',
    description: '豆包主力模型 256k 上下文版本。',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 5, output: 9 },
  },
  {
    id: 'doubao-lite-4k',
    displayName: 'Doubao Lite 4k',
    description: '豆包轻量模型 4k 版本，极致响应速度。',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'doubao-lite-32k',
    displayName: 'Doubao Lite 32k',
    description: '豆包轻量模型，极致响应速度，高性价比。',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'doubao-lite-128k',
    displayName: 'Doubao Lite 128k',
    description: '豆包轻量模型 128k 上下文版本。',
    type: 'chat',
    contextWindowTokens: 128_000,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.8, output: 1 },
  },
  {
    id: 'doubao-seed-2.0-pro',
    displayName: 'Doubao Seed 2.0 Pro',
    description:
      "Doubao-Seed-2.0-pro is ByteDance's flagship Agent general model, with all-around leaps in complex task planning and execution capabilities.",
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 128_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 3.2, output: 16, cachedInput: 0.64 },
    releasedAt: '2026-02-15',
  },
  {
    id: 'doubao-seed-2.0-lite',
    displayName: 'Doubao Seed 2.0 Lite',
    description:
      'Doubao-Seed-2.0-lite is a new multimodal deep-reasoning model that delivers better value and a strong choice for common tasks, with a context window up to 256k.',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 128_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.6, output: 3.6, cachedInput: 0.12 },
    releasedAt: '2026-02-15',
  },
  {
    id: 'doubao-seed-2.0-mini',
    displayName: 'Doubao Seed 2.0 Mini',
    description:
      'Doubao-Seed-2.0-mini is a lightweight model with fast response and high performance, suitable for small tasks and high-concurrency scenarios.',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 128_000,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.2, output: 2, cachedInput: 0.04 },
    releasedAt: '2026-02-15',
  },
  {
    id: 'doubao-seed-2.0-code',
    displayName: 'Doubao Seed 2.0 Code',
    description:
      'Doubao-Seed-2.0-code is deeply optimized for agentic coding, supports multimodal inputs and a 256k context window, fitting coding, vision understanding, and agent workflows.',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 128_000,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 3.2, output: 16, cachedInput: 0.64 },
    releasedAt: '2026-02-15',
  },
  {
    id: 'doubao-seed-1.8',
    displayName: 'Doubao Seed 1.8',
    description:
      'Doubao-Seed-1.8 has stronger multimodal understanding and Agent capabilities, supports text/image/video input and context caching, and can deliver excellent performance in complex tasks.',
    type: 'chat',
    contextWindowTokens: 256_000,
    maxOutput: 64_000,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 2, cachedInput: 0.16 },
    releasedAt: '2025-12-18',
  },
  {
    id: 'glm-4-7',
    displayName: 'GLM-4.7',
    description: 'GLM-4.7 is the latest flagship model from Zhipu AI.',
    type: 'chat',
    contextWindowTokens: 200_000,
    maxOutput: 128_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8, cachedInput: 0.4 },
  },
  {
    id: 'deepseek-v3.2',
    displayName: 'DeepSeek V3.2',
    description:
      'DeepSeek-V3.2 is the first hybrid reasoning model from DeepSeek that integrates thinking into tool usage.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 3, cachedInput: 0.4 },
  },
  {
    id: 'kimi-k2-thinking',
    displayName: 'Kimi K2 Thinking',
    description:
      'Kimi-K2 is a MoE architecture basic model launched by Moonshot AI with super strong code and agent capabilities.',
    type: 'chat',
    contextWindowTokens: 262_144,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16, cachedInput: 0.8 },
  },
];

const volcengineImageModels: ImageModelCard[] = [
  {
    id: 'doubao-seedream-4-0-250828',
    displayName: 'Seedream 4.0',
    description:
      'Seedream 4.0 图片生成模型由字节跳动 Seed 团队研发，支持文字与图片输入，提供高可控、高质量的图片生成体验。',
    type: 'image',
    enabled: true,
    resolutions: [
      '2048x2048',
      '2304x1728',
      '1728x2304',
      '2560x1440',
      '1440x2560',
      '2496x1664',
      '1664x2496',
      '3024x1296',
    ],
    releasedAt: '2025-09-09',
  },
  {
    id: 'doubao-seedream-3-0-t2i-250415',
    displayName: 'Seedream 3.0 文生图',
    description:
      'Seedream 3.0 图片生成模型由字节跳动 Seed 团队研发，支持文字与图片输入，提供高可控、高质量的图片生成体验。',
    type: 'image',
    enabled: true,
    resolutions: [
      '1024x1024',
      '864x1152',
      '1152x864',
      '1280x720',
      '720x1280',
      '832x1248',
      '1248x832',
      '1512x648',
    ],
    releasedAt: '2025-04-15',
  },
  {
    id: 'doubao-seededit-3-0-i2i-250628',
    displayName: 'SeedEdit 3.0 图生图',
    description: '支持通过文本指令编辑图像，生成图像的边长在 512～1536 之间。',
    type: 'image',
    enabled: true,
    releasedAt: '2025-06-28',
  },
  {
    id: 'doubao-seedream-5-0-260128',
    displayName: 'Seedream 5.0 Lite',
    description: 'Doubao-Seedream-5.0-lite is ByteDance’s latest image-generation model.',
    type: 'image',
    enabled: true,
    releasedAt: '2026-01-28',
  },
  {
    id: 'doubao-seedream-4-5-251128',
    displayName: 'Seedream 4.5',
    description:
      'Seedream 4.5 is ByteDance’s latest multimodal image model, integrating text-to-image, image-to-image, and batch image generation capabilities, while incorporating commonsense and reasoning abilities.',
    type: 'image',
    enabled: true,
    releasedAt: '2025-11-28',
  },
];

const volcengineVideoModels: VideoModelCard[] = [
  {
    id: 'doubao-seedance-2-0-260128',
    displayName: 'Seedance 2.0',
    description:
      'Seedance 2.0 by ByteDance is the most powerful video generation model, supporting multimodal reference video generation, video editing, video extension, text-to-video, and image-to-video with synchronized audio.',
    type: 'video',
    enabled: true,
    organization: 'ByteDance',
    releasedAt: '2026-01-28',
  },
  {
    id: 'doubao-seedance-2-0-fast-260128',
    displayName: 'Seedance 2.0 Fast',
    description:
      'Seedance 2.0 Fast by ByteDance offers the same capabilities as Seedance 2.0 with faster generation speeds at a more competitive price.',
    type: 'video',
    enabled: true,
    organization: 'ByteDance',
    releasedAt: '2026-01-28',
  },
  {
    id: 'doubao-seedance-1-5-pro-251215',
    displayName: 'Seedance 1.5 Pro',
    description:
      'Seedance 1.5 Pro by ByteDance supports text-to-video, image-to-video (first frame, first+last frame), and audio generation synchronized with visuals.',
    type: 'video',
    enabled: true,
    organization: 'ByteDance',
    releasedAt: '2025-12-15',
  },
  {
    id: 'doubao-seedance-1-0-pro-fast-251015',
    displayName: 'Seedance 1.0 Pro Fast',
    description:
      'Seedance 1.0 Pro Fast is a comprehensive model designed to minimize cost while maximizing performance, achieving an excellent balance between video generation quality, speed, and price.',
    type: 'video',
    organization: 'ByteDance',
    releasedAt: '2025-10-15',
  },
  {
    id: 'doubao-seedance-1-0-pro-250528',
    displayName: 'Seedance 1.0 Pro',
    description:
      'Seedance 1.0 Pro is a video generation foundation model that supports multi-shot storytelling.',
    type: 'video',
    organization: 'ByteDance',
    releasedAt: '2025-05-28',
  },
  {
    id: 'doubao-seedance-1-0-lite-i2v-250428',
    displayName: 'Seedance 1.0 Lite I2V',
    description:
      'Stable generation quality with high cost-effectiveness, capable of generating videos from a first frame, first-and-last frames, or reference images.',
    type: 'video',
    organization: 'ByteDance',
    releasedAt: '2025-04-28',
  },
  {
    id: 'doubao-seedance-1-0-lite-t2v-250428',
    displayName: 'Seedance 1.0 Lite T2V',
    description:
      'Stable generation quality with high cost-effectiveness, capable of generating videos based on text instructions.',
    type: 'video',
    organization: 'ByteDance',
    releasedAt: '2025-04-28',
  },
];

export default {
  chat: volcengineChatModels,
  image: volcengineImageModels,
  video: volcengineVideoModels,
};
