import type { ChatModelCard, ImageModelCard, VideoModelCard } from '../types';

const wenxinChatModels: ChatModelCard[] = [
  {
    id: 'ernie-5.1',
    displayName: 'ERNIE 5.1',
    description:
      '文心 5.1 是文心系列最新模型，基础能力全面升级，在智能体、知识处理、推理与深度搜索等方面显著提升，并通过大规模智能体后训练增强复杂任务的稳定性。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 4, output: 18 },
    releasedAt: '2026-05-09',
  },
  {
    id: 'ernie-5.0-thinking-latest',
    displayName: 'ERNIE 5.0 Thinking',
    description: '文心5.0原生全模态旗舰模型，支持文本、图像、音频、视频统一建模。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, vision: true },
    pricing: { currency: 'CNY', input: 6, output: 24 },
    releasedAt: '2025-11-12',
  },
  {
    id: 'ernie-4.5-turbo-128k',
    displayName: 'ERNIE 4.5 Turbo 128K',
    description: '文心高性能通用模型，支持搜索增强与工具调用。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 12_288,
    enabled: true,
    abilities: { functionCall: true, search: true },
    pricing: { currency: 'CNY', input: 0.8, output: 3.2, cachedInput: 0.2 },
  },
  {
    id: 'ernie-speed-128k',
    displayName: 'ERNIE Speed 128K',
    description: '文心免费大模型，适合长文本理解与大规模试用场景。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'ernie-speed-8k',
    displayName: 'ERNIE Speed 8K',
    description: '文心免费快速模型，适合日常对话和轻量文本任务。',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'ernie-lite-8k',
    displayName: 'ERNIE Lite 8K',
    description: '文心轻量级通用模型，适合成本敏感的日常问答。',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    pricing: { currency: 'CNY', input: 0, output: 0 },
  },
  {
    id: 'ernie-x1.1-preview',
    displayName: 'ERNIE X1.1 Preview',
    description: '文心X1.1深度思考模型预览版，适合能力验证与测试。',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'ernie-4.5-turbo-vl',
    displayName: 'ERNIE 4.5 Turbo VL',
    description: '文心成熟多模态模型，适合图文理解与识别任务。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9, cachedInput: 0.75 },
  },
  {
    id: 'deepseek-v3.2-think',
    displayName: 'DeepSeek V3.2 Think',
    description: '百度托管的DeepSeek V3.2满血版深度思考模型。',
    type: 'chat',
    contextWindowTokens: 144_000,
    maxOutput: 32_768,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 2, output: 3 },
  },
  {
    id: 'ernie-5.0',
    displayName: 'ERNIE 5.0',
    description:
      'ERNIE 5.0, the new-generation model in the ERNIE series, is a natively multimodal large model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 6, output: 24 },
    releasedAt: '2026-03-05',
  },
  {
    id: 'ernie-5.0-thinking-preview',
    displayName: 'ERNIE 5.0 Thinking Preview',
    description:
      'Wenxin 5.0 Thinking Preview is a native full-modal flagship model with unified text, image, audio, and video modeling.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    abilities: { functionCall: true, reasoning: true, search: true, video: true, vision: true },
    pricing: { currency: 'CNY', input: 6, output: 24 },
    releasedAt: '2025-11-12',
  },
  {
    id: 'ernie-4.5-turbo-128k-preview',
    displayName: 'ERNIE 4.5 Turbo 128K Preview',
    description:
      'ERNIE 4.5 Turbo 128K preview with release-level capabilities, suitable for integration and canary testing.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 12_288,
    abilities: { functionCall: true, search: true },
    pricing: { currency: 'CNY', input: 0.8, output: 3.2, cachedInput: 0.2 },
  },
  {
    id: 'ernie-4.5-turbo-32k',
    displayName: 'ERNIE 4.5 Turbo 32K',
    description:
      'ERNIE 4.5 Turbo 32K is a mid-length context version for QA, knowledge base retrieval, and multi-turn dialogue.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 12_288,
    abilities: { functionCall: true, search: true },
    pricing: { currency: 'CNY', input: 0.8, output: 3.2, cachedInput: 0.2 },
  },
  {
    id: 'ernie-4.5-turbo-latest',
    displayName: 'ERNIE 4.5 Turbo Latest',
    description:
      'Latest ERNIE 4.5 Turbo with optimized overall performance, ideal as the primary production model.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 12_288,
    abilities: { functionCall: true, search: true },
    pricing: { currency: 'CNY', input: 0.8, output: 3.2, cachedInput: 0.2 },
  },
  {
    id: 'ernie-speed-pro-128k',
    displayName: 'ERNIE Speed Pro 128K',
    description:
      'ERNIE Speed Pro 128K is a high-concurrency, high-value model for large-scale online services and enterprise apps.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'ernie-lite-pro-128k',
    displayName: 'ERNIE Lite Pro 128K',
    description:
      'ERNIE Lite Pro 128K is a lightweight high-performance model for latency- and cost-sensitive scenarios.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 0.2, output: 0.4 },
  },
  {
    id: 'ernie-char-8k',
    displayName: 'ERNIE Character 8K',
    description:
      'ERNIE Character 8K is a persona dialogue model for IP character building and long-term companionship chat.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'ernie-char-fiction-8k',
    displayName: 'ERNIE Character Fiction 8K',
    description:
      'ERNIE Character Fiction 8K is a persona model for novels and plot creation, suited for long-form story generation.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'ernie-char-fiction-8k-preview',
    displayName: 'ERNIE Character Fiction 8K Preview',
    description:
      'ERNIE Character Fiction 8K Preview is a character and plot creation model preview for feature evaluation and testing.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    pricing: { currency: 'CNY', input: 0.3, output: 0.6 },
  },
  {
    id: 'ernie-novel-8k',
    displayName: 'ERNIE Novel 8K',
    description:
      'ERNIE Novel 8K is built for long-form novels and IP plots with multi-character narratives.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    pricing: { currency: 'CNY', input: 40, output: 120 },
  },
  {
    id: 'ernie-4.5-0.3b',
    displayName: 'ERNIE 4.5 0.3B',
    description:
      'ERNIE 4.5 0.3B is an open-source lightweight model for local and customized deployment.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.1, output: 0.4 },
  },
  {
    id: 'ernie-4.5-21b-a3b',
    displayName: 'ERNIE 4.5 21B A3B',
    description:
      'ERNIE 4.5 21B A3B is an open-source large-parameter model with stronger understanding and generation.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { search: true },
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
  },
  {
    id: 'ernie-4.5-21b-a3b-thinking',
    displayName: 'ERNIE 4.5 21B A3B Thinking',
    description:
      'ERNIE-4.5-21B-A3B-Thinking is a text MoE (Mixture-of-Experts) post-trained model with a total of 21B parameters and 3B active parameters, offering significantly enhanced reasoning quality and depth.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
  },
  {
    id: 'ernie-4.5-vl-28b-a3b',
    displayName: 'ERNIE 4.5 VL 28B A3B',
    description:
      'ERNIE 4.5 VL 28B A3B is an open-source multimodal model for image-text understanding and reasoning.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'qianfan-8b',
    displayName: 'Qianfan 8B',
    description:
      'Qianfan 8B is a mid-size general model balancing cost and quality for text generation and QA.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 16_384,
    pricing: { currency: 'CNY', input: 0.5, output: 1 },
  },
  {
    id: 'qianfan-70b',
    displayName: 'Qianfan 70B',
    description:
      'Qianfan 70B is a large Chinese model for high-quality generation and complex reasoning.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 16_384,
    pricing: { currency: 'CNY', input: 0.8, output: 3.2 },
  },
  {
    id: 'qianfan-agent-intent-32k',
    displayName: 'Qianfan Agent Intent 32K',
    description:
      'Qianfan Agent Intent 32K targets intent recognition and agent orchestration with long context support.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    pricing: { currency: 'CNY', input: 0.4, output: 1.2 },
  },
  {
    id: 'qianfan-agent-lite-8k',
    displayName: 'Qianfan Agent Lite 8K',
    description:
      'Qianfan Agent Lite 8K is a lightweight agent model for low-cost multi-turn dialogue and workflows.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
  },
  {
    id: 'ernie-4.5-turbo-vl-preview',
    displayName: 'ERNIE 4.5 Turbo VL Preview',
    description:
      'ERNIE 4.5 Turbo VL Preview is a multimodal preview model for image-text understanding and generation, suitable for visual QA and content comprehension.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9, cachedInput: 0.75 },
  },
  {
    id: 'ernie-4.5-turbo-vl-32k',
    displayName: 'ERNIE 4.5 Turbo VL 32K',
    description:
      'ERNIE 4.5 Turbo VL 32K is a mid-long multimodal version for combined long-doc and image understanding.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 12_288,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9, cachedInput: 0.75 },
  },
  {
    id: 'ernie-4.5-turbo-vl-32k-preview',
    displayName: 'ERNIE 4.5 Turbo VL 32K Preview',
    description:
      'ERNIE 4.5 Turbo VL 32K Preview is a 32K multimodal preview for evaluating long-context vision ability.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 16_384,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9, cachedInput: 0.75 },
  },
  {
    id: 'ernie-4.5-turbo-vl-latest',
    displayName: 'ERNIE 4.5 Turbo VL Latest',
    description:
      'ERNIE 4.5 Turbo VL Latest is the newest multimodal version with improved image-text understanding and reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 16_384,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 3, output: 9, cachedInput: 0.75 },
  },
  {
    id: 'ernie-4.5-8k-preview',
    displayName: 'ERNIE 4.5 8K Preview',
    description: 'ERNIE 4.5 8K Preview is an 8K context preview model for evaluating ERNIE 4.5.',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 2_048,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'ernie-x1.1',
    displayName: 'ERNIE X1.1',
    description: 'ERNIE X1.1 is a thinking-model preview for evaluation and testing.',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 65_536,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'ernie-x1-turbo-32k',
    displayName: 'ERNIE X1 Turbo 32K',
    description:
      'ERNIE X1 Turbo 32K is a fast thinking model with 32K context for complex reasoning and multi-turn chat.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 28_160,
    abilities: { reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'ernie-x1-turbo-32k-preview',
    displayName: 'ERNIE X1 Turbo 32K Preview',
    description:
      'ERNIE X1 Turbo 32K Preview is a fast thinking model with 32K context for complex reasoning and multi-turn chat.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 28_160,
    abilities: { reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'qianfan-composition',
    displayName: 'Qianfan Composition',
    description:
      'Qianfan Composition is a multimodal creation model for mixed image-text understanding and generation.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2.5, output: 7.5 },
  },
  {
    id: 'qianfan-check-vl',
    displayName: 'Qianfan Check VL',
    description:
      'Qianfan Check VL is a multimodal content review model for image-text compliance and recognition tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 131_072,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 1.25, output: 3.75 },
  },
  {
    id: 'qianfan-multipicocr',
    displayName: 'Qianfan MultiPicOCR',
    description:
      'Qianfan MultiPicOCR is a multi-image OCR model for text detection and recognition across images.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2.5, output: 7.5 },
  },
  {
    id: 'qianfan-vl-70b',
    displayName: 'Qianfan VL 70B',
    description: 'Qianfan VL 70B is a large VLM for complex image-text understanding.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 28_672,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 8, output: 24 },
  },
  {
    id: 'qianfan-vl-8b',
    displayName: 'Qianfan VL 8B',
    description: 'Qianfan VL 8B is a lightweight VLM for daily image-text QA and analysis.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 28_672,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'qianfan-llama-vl-8b',
    displayName: 'Qianfan Llama VL 8B',
    description:
      'Qianfan Llama VL 8B is a Llama-based multimodal model for general image-text understanding.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 16_384,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 5 },
  },
  {
    id: 'qianfan-qi-vl',
    displayName: 'Qianfan QI VL',
    description:
      'Qianfan QI VL is a multimodal QA model for accurate retrieval and QA in complex image-text scenarios.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 131_072,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 1.5, output: 4.5 },
  },
  {
    id: 'qianfan-engcard-vl',
    displayName: 'Qianfan EngCard VL',
    description:
      'Qianfan EngCard VL is a multimodal recognition model focused on English scenarios.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_000,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 2 },
  },
  {
    id: 'qianfan-singlepicocr',
    displayName: 'Qianfan SinglePicOCR',
    description:
      'Qianfan SinglePicOCR is a single-image OCR model with high-accuracy character recognition.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.8, output: 8 },
  },
  {
    id: 'internvl3-38b',
    displayName: 'InternVL3 38B',
    description:
      'InternVL3 38B is a large open-source multimodal model for high-accuracy image-text understanding.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 8, output: 24 },
  },
  {
    id: 'internvl3-14b',
    displayName: 'InternVL3 14B',
    description: 'InternVL3 14B is a mid-size multimodal model balancing performance and cost.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'internvl3-1b',
    displayName: 'InternVL3 1B',
    description:
      'InternVL3 1B is a lightweight multimodal model for resource-constrained deployment.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.4, output: 1.2 },
  },
  {
    id: 'internvl2.5-38b-mpo',
    displayName: 'InternVL2.5 38B MPO',
    description:
      'InternVL2.5 38B MPO is a multimodal pretrained model for complex image-text reasoning.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 4_096,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 8, output: 24 },
  },
  {
    id: 'qwen3-vl-32b-instruct',
    displayName: 'Qwen3 VL 32B Instruct',
    description:
      'Qwen3 VL 32B Instruct is a multimodal instruction-tuned model for high-quality image-text QA and creation.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen3-vl-32b-thinking',
    displayName: 'Qwen3 VL 32B Thinking',
    description:
      'Qwen3 VL 32B Thinking is a deep-thinking multimodal version for complex reasoning and long-chain analysis.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 20 },
  },
  {
    id: 'qwen3-vl-8b-instruct',
    displayName: 'Qwen3 VL 8B Instruct',
    description:
      'Qwen3 VL 8B Instruct is a lightweight multimodal model for daily visual QA and app integration.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
  },
  {
    id: 'qwen3-vl-8b-thinking',
    displayName: 'Qwen3 VL 8B Thinking',
    description:
      'Qwen3 VL 8B Thinking is a multimodal chain-of-thought model for detailed visual reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 5 },
  },
  {
    id: 'qwen3-vl-30b-a3b-instruct',
    displayName: 'Qwen3 VL 30B A3B Instruct',
    description:
      'Qwen3 VL 30B A3B Instruct is a large multimodal model balancing accuracy and reasoning performance.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.75, output: 3 },
  },
  {
    id: 'qwen3-vl-30b-a3b-thinking',
    displayName: 'Qwen3 VL 30B A3B Thinking',
    description:
      'Qwen3 VL 30B A3B Thinking is a deep-thinking version for complex multimodal tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.75, output: 7.5 },
  },
  {
    id: 'qwen3-vl-235b-a22b-instruct',
    displayName: 'Qwen3 VL 235B A22B Instruct',
    description:
      'Qwen3 VL 235B A22B Instruct is a flagship multimodal model for demanding understanding and creation.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen3-vl-235b-a22b-thinking',
    displayName: 'Qwen3 VL 235B A22B Thinking',
    description:
      'Qwen3 VL 235B A22B Thinking is the flagship thinking version for complex multimodal reasoning and planning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 20 },
  },
  {
    id: 'qwen2.5-vl-32b-instruct',
    displayName: 'Qwen2.5 VL 32B Instruct',
    description:
      'Qwen2.5 VL 32B Instruct is an open-source multimodal model suitable for private deployment and multi-scenario use.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 8, output: 24 },
  },
  {
    id: 'qwen2.5-vl-7b-instruct',
    displayName: 'Qwen2.5 VL 7B Instruct',
    description:
      'Qwen2.5 VL 7B Instruct is a lightweight multimodal model balancing deployment cost and recognition ability.',
    type: 'chat',
    contextWindowTokens: 16_384,
    maxOutput: 4_096,
    abilities: { video: true, vision: true },
    pricing: { currency: 'CNY', input: 2, output: 5 },
  },
  {
    id: 'glm-4.5v',
    displayName: 'GLM-4.5V',
    description:
      'GLM-4.5V is a multimodal vision-language model for general image understanding and QA.',
    type: 'chat',
    contextWindowTokens: 65_536,
    maxOutput: 16_384,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'deepseek-vl2',
    displayName: 'DeepSeek VL2',
    description:
      'DeepSeek VL2 is a multimodal model for image-text understanding and fine-grained visual QA.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 2_048,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.99, output: 0.99 },
  },
  {
    id: 'deepseek-vl2-small',
    displayName: 'DeepSeek VL2 Small',
    description:
      'DeepSeek VL2 Small is a lightweight multimodal version for resource-constrained and high-concurrency use.',
    type: 'chat',
    contextWindowTokens: 4_096,
    maxOutput: 2_048,
    abilities: { vision: true },
    pricing: { currency: 'CNY', input: 0.5, output: 0.5 },
  },
  {
    id: 'deepseek-v3.1-think-250821',
    displayName: 'DeepSeek V3.1 Think 250821',
    description:
      'DeepSeek V3.1 Think 250821 is the deep-thinking model corresponding to the Terminus version, built for high-performance reasoning.',
    type: 'chat',
    contextWindowTokens: 144_000,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 4, output: 12 },
  },
  {
    id: 'deepseek-r1-250528',
    displayName: 'DeepSeek R1 250528',
    description:
      'DeepSeek R1 250528 is the full DeepSeek-R1 reasoning model for hard math and logic tasks.',
    type: 'chat',
    contextWindowTokens: 144_000,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek-r1',
    displayName: 'DeepSeek R1 250120',
    description:
      'DeepSeek R1 (current 250120) is a deep reasoning model with open chain-of-thought output.',
    type: 'chat',
    contextWindowTokens: 144_000,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'deepseek-r1-distill-qianfan-70b',
    displayName: 'DeepSeek R1 Distill Qianfan 70B',
    description:
      'DeepSeek R1 Distill Qianfan 70B is an R1 distill based on Qianfan-70B with strong value.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'deepseek-r1-distill-qianfan-8b',
    displayName: 'DeepSeek R1 Distill Qianfan 8B',
    description:
      'DeepSeek R1 Distill Qianfan 8B is an R1 distill based on Qianfan-8B for small and mid-sized apps.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'deepseek-r1-distill-qianfan-llama-70b',
    displayName: 'DeepSeek R1 Distill Qianfan Llama 70B',
    description: 'DeepSeek R1 Distill Qianfan Llama 70B is an R1 distill based on Llama-70B.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    displayName: 'DeepSeek R1 Distill Llama 70B',
    description: 'DeepSeek R1 Distill Llama 70B combines R1 reasoning with the Llama ecosystem.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'deepseek-r1-distill-qwen-32b',
    displayName: 'DeepSeek R1 Distill Qwen 32B',
    description:
      'DeepSeek R1 Distill Qwen 32B is an R1 distill based on Qwen-32B, balancing performance and cost.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1.5, output: 6 },
  },
  {
    id: 'deepseek-r1-distill-qwen-14b',
    displayName: 'DeepSeek R1 Distill Qwen 14B',
    description:
      'DeepSeek R1 Distill Qwen 14B is a mid-size distill model for multi-scenario deployment.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.6, output: 2.4 },
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    displayName: 'DeepSeek R1 Distill Qwen 7B',
    description:
      'DeepSeek R1 Distill Qwen 7B is a lightweight distill model for edge and private enterprise environments.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
  },
  {
    id: 'deepseek-r1-distill-qwen-1.5b',
    displayName: 'DeepSeek R1 Distill Qwen 1.5B',
    description:
      'DeepSeek R1 Distill Qwen 1.5B is an ultra-light distill model for very low-resource environments.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
  },
  {
    id: 'qwen3-next-80b-a3b-thinking',
    displayName: 'Qwen3 Next 80B A3B Thinking',
    description:
      'Qwen3 Next 80B A3B Thinking is a flagship reasoning model version for complex tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 1, output: 10 },
  },
  {
    id: 'qwen3-235b-a22b-thinking-2507',
    displayName: 'Qwen3 235B A22B Thinking 2507',
    description:
      'Qwen3 235B A22B Thinking 2507 is an ultra-large thinking model for hard reasoning.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 20 },
  },
  {
    id: 'qwen3-30b-a3b-thinking-2507',
    displayName: 'Qwen3 30B A3B Thinking 2507',
    description:
      'Qwen3 30B A3B Thinking 2507 is a mid-large thinking model balancing accuracy and cost.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 0.75, output: 7.5 },
  },
  {
    id: 'qwq-32b',
    displayName: 'QWQ 32B',
    description:
      'QWQ-32B is a large open-source reasoning model, suitable as a reasoning core for agents.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    abilities: { functionCall: true, reasoning: true },
    pricing: { currency: 'CNY', input: 2, output: 6 },
  },
  {
    id: 'kimi-k2-instruct',
    displayName: 'Kimi K2 Instruct',
    description:
      'Kimi K2 Instruct is Kimi’s official reasoning model with long context for code, QA, and more.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 4, output: 16 },
  },
  {
    id: 'qwen3-coder-480b-a35b-instruct',
    displayName: 'Qwen3 Coder 480B A35B Instruct',
    description:
      'Qwen3 Coder 480B A35B Instruct is a flagship code model for multilingual programming and complex code understanding.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 65_536,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 6, output: 24 },
  },
  {
    id: 'qwen3-235b-a22b-instruct-2507',
    displayName: 'Qwen3 235B A22B Instruct 2507',
    description:
      'Qwen3 235B A22B Instruct 2507 is a flagship instruct model for a wide range of generation and reasoning tasks.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true },
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen3-30b-a3b-instruct-2507',
    displayName: 'Qwen3 30B A3B Instruct 2507',
    description:
      'Qwen3 30B A3B Instruct 2507 is a mid-large instruct model for high-quality generation and QA.',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 32_768,
    abilities: { functionCall: true, search: true },
    pricing: { currency: 'CNY', input: 0.75, output: 3 },
  },
  {
    id: 'qwen3-30b-a3b',
    displayName: 'Qwen3 30B A3B',
    description: 'Qwen3 30B A3B is a mid-large general model balancing cost and quality.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.75, output: 3 },
  },
  {
    id: 'qwen3-32b',
    displayName: 'Qwen3 32B',
    description: 'Qwen3 32B is suited for general tasks requiring stronger understanding.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 2, output: 8 },
  },
  {
    id: 'qwen3-14b',
    displayName: 'Qwen3 14B',
    description: 'Qwen3 14B is a mid-size model for multilingual QA and text generation.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 1, output: 4 },
  },
  {
    id: 'qwen3-8b',
    displayName: 'Qwen3 8B',
    description:
      'Qwen3 8B is a lightweight model with flexible deployment for high-concurrency workloads.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.5, output: 2 },
  },
  {
    id: 'qwen3-4b',
    displayName: 'Qwen3 4B',
    description: 'Qwen3 4B is suitable for small-to-mid apps and local inference.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.3, output: 1.2 },
  },
  {
    id: 'qwen3-1.7b',
    displayName: 'Qwen3 1.7B',
    description: 'Qwen3 1.7B is an ultra-light model for edge and device deployment.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.3, output: 1.2 },
  },
  {
    id: 'qwen3-0.6b',
    displayName: 'Qwen3 0.6B',
    description:
      'Qwen3 0.6B is an entry-level model for simple reasoning and very constrained environments.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.3, output: 1.2 },
  },
  {
    id: 'qwen2.5-7b-instruct',
    displayName: 'Qwen2.5 7B Instruct',
    description:
      'Qwen2.5 7B Instruct is a mature open-source instruct model for multi-scenario chat and generation.',
    type: 'chat',
    contextWindowTokens: 32_768,
    maxOutput: 8_192,
    pricing: { currency: 'CNY', input: 0.5, output: 1 },
  },
];

const wenxinImageModels: ImageModelCard[] = [
  {
    id: 'musesteamer-air-image',
    displayName: 'MuseSteamer Air Image',
    description:
      'musesteamer-air-image is an image-generation model developed by Baidu’s search team to deliver exceptional cost-performance.',
    type: 'image',
    enabled: true,
  },
  {
    id: 'ernie-image-turbo',
    displayName: 'ERNIE Image Turbo',
    description: 'ERNIE-Image is an 8B-parameter text-to-image model developed by Baidu.',
    type: 'image',
    enabled: true,
  },
  {
    id: 'irag-1.0',
    displayName: 'ERNIE iRAG',
    description:
      'ERNIE iRAG is an image retrieval-augmented generation model for image search, image-text retrieval, and content generation.',
    type: 'image',
    releasedAt: '2025-02-05',
  },
  {
    id: 'ernie-irag-edit',
    displayName: 'ERNIE iRAG Edit',
    description:
      'ERNIE iRAG Edit is an image editing model supporting erasing, repainting, and variant generation.',
    type: 'image',
    releasedAt: '2025-04-17',
  },
  {
    id: 'qwen-image',
    displayName: 'Qwen Image',
    description:
      'Qwen-Image is a general image generation model supporting multiple art styles and strong complex text rendering, especially Chinese and English.',
    type: 'image',
    enabled: true,
  },
  {
    id: 'qwen-image-edit',
    displayName: 'Qwen Image Edit',
    description:
      'Qwen Image Edit is an image-to-image model that edits images based on input images and text prompts, enabling precise adjustments and creative transformations.',
    type: 'image',
    enabled: true,
  },
  {
    id: 'flux.1-schnell',
    displayName: 'FLUX.1-schnell',
    description:
      'FLUX.1-schnell is a high-performance image generation model for fast multi-style outputs.',
    type: 'image',
    enabled: true,
    releasedAt: '2025-03-27',
  },
];

const wenxinVideoModels: VideoModelCard[] = [
  {
    id: 'musesteamer-2.0-turbo-i2v-audio',
    displayName: 'MuseSteamer 2.0 Turbo I2V Audio',
    description: 'Supports 5s and 10s 720P dynamic video generation with sound.',
    type: 'video',
    enabled: true,
  },
  {
    id: 'musesteamer-2.0-turbo-i2v',
    displayName: 'MuseSteamer 2.0 Turbo I2V',
    description:
      'Supports 5-second 720P silent dynamic video generation, featuring cinematic-quality visuals, complex camera movements, and realistic character emotions and actions.',
    type: 'video',
    enabled: true,
  },
  {
    id: 'musesteamer-2.0-pro-i2v',
    displayName: 'MuseSteamer 2.0 Pro I2V',
    description:
      'Based on Turbo, supports 1080P dynamic video generation, offering higher visual quality and enhanced video expressiveness.',
    type: 'video',
    enabled: true,
  },
  {
    id: 'musesteamer-2.0-lite-i2v',
    displayName: 'MuseSteamer 2.0 Lite I2V',
    description:
      'Compared to Turbo, it offers superior performance with excellent cost-effectiveness.',
    type: 'video',
    enabled: true,
  },
  {
    id: 'musesteamer-air-i2v',
    displayName: 'MuseSteamer Air I2V',
    description:
      'The Baidu MuseSteamer Air video generation model performs well in subject consistency, physical realism, camera movement effects, and generation speed.',
    type: 'video',
  },
];

export default {
  chat: wenxinChatModels,
  image: wenxinImageModels,
  video: wenxinVideoModels,
};
