import type { ChatModelCard, ImageModelCard, VideoModelCard } from '../types';

const xaiChatModels: ChatModelCard[] = [
  {
    id: 'grok-4.3',
    displayName: 'Grok 4.3',
    description:
      'xAI 最新旗舰模型，支持 100 万上下文窗口，具备视觉理解、函数调用与结构化输出能力。',
    type: 'chat',
    contextWindowTokens: 1_000_000,
    enabled: true,
    abilities: { functionCall: true, search: true, structuredOutput: true, vision: true },
    pricing: { input: 1.25, output: 2.5, cachedInput: 0.2 },
    releasedAt: '2026-05-01',
  },
  {
    id: 'grok-4.20-0309-reasoning',
    displayName: 'Grok 4.20',
    description:
      'xAI 最新旗舰推理模型，支持 200 万上下文窗口，具备视觉理解、函数调用和结构化输出能力。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, structuredOutput: true, vision: true },
    pricing: { input: 2, output: 6, cachedInput: 0.2 },
    releasedAt: '2026-03-09',
  },
  {
    id: 'grok-4.20-0309-non-reasoning',
    displayName: 'Grok 4.20 (Non-Reasoning)',
    description:
      'xAI 最新旗舰非推理模型，支持 200 万上下文窗口，具备视觉理解、函数调用和结构化输出能力。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    enabled: true,
    abilities: { functionCall: true, structuredOutput: true, vision: true },
    pricing: { input: 2, output: 6, cachedInput: 0.2 },
    releasedAt: '2026-03-09',
  },
  {
    id: 'grok-4.20-multi-agent-0309',
    displayName: 'Grok 4.20 Multi-Agent',
    description: 'xAI 多智能体协作模型，专为多代理工作流优化，支持函数调用和结构化输出。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    enabled: true,
    abilities: { functionCall: true, structuredOutput: true },
    pricing: { input: 2, output: 6, cachedInput: 0.2 },
    releasedAt: '2026-03-09',
  },
  {
    id: 'grok-4-1-fast-non-reasoning',
    displayName: 'Grok 4.1 Fast (Non-Reasoning)',
    description: '前沿多模态模型，专门针对高性能代理工具调用进行优化。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    enabled: true,
    abilities: { functionCall: true, search: true, structuredOutput: true, vision: true },
    pricing: { input: 0.2, output: 0.5, cachedInput: 0.05 },
    releasedAt: '2025-11-20',
  },
  {
    id: 'grok-4-1-fast-reasoning',
    displayName: 'Grok 4.1 Fast',
    description: '前沿多模态模型，专门针对高性能代理工具调用进行优化，支持推理。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    enabled: true,
    abilities: {
      functionCall: true,
      reasoning: true,
      search: true,
      structuredOutput: true,
      vision: true,
    },
    pricing: { input: 0.2, output: 0.5, cachedInput: 0.05 },
    releasedAt: '2025-11-20',
  },
  {
    id: 'grok-4',
    displayName: 'Grok 4 0709',
    description:
      '我们最新最强大的旗舰模型，在自然语言处理、数学计算和推理方面表现卓越 - 是一款完美的全能型选手。',
    type: 'chat',
    contextWindowTokens: 256_000,
    enabled: true,
    abilities: { functionCall: true, reasoning: true, search: true, vision: true },
    pricing: { input: 3, output: 15, cachedInput: 0.75 },
    releasedAt: '2025-07-09',
  },
  {
    id: 'grok-4-fast-non-reasoning',
    displayName: 'Grok 4 Fast (Non-Reasoning)',
    description: '我们很高兴发布 Grok 4 Fast，这是我们在成本效益推理模型方面的最新进展。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    abilities: { functionCall: true, search: true, vision: true },
    pricing: { input: 0.4, output: 1, cachedInput: 0.05 },
    releasedAt: '2025-09-09',
  },
  {
    id: 'grok-4-fast-reasoning',
    displayName: 'Grok 4 Fast',
    description: '我们很高兴发布 Grok 4 Fast，这是我们在成本效益推理模型方面的最新进展。',
    type: 'chat',
    contextWindowTokens: 2_000_000,
    abilities: { functionCall: true, reasoning: true, search: true, vision: true },
    pricing: { input: 0.4, output: 1, cachedInput: 0.05 },
    releasedAt: '2025-09-09',
  },
  {
    id: 'grok-code-fast-1',
    displayName: 'Grok Code Fast 1',
    description:
      '我们很高兴推出 grok-code-fast-1，这是一款快速且经济高效的推理模型，在代理编码方面表现出色。',
    type: 'chat',
    contextWindowTokens: 256_000,
    abilities: { functionCall: true, reasoning: true },
    pricing: { input: 0.2, output: 1.5, cachedInput: 0.02 },
    releasedAt: '2025-08-27',
  },
  {
    id: 'grok-3',
    displayName: 'Grok 3',
    description:
      '旗舰级模型，擅长数据提取、编程和文本摘要等企业级应用，拥有金融、医疗、法律和科学等领域的深厚知识。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, search: true },
    pricing: { input: 3, output: 15, cachedInput: 0.75 },
    releasedAt: '2025-04-03',
  },
  {
    id: 'grok-3-fast',
    displayName: 'Grok 3 Fast',
    description: '旗舰级模型的快速版本，在保持核心能力的同时提供更低延迟和成本。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, search: true },
    pricing: { input: 0.6, output: 3, cachedInput: 0.15 },
    releasedAt: '2025-04-03',
  },
  {
    id: 'grok-3-mini',
    displayName: 'Grok 3 Mini',
    description:
      '轻量级模型，回话前会先思考。运行快速、智能，适用于不需要深层领域知识的逻辑任务，并能获取原始的思维轨迹。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { input: 0.3, output: 0.5, cachedInput: 0.075 },
    releasedAt: '2025-04-03',
  },
  {
    id: 'grok-3-mini-fast',
    displayName: 'Grok 3 Mini Fast',
    description: '轻量级思考模型的快速版本，适用于高吞吐量场景，兼具速度与推理能力。',
    type: 'chat',
    contextWindowTokens: 131_072,
    abilities: { functionCall: true, reasoning: true, search: true },
    pricing: { input: 0.06, output: 0.1, cachedInput: 0.015 },
    releasedAt: '2025-04-03',
  },
  {
    id: 'grok-2-vision-1212',
    displayName: 'Grok 2 Vision 1212',
    description: '该模型在准确性、指令遵循和多语言能力方面有所改进。',
    type: 'chat',
    contextWindowTokens: 32_768,
    abilities: { functionCall: true, search: true, vision: true },
    pricing: { input: 2, output: 10 },
    releasedAt: '2024-12-12',
  },
  {
    id: 'grok-2',
    displayName: 'Grok 2',
    description: 'Grok 2 是升级版本，提供更强的推理和对话能力。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    abilities: { functionCall: true, vision: true, structuredOutput: true },
    pricing: { input: 2, output: 10 },
  },
  {
    id: 'grok-beta',
    displayName: 'Grok Beta',
    description: 'Grok 是 xAI 的旗舰对话模型，具有实时知识和推理能力。',
    type: 'chat',
    contextWindowTokens: 131_072,
    maxOutput: 4_096,
    legacy: true,
    abilities: { functionCall: true, structuredOutput: true },
    pricing: { input: 5, output: 15 },
  },
  {
    id: 'grok-vision-beta',
    displayName: 'Grok Vision Beta',
    description: 'Grok Vision 支持图像理解和视觉分析。',
    type: 'chat',
    contextWindowTokens: 8_192,
    maxOutput: 4_096,
    legacy: true,
    abilities: { functionCall: true, vision: true },
    pricing: { input: 5, output: 15 },
  },
];

const xaiImageModels: ImageModelCard[] = [
  {
    id: 'grok-imagine-image-quality',
    displayName: 'Grok Imagine Image Quality',
    description: 'xAI 高质量图像生成模型，支持文生图、自然语言图像编辑与多轮迭代优化。',
    type: 'image',
    enabled: true,
    releasedAt: '2026-05-06',
  },
  {
    id: 'grok-imagine-image-pro',
    displayName: 'Grok Imagine Image Pro',
    description: 'xAI 专业图像生成模型，支持高质量、高分辨率的图像生成。',
    type: 'image',
    enabled: true,
    releasedAt: '2026-01-28',
  },
  {
    id: 'grok-imagine-image',
    displayName: 'Grok Imagine Image',
    description: 'xAI 图像生成模型，支持根据文本提示生成高质量图像。',
    type: 'image',
    enabled: true,
    releasedAt: '2026-01-28',
  },
  {
    id: 'grok-2-image-1212',
    displayName: 'Grok 2 Image 1212',
    description:
      '我们最新的图像生成模型可以根据文本提示生成生动逼真的图像。它在营销、社交媒体和娱乐等领域的图像生成方面表现出色。',
    type: 'image',
    enabled: true,
    releasedAt: '2024-12-12',
  },
];

const xaiVideoModels: VideoModelCard[] = [
  {
    id: 'grok-imagine-video',
    displayName: 'Grok Imagine Video',
    description: 'xAI 视频生成模型，支持根据文本提示生成高质量视频。',
    type: 'video',
    enabled: true,
    abilities: { videoOutput: true },
    releasedAt: '2026-01-28',
  },
];

export default {
  chat: xaiChatModels,
  image: xaiImageModels,
  video: xaiVideoModels,
};
